# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = './llvm/test/CodeGen/Xtensa/GlobalISel/llvm-ir/alloca.ll'
  source_filename = "./llvm/test/CodeGen/Xtensa/GlobalISel/llvm-ir/alloca.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i8 @alloca_i8(i8 %val) {
    %p = alloca i8, align 1
    store i8 %val, ptr %p, align 1
    %retval = load i8, ptr %p, align 1
    ret i8 %retval
  }

  define i16 @alloca_i16(i16 %val) {
    %p = alloca i16, align 2
    store i16 %val, ptr %p, align 2
    %retval = load i16, ptr %p, align 2
    ret i16 %retval
  }

  define i32 @alloca_i32(i32 %val) {
    %p = alloca i32, align 4
    store i32 %val, ptr %p, align 4
    %retval = load i32, ptr %p, align 4
    ret i32 %retval
  }

  define i64 @alloca_i64(i64 %val) {
    %p = alloca i64, align 8
    store i64 %val, ptr %p, align 8
    %retval = load i64, ptr %p, align 8
    ret i64 %retval
  }

...
---
name:            alloca_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 1, alignment: 1,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_i8
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: S8I [[COPY]], %stack.0.p, 0 :: (store (s8) into %ir.p)
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI %stack.0.p, 0 :: (dereferenceable load (s8) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L8UI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %1:gprb(s32) = COPY $a2
    %2:gprb(p0) = G_FRAME_INDEX %stack.0.p
    G_STORE %1(s32), %2(p0) :: (store (s8) into %ir.p)
    %5:gprb(s32) = G_LOAD %2(p0) :: (dereferenceable load (s8) from %ir.p)
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            alloca_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    2
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 2, alignment: 2,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_i16
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: S16I [[COPY]], %stack.0.p, 0 :: (store (s16) into %ir.p)
    ; CHECK-NEXT: [[L16UI:%[0-9]+]]:gpr = L16UI %stack.0.p, 0 :: (dereferenceable load (s16) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L16UI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %1:gprb(s32) = COPY $a2
    %2:gprb(p0) = G_FRAME_INDEX %stack.0.p
    G_STORE %1(s32), %2(p0) :: (store (s16) into %ir.p)
    %5:gprb(s32) = G_LOAD %2(p0) :: (dereferenceable load (s16) from %ir.p)
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            alloca_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_i32
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: S32I [[COPY]], %stack.0.p, 0 :: (store (s32) into %ir.p)
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I %stack.0.p, 0 :: (dereferenceable load (s32) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(p0) = G_FRAME_INDEX %stack.0.p
    G_STORE %0(s32), %1(p0) :: (store (s32) into %ir.p)
    %2:gprb(s32) = G_LOAD %1(p0) :: (dereferenceable load (s32) from %ir.p)
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            alloca_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    8
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 8, alignment: 8,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: alloca_i64
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: S32I [[COPY]], %stack.0.p, 0 :: (store (s32) into %ir.p, align 8)
    ; CHECK-NEXT: S32I [[COPY1]], %stack.0.p, 4 :: (store (s32) into %ir.p + 4, basealign 8)
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I %stack.0.p, 0 :: (dereferenceable load (s32) from %ir.p, align 8)
    ; CHECK-NEXT: [[L32I1:%[0-9]+]]:gpr = L32I %stack.0.p, 4 :: (dereferenceable load (s32) from %ir.p + 4, basealign 8)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: $a3 = COPY [[L32I1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %3:gprb(p0) = G_FRAME_INDEX %stack.0.p
    G_STORE %1(s32), %3(p0) :: (store (s32) into %ir.p, align 8)
    %14:gprb(s32) = G_CONSTANT i32 4
    %13:gprb(p0) = G_PTR_ADD %3, %14(s32)
    G_STORE %2(s32), %13(p0) :: (store (s32) into %ir.p + 4, basealign 8)
    %7:gprb(s32) = G_LOAD %3(p0) :: (dereferenceable load (s32) from %ir.p, align 8)
    %9:gprb(s32) = G_CONSTANT i32 4
    %8:gprb(p0) = G_PTR_ADD %3, %9(s32)
    %10:gprb(s32) = G_LOAD %8(p0) :: (dereferenceable load (s32) from %ir.p + 4, basealign 8)
    $a2 = COPY %7(s32)
    $a3 = COPY %10(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
