# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
# RUN: llc -O0 -mtriple=xtensa -mcpu=lx7 -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=LX7
--- |
  ; ModuleID = 'llvm/test/CodeGen/Xtensa/GlobalISel/regbankselect/icmp.mir'
  source_filename = "icmp.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i1 @icmp_eq_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp eq i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_ne_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp ne i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_eqz_i32(i32 %a) {
  entry:
    %icmp = icmp eq i32 %a, 0
    ret i1 %icmp
  }

  define i1 @icmp_nez_i32(i32 %a) {
  entry:
    %icmp = icmp ne i32 %a, 0
    ret i1 %icmp
  }

  define i1 @icmp_slt_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp slt i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_sle_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp sle i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_sgt_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp sgt i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_sge_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp sge i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_sltz_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp slt i32 %a, 0
    ret i1 %icmp
  }

  define i1 @icmp_slez_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp slt i32 %a, 1
    ret i1 %icmp
  }

  define i1 @icmp_sgtz_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp sgt i32 %a, 0
    ret i1 %icmp
  }

  define i1 @icmp_sgez_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp sgt i32 %a, -1
    ret i1 %icmp
  }

  define i1 @icmp_ult_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp ult i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_ule_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp ule i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_ugt_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp ugt i32 %a, %b
    ret i1 %icmp
  }

  define i1 @icmp_uge_i32(i32 %a, i32 %b) {
  entry:
    %icmp = icmp uge i32 %a, %b
    ret i1 %icmp
  }

...
---
name:            icmp_eq_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_eq_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI]], [[MOVI1]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVEQZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_eq_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; LX7-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; LX7-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI]], [[MOVI1]], [[SUB]]
    ; LX7-NEXT: $a2 = COPY [[MOVEQZ]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(eq), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_ne_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_ne_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI1]], [[MOVI]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVEQZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_ne_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; LX7-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; LX7-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI1]], [[MOVI]], [[SUB]]
    ; LX7-NEXT: $a2 = COPY [[MOVEQZ]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(ne), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_eqz_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2

    ; CHECK-LABEL: name: icmp_eqz_i32
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI]], [[MOVI1]], [[COPY]]
    ; CHECK-NEXT: $a2 = COPY [[MOVEQZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_eqz_i32
    ; LX7: liveins: $a2
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; LX7-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI]], [[MOVI1]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[MOVEQZ]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = G_CONSTANT i32 0
    %4:gprb(s32) = G_ICMP intpred(eq), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_nez_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2

    ; CHECK-LABEL: name: icmp_nez_i32
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI1]], [[MOVI]], [[COPY]]
    ; CHECK-NEXT: $a2 = COPY [[MOVEQZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_nez_i32
    ; LX7: liveins: $a2
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; LX7-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[MOVEQZ:%[0-9]+]]:gpr = MOVEQZ [[MOVI1]], [[MOVI]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[MOVEQZ]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = G_CONSTANT i32 0
    %4:gprb(s32) = G_ICMP intpred(ne), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_slt_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_slt_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI1]], [[MOVI]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_slt_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[COPY]], [[COPY1]]
    ; LX7-NEXT: $a2 = COPY [[SALT]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(slt), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sle_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sle_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY1]], [[COPY]]
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI]], [[MOVI1]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sle_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[COPY1]], [[COPY]]
    ; LX7-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[SALT]], [[MOVI]]
    ; LX7-NEXT: $a2 = COPY [[XOR]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(sle), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sgt_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sgt_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY1]], [[COPY]]
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI1]], [[MOVI]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sgt_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[COPY1]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[SALT]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(sgt), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sge_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sge_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gpr = SUB [[COPY]], [[COPY1]]
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI]], [[MOVI1]], [[SUB]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sge_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[COPY]], [[COPY1]]
    ; LX7-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[SALT]], [[MOVI]]
    ; LX7-NEXT: $a2 = COPY [[XOR]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(sge), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sltz_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sltz_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY]], 31, 1
    ; CHECK-NEXT: $a2 = COPY [[EXTUI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sltz_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY]], 31, 1
    ; LX7-NEXT: $a2 = COPY [[EXTUI]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %2:gprb(s32) = G_CONSTANT i32 0
    %5:gprb(s32) = G_ICMP intpred(slt), %0(s32), %2
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_slez_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_slez_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], -1
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI1]], [[MOVI]], [[ADDI]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_slez_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[COPY]], [[MOVI]]
    ; LX7-NEXT: $a2 = COPY [[SALT]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %2:gprb(s32) = G_CONSTANT i32 1
    %5:gprb(s32) = G_ICMP intpred(slt), %0(s32), %2
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sgtz_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sgtz_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], -1
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI]], [[MOVI1]], [[ADDI]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sgtz_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[MOVI]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[SALT]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %2:gprb(s32) = G_CONSTANT i32 0
    %5:gprb(s32) = G_ICMP intpred(sgt), %0(s32), %2
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_sgez_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_sgez_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[MOVGEZ:%[0-9]+]]:gpr = MOVGEZ [[MOVI]], [[MOVI1]], [[COPY]]
    ; CHECK-NEXT: $a2 = COPY [[MOVGEZ]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_sgez_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI -1
    ; LX7-NEXT: [[SALT:%[0-9]+]]:gpr = SALT [[MOVI]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[SALT]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %2:gprb(s32) = G_CONSTANT i32 -1
    %5:gprb(s32) = G_ICMP intpred(sgt), %0(s32), %2
    $a2 = COPY %5(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_ult_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_ult_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SELECT_LTU:%[0-9]+]]:gpr = SELECT_LTU [[COPY]], [[COPY1]], [[MOVI1]], [[MOVI]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT_LTU]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_ult_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[SALTU:%[0-9]+]]:gpr = SALTU [[COPY]], [[COPY1]]
    ; LX7-NEXT: $a2 = COPY [[SALTU]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(ult), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_ule_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_ule_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SELECT_LTU:%[0-9]+]]:gpr = SELECT_LTU [[COPY1]], [[COPY]], [[MOVI]], [[MOVI1]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT_LTU]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_ule_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SALTU:%[0-9]+]]:gpr = SALTU [[COPY1]], [[COPY]]
    ; LX7-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[SALTU]], [[MOVI]]
    ; LX7-NEXT: $a2 = COPY [[XOR]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(ule), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_ugt_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_ugt_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SELECT_LTU:%[0-9]+]]:gpr = SELECT_LTU [[COPY1]], [[COPY]], [[MOVI1]], [[MOVI]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT_LTU]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_ugt_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[SALTU:%[0-9]+]]:gpr = SALTU [[COPY1]], [[COPY]]
    ; LX7-NEXT: $a2 = COPY [[SALTU]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(ugt), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            icmp_uge_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: icmp_uge_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 1
    ; CHECK-NEXT: [[SELECT_LTU:%[0-9]+]]:gpr = SELECT_LTU [[COPY]], [[COPY1]], [[MOVI]], [[MOVI1]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT_LTU]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    ; LX7-LABEL: name: icmp_uge_i32
    ; LX7: liveins: $a2, $a3
    ; LX7-NEXT: {{  $}}
    ; LX7-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; LX7-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; LX7-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 1
    ; LX7-NEXT: [[SALTU:%[0-9]+]]:gpr = SALTU [[COPY]], [[COPY1]]
    ; LX7-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[SALTU]], [[MOVI]]
    ; LX7-NEXT: $a2 = COPY [[XOR]]
    ; LX7-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    %4:gprb(s32) = G_ICMP intpred(uge), %0(s32), %1
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
