# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'jumptable.ll'
  source_filename = "jumptable.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  declare i32 @func(i32 noundef)

  define i32 @test(i32 %a) {
  entry:
    switch i32 %a, label %sw.default [
      i32 0, label %return
      i32 1, label %sw.bb1
      i32 2, label %sw.bb2
      i32 3, label %sw.bb3
      i32 4, label %sw.bb4
      i32 5, label %sw.bb5
      i32 6, label %sw.bb6
      i32 7, label %sw.bb7
      i32 8, label %sw.bb8
      i32 9, label %sw.bb9
      i32 10, label %sw.bb10
      i32 11, label %sw.bb11
      i32 12, label %sw.bb12
      i32 13, label %sw.bb13
      i32 14, label %sw.bb14
    ]

  sw.bb1:                                           ; preds = %entry
    %call = tail call i32 @func(i32 17)
    br label %return

  sw.bb2:                                           ; preds = %entry
    br label %return

  sw.bb3:                                           ; preds = %entry
    br label %return

  sw.bb4:                                           ; preds = %entry
    br label %return

  sw.bb5:                                           ; preds = %entry
    br label %return

  sw.bb6:                                           ; preds = %entry
    br label %return

  sw.bb7:                                           ; preds = %entry
    br label %return

  sw.bb8:                                           ; preds = %entry
    br label %return

  sw.bb9:                                           ; preds = %entry
    br label %return

  sw.bb10:                                          ; preds = %entry
    br label %return

  sw.bb11:                                          ; preds = %entry
    br label %return

  sw.bb12:                                          ; preds = %entry
    br label %return

  sw.bb13:                                          ; preds = %entry
    br label %return

  sw.bb14:                                          ; preds = %entry
    br label %return

  sw.default:                                       ; preds = %entry
    br label %return

  return:                                           ; preds = %sw.default, %sw.bb14, %sw.bb13, %sw.bb12, %sw.bb11, %sw.bb10, %sw.bb9, %sw.bb8, %sw.bb7, %sw.bb6, %sw.bb5, %sw.bb4, %sw.bb3, %sw.bb2, %sw.bb1, %entry
    %retval.0 = phi i32 [ 8, %sw.default ], [ 15, %sw.bb14 ], [ -1, %sw.bb13 ], [ 144, %sw.bb12 ], [ 666, %sw.bb11 ], [ 700, %sw.bb10 ], [ 20, %sw.bb9 ], [ 18, %sw.bb8 ], [ 90, %sw.bb7 ], [ 100, %sw.bb6 ], [ 7, %sw.bb5 ], [ -92, %sw.bb4 ], [ 553, %sw.bb3 ], [ 28, %sw.bb2 ], [ %call, %sw.bb1 ], [ 5, %entry ]
    ret i32 %retval.0
  }

...
---
name:            test
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: gprb, preferred-register: '' }
  - { id: 18, class: gprb, preferred-register: '' }
  - { id: 19, class: gprb, preferred-register: '' }
  - { id: 20, class: gprb, preferred-register: '' }
  - { id: 21, class: gprb, preferred-register: '' }
  - { id: 22, class: gprb, preferred-register: '' }
  - { id: 23, class: gprb, preferred-register: '' }
  - { id: 24, class: gprb, preferred-register: '' }
  - { id: 25, class: gprb, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: gprb, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: gprb, preferred-register: '' }
  - { id: 30, class: gprb, preferred-register: '' }
  - { id: 31, class: gprb, preferred-register: '' }
  - { id: 32, class: gprb, preferred-register: '' }
  - { id: 33, class: gprb, preferred-register: '' }
  - { id: 34, class: gprb, preferred-register: '' }
  - { id: 35, class: gprb, preferred-register: '' }
  - { id: 36, class: gprb, preferred-register: '' }
  - { id: 37, class: gprb, preferred-register: '' }
  - { id: 38, class: gprb, preferred-register: '' }
  - { id: 39, class: gprb, preferred-register: '' }
  - { id: 40, class: gprb, preferred-register: '' }
  - { id: 41, class: gprb, preferred-register: '' }
  - { id: 42, class: gprb, preferred-register: '' }
  - { id: 43, class: gprb, preferred-register: '' }
  - { id: 44, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.17', '%bb.2', '%bb.3', '%bb.4', '%bb.5',
                         '%bb.6', '%bb.7', '%bb.8', '%bb.9', '%bb.10',
                         '%bb.11', '%bb.12', '%bb.13', '%bb.14', '%bb.15' ]
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.16(0x08000000), %bb.1(0x78000000)
  ; CHECK-NEXT:   liveins: $a2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $a2
  ; CHECK-NEXT:   [[MOVI:%[0-9]+]]:gpr = MOVI 14
  ; CHECK-NEXT:   BLTU [[MOVI]], [[COPY]], %bb.16
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.17(0x08888889), %bb.2(0x08888889), %bb.3(0x08888889), %bb.4(0x08888889), %bb.5(0x08888889), %bb.6(0x08888889), %bb.7(0x08888889), %bb.8(0x08888889), %bb.9(0x08888889), %bb.10(0x08888889), %bb.11(0x08888889), %bb.12(0x08888889), %bb.13(0x08888889), %bb.14(0x08888889), %bb.15(0x08888889)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI1:%[0-9]+]]:gpr = MOVI 5
  ; CHECK-NEXT:   [[L32R:%[0-9]+]]:gpr = L32R %const.0 :: (load (s32) from constant-pool)
  ; CHECK-NEXT:   JUMPTABLE_USED %jump-table.0
  ; CHECK-NEXT:   [[ADDX4_:%[0-9]+]]:gpr = ADDX4 [[COPY]], [[L32R]]
  ; CHECK-NEXT:   [[L32I:%[0-9]+]]:gpr = L32I [[ADDX4_]], 0 :: (load (s32) from jump-table)
  ; CHECK-NEXT:   JX [[L32I]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.sw.bb1:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
  ; CHECK-NEXT:   [[MOVI2:%[0-9]+]]:gpr = MOVI 17
  ; CHECK-NEXT:   $a2 = COPY [[MOVI2]]
  ; CHECK-NEXT:   CALL0 @func, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit-def $a2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $a2
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.sw.bb2:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI3:%[0-9]+]]:gpr = MOVI 28
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4.sw.bb3:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI4:%[0-9]+]]:gpr = MOVI 553
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5.sw.bb4:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI5:%[0-9]+]]:gpr = MOVI -92
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6.sw.bb5:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI6:%[0-9]+]]:gpr = MOVI 7
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.7.sw.bb6:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI7:%[0-9]+]]:gpr = MOVI 100
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.8.sw.bb7:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI8:%[0-9]+]]:gpr = MOVI 90
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.9.sw.bb8:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI9:%[0-9]+]]:gpr = MOVI 18
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.10.sw.bb9:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI10:%[0-9]+]]:gpr = MOVI 20
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.11.sw.bb10:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI11:%[0-9]+]]:gpr = MOVI 700
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.12.sw.bb11:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI12:%[0-9]+]]:gpr = MOVI 666
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.13.sw.bb12:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI13:%[0-9]+]]:gpr = MOVI 144
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.14.sw.bb13:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI14:%[0-9]+]]:gpr = MOVI -1
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.15.sw.bb14:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI15:%[0-9]+]]:gpr = MOVI 15
  ; CHECK-NEXT:   J %bb.17
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.16.sw.default:
  ; CHECK-NEXT:   successors: %bb.17(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVI16:%[0-9]+]]:gpr = MOVI 8
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.17.return:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[MOVI16]], %bb.16, [[MOVI15]], %bb.15, [[MOVI14]], %bb.14, [[MOVI13]], %bb.13, [[MOVI12]], %bb.12, [[MOVI11]], %bb.11, [[MOVI10]], %bb.10, [[MOVI9]], %bb.9, [[MOVI8]], %bb.8, [[MOVI7]], %bb.7, [[MOVI6]], %bb.6, [[MOVI5]], %bb.5, [[MOVI4]], %bb.4, [[MOVI3]], %bb.3, [[COPY1]], %bb.2, [[MOVI1]], %bb.1
  ; CHECK-NEXT:   $a2 = COPY [[PHI]]
  ; CHECK-NEXT:   RETN implicit $a0, implicit $a2
  bb.1.entry:
    successors: %bb.16(0x08000000), %bb.18(0x78000000)
    liveins: $a2

    %0:gprb(s32) = COPY $a2
    %9:gprb(s32) = G_CONSTANT i32 17
    %11:gprb(s32) = G_CONSTANT i32 8
    %12:gprb(s32) = G_CONSTANT i32 15
    %13:gprb(s32) = G_CONSTANT i32 -1
    %14:gprb(s32) = G_CONSTANT i32 144
    %15:gprb(s32) = G_CONSTANT i32 666
    %16:gprb(s32) = G_CONSTANT i32 700
    %17:gprb(s32) = G_CONSTANT i32 20
    %18:gprb(s32) = G_CONSTANT i32 18
    %19:gprb(s32) = G_CONSTANT i32 90
    %20:gprb(s32) = G_CONSTANT i32 100
    %21:gprb(s32) = G_CONSTANT i32 7
    %22:gprb(s32) = G_CONSTANT i32 -92
    %23:gprb(s32) = G_CONSTANT i32 553
    %24:gprb(s32) = G_CONSTANT i32 28
    %25:gprb(s32) = G_CONSTANT i32 5
    %4:gprb(s32) = G_CONSTANT i32 14
    %27:gprb(s32) = G_ICMP intpred(ugt), %0(s32), %4
    G_BRCOND %27(s32), %bb.16

  bb.18.entry:
    successors: %bb.17(0x08888889), %bb.2(0x08888889), %bb.3(0x08888889), %bb.4(0x08888889), %bb.5(0x08888889), %bb.6(0x08888889), %bb.7(0x08888889), %bb.8(0x08888889), %bb.9(0x08888889), %bb.10(0x08888889), %bb.11(0x08888889), %bb.12(0x08888889), %bb.13(0x08888889), %bb.14(0x08888889), %bb.15(0x08888889)

    %29:gprb(s32) = G_CONSTANT i32 5
    %7:gprb(p0) = G_JUMP_TABLE %jump-table.0
    G_BRJT %7(p0), %jump-table.0, %0(s32)

  bb.2.sw.bb1:
    successors: %bb.17(0x80000000)

    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    %44:gprb(s32) = G_CONSTANT i32 17
    $a2 = COPY %44(s32)
    CALL0 @func, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit-def $a2
    %8:gprb(s32) = COPY $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    G_BR %bb.17

  bb.3.sw.bb2:
    successors: %bb.17(0x80000000)

    %30:gprb(s32) = G_CONSTANT i32 28
    G_BR %bb.17

  bb.4.sw.bb3:
    successors: %bb.17(0x80000000)

    %31:gprb(s32) = G_CONSTANT i32 553
    G_BR %bb.17

  bb.5.sw.bb4:
    successors: %bb.17(0x80000000)

    %32:gprb(s32) = G_CONSTANT i32 -92
    G_BR %bb.17

  bb.6.sw.bb5:
    successors: %bb.17(0x80000000)

    %33:gprb(s32) = G_CONSTANT i32 7
    G_BR %bb.17

  bb.7.sw.bb6:
    successors: %bb.17(0x80000000)

    %34:gprb(s32) = G_CONSTANT i32 100
    G_BR %bb.17

  bb.8.sw.bb7:
    successors: %bb.17(0x80000000)

    %35:gprb(s32) = G_CONSTANT i32 90
    G_BR %bb.17

  bb.9.sw.bb8:
    successors: %bb.17(0x80000000)

    %36:gprb(s32) = G_CONSTANT i32 18
    G_BR %bb.17

  bb.10.sw.bb9:
    successors: %bb.17(0x80000000)

    %37:gprb(s32) = G_CONSTANT i32 20
    G_BR %bb.17

  bb.11.sw.bb10:
    successors: %bb.17(0x80000000)

    %38:gprb(s32) = G_CONSTANT i32 700
    G_BR %bb.17

  bb.12.sw.bb11:
    successors: %bb.17(0x80000000)

    %39:gprb(s32) = G_CONSTANT i32 666
    G_BR %bb.17

  bb.13.sw.bb12:
    successors: %bb.17(0x80000000)

    %40:gprb(s32) = G_CONSTANT i32 144
    G_BR %bb.17

  bb.14.sw.bb13:
    successors: %bb.17(0x80000000)

    %41:gprb(s32) = G_CONSTANT i32 -1
    G_BR %bb.17

  bb.15.sw.bb14:
    successors: %bb.17(0x80000000)

    %42:gprb(s32) = G_CONSTANT i32 15
    G_BR %bb.17

  bb.16.sw.default:
    successors: %bb.17(0x80000000)

    %43:gprb(s32) = G_CONSTANT i32 8

  bb.17.return:
    %10:gprb(s32) = G_PHI %43(s32), %bb.16, %42(s32), %bb.15, %41(s32), %bb.14, %40(s32), %bb.13, %39(s32), %bb.12, %38(s32), %bb.11, %37(s32), %bb.10, %36(s32), %bb.9, %35(s32), %bb.8, %34(s32), %bb.7, %33(s32), %bb.6, %32(s32), %bb.5, %31(s32), %bb.4, %30(s32), %bb.3, %8(s32), %bb.2, %29(s32), %bb.18
    $a2 = COPY %10(s32)
    RETN implicit $a0, implicit $a2

...
