# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'load.ll'
  source_filename = "load.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i8 @load_i8(ptr %p) {
  entry:
    %load = load i8, ptr %p, align 1
    ret i8 %load
  }

  define i16 @load_i16(ptr %p) {
  entry:
    %load = load i16, ptr %p, align 2
    ret i16 %load
  }

  define i16 @load_i16_unaligned_1(ptr %p) {
  entry:
    %load = load i16, ptr %p, align 1
    ret i16 %load
  }

  define i32 @load_i32(ptr %p) {
  entry:
    %load = load i32, ptr %p, align 4
    ret i32 %load
  }

  define i32 @load_i32_unaligned_1(ptr %p) {
  entry:
    %load = load i32, ptr %p, align 1
    ret i32 %load
  }

  define i32 @load_i32_unaligned_2(ptr %p) {
  entry:
    %load = load i32, ptr %p, align 2
    ret i32 %load
  }

  define i64 @load_i64(ptr %p) {
  entry:
    %load = load i64, ptr %p, align 8
    ret i64 %load
  }

  define i64 @load_i64_unaligned_1(ptr %p) {
  entry:
    %load = load i64, ptr %p, align 1
    ret i64 %load
  }

  define i64 @load_i64_unaligned_2(ptr %p) {
  entry:
    %load = load i64, ptr %p, align 2
    ret i64 %load
  }

  define i64 @load_i64_unaligned_4(ptr %p) {
  entry:
    %load = load i64, ptr %p, align 4
    ret i64 %load
  }

  define ptr @load_ptr(ptr %p) {
  entry:
    %load = load ptr, ptr %p, align 4
    ret ptr %load
  }

  define ptr @load_ptr_unaligned_1(ptr %p) {
  entry:
    %load = load ptr, ptr %p, align 1
    ret ptr %load
  }

  define ptr @load_ptr_unaligned_2(ptr %p) {
  entry:
    %load = load ptr, ptr %p, align 2
    ret ptr %load
  }

...
---
name:            load_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i8
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI [[COPY]], 0 :: (load (s8) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L8UI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %3:gprb(s32) = G_LOAD %0(p0) :: (load (s8) from %ir.p)
    $a2 = COPY %3(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i16
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L16UI:%[0-9]+]]:gpr = L16UI [[COPY]], 0 :: (load (s16) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L16UI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %3:gprb(s32) = G_LOAD %0(p0) :: (load (s16) from %ir.p)
    $a2 = COPY %3(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i16_unaligned_1
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i16_unaligned_1
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI [[COPY]], 0 :: (load (s8) from %ir.p)
    ; CHECK-NEXT: [[L8UI1:%[0-9]+]]:gpr = L8UI [[COPY]], 1 :: (load (s8) from %ir.p + 1)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L8UI1]], 8
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L8UI]]
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %4:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s8) from %ir.p)
    %5:gprb(s32) = G_CONSTANT i32 1
    %6:gprb(p0) = G_PTR_ADD %0, %5(s32)
    %7:gprb(s32) = G_LOAD %6(p0) :: (load (s8) from %ir.p + 1)
    %8:gprb(s32) = G_CONSTANT i32 8
    %9:gprb(s32) = G_SHL %7, %8(s32)
    %3:gprb(s32) = G_OR %9, %4
    $a2 = COPY %3(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i32
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I [[COPY]], 0 :: (load (s32) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %1:gprb(s32) = G_LOAD %0(p0) :: (load (s32) from %ir.p)
    $a2 = COPY %1(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i32_unaligned_1
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: gprb, preferred-register: '' }
  - { id: 18, class: gprb, preferred-register: '' }
  - { id: 19, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i32_unaligned_1
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI [[COPY]], 0 :: (load (s8) from %ir.p)
    ; CHECK-NEXT: [[L8UI1:%[0-9]+]]:gpr = L8UI [[COPY]], 1 :: (load (s8) from %ir.p + 1)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L8UI1]], 8
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L8UI]]
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 2
    ; CHECK-NEXT: [[L8UI2:%[0-9]+]]:gpr = L8UI [[COPY]], 2 :: (load (s8) from %ir.p + 2)
    ; CHECK-NEXT: [[L8UI3:%[0-9]+]]:gpr = L8UI [[ADDI]], 1 :: (load (s8) from %ir.p + 3)
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[L8UI3]], 8
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gpr = OR [[SLLI1]], [[L8UI2]]
    ; CHECK-NEXT: [[SLLI2:%[0-9]+]]:gpr = SLLI [[OR1]], 16
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:gpr = OR [[SLLI2]], [[OR]]
    ; CHECK-NEXT: $a2 = COPY [[OR2]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %14:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s8) from %ir.p)
    %15:gprb(s32) = G_CONSTANT i32 1
    %16:gprb(p0) = G_PTR_ADD %0, %15(s32)
    %17:gprb(s32) = G_ZEXTLOAD %16(p0) :: (load (s8) from %ir.p + 1)
    %18:gprb(s32) = G_CONSTANT i32 8
    %19:gprb(s32) = G_SHL %17, %18(s32)
    %2:gprb(s32) = G_OR %19, %14
    %3:gprb(s32) = G_CONSTANT i32 2
    %4:gprb(p0) = G_PTR_ADD %0, %3(s32)
    %8:gprb(s32) = G_ZEXTLOAD %4(p0) :: (load (s8) from %ir.p + 2)
    %9:gprb(s32) = G_CONSTANT i32 1
    %10:gprb(p0) = G_PTR_ADD %4, %9(s32)
    %11:gprb(s32) = G_LOAD %10(p0) :: (load (s8) from %ir.p + 3)
    %12:gprb(s32) = G_CONSTANT i32 8
    %13:gprb(s32) = G_SHL %11, %12(s32)
    %5:gprb(s32) = G_OR %13, %8
    %6:gprb(s32) = G_CONSTANT i32 16
    %7:gprb(s32) = G_SHL %5, %6(s32)
    %1:gprb(s32) = G_OR %7, %2
    $a2 = COPY %1(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i32_unaligned_2
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i32_unaligned_2
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L16UI:%[0-9]+]]:gpr = L16UI [[COPY]], 0 :: (load (s16) from %ir.p)
    ; CHECK-NEXT: [[L16UI1:%[0-9]+]]:gpr = L16UI [[COPY]], 2 :: (load (s16) from %ir.p + 2)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L16UI1]], 16
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L16UI]]
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %2:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s16) from %ir.p)
    %3:gprb(s32) = G_CONSTANT i32 2
    %4:gprb(p0) = G_PTR_ADD %0, %3(s32)
    %5:gprb(s32) = G_LOAD %4(p0) :: (load (s16) from %ir.p + 2)
    %6:gprb(s32) = G_CONSTANT i32 16
    %7:gprb(s32) = G_SHL %5, %6(s32)
    %1:gprb(s32) = G_OR %7, %2
    $a2 = COPY %1(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            load_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i64
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I [[COPY]], 0 :: (load (s32) from %ir.p, align 8)
    ; CHECK-NEXT: [[L32I1:%[0-9]+]]:gpr = L32I [[COPY]], 4 :: (load (s32) from %ir.p + 4, basealign 8)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: $a3 = COPY [[L32I1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %0:gprb(p0) = COPY $a2
    %4:gprb(s32) = G_LOAD %0(p0) :: (load (s32) from %ir.p, align 8)
    %6:gprb(s32) = G_CONSTANT i32 4
    %5:gprb(p0) = G_PTR_ADD %0, %6(s32)
    %7:gprb(s32) = G_LOAD %5(p0) :: (load (s32) from %ir.p + 4, basealign 8)
    $a2 = COPY %4(s32)
    $a3 = COPY %7(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            load_i64_unaligned_1
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: gprb, preferred-register: '' }
  - { id: 18, class: gprb, preferred-register: '' }
  - { id: 19, class: gprb, preferred-register: '' }
  - { id: 20, class: gprb, preferred-register: '' }
  - { id: 21, class: gprb, preferred-register: '' }
  - { id: 22, class: gprb, preferred-register: '' }
  - { id: 23, class: gprb, preferred-register: '' }
  - { id: 24, class: gprb, preferred-register: '' }
  - { id: 25, class: gprb, preferred-register: '' }
  - { id: 26, class: gprb, preferred-register: '' }
  - { id: 27, class: gprb, preferred-register: '' }
  - { id: 28, class: gprb, preferred-register: '' }
  - { id: 29, class: gprb, preferred-register: '' }
  - { id: 30, class: gprb, preferred-register: '' }
  - { id: 31, class: gprb, preferred-register: '' }
  - { id: 32, class: gprb, preferred-register: '' }
  - { id: 33, class: gprb, preferred-register: '' }
  - { id: 34, class: gprb, preferred-register: '' }
  - { id: 35, class: gprb, preferred-register: '' }
  - { id: 36, class: gprb, preferred-register: '' }
  - { id: 37, class: gprb, preferred-register: '' }
  - { id: 38, class: gprb, preferred-register: '' }
  - { id: 39, class: gprb, preferred-register: '' }
  - { id: 40, class: gprb, preferred-register: '' }
  - { id: 41, class: gprb, preferred-register: '' }
  - { id: 42, class: gprb, preferred-register: '' }
  - { id: 43, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i64_unaligned_1
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI [[COPY]], 0 :: (load (s8) from %ir.p)
    ; CHECK-NEXT: [[L8UI1:%[0-9]+]]:gpr = L8UI [[COPY]], 1 :: (load (s8) from %ir.p + 1)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L8UI1]], 8
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L8UI]]
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 2
    ; CHECK-NEXT: [[L8UI2:%[0-9]+]]:gpr = L8UI [[COPY]], 2 :: (load (s8) from %ir.p + 2)
    ; CHECK-NEXT: [[L8UI3:%[0-9]+]]:gpr = L8UI [[ADDI]], 1 :: (load (s8) from %ir.p + 3)
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[L8UI3]], 8
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gpr = OR [[SLLI1]], [[L8UI2]]
    ; CHECK-NEXT: [[SLLI2:%[0-9]+]]:gpr = SLLI [[OR1]], 16
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:gpr = OR [[SLLI2]], [[OR]]
    ; CHECK-NEXT: [[ADDI1:%[0-9]+]]:gpr = ADDI [[COPY]], 4
    ; CHECK-NEXT: [[L8UI4:%[0-9]+]]:gpr = L8UI [[COPY]], 4 :: (load (s8) from %ir.p + 4)
    ; CHECK-NEXT: [[L8UI5:%[0-9]+]]:gpr = L8UI [[ADDI1]], 1 :: (load (s8) from %ir.p + 5)
    ; CHECK-NEXT: [[SLLI3:%[0-9]+]]:gpr = SLLI [[L8UI5]], 8
    ; CHECK-NEXT: [[OR3:%[0-9]+]]:gpr = OR [[SLLI3]], [[L8UI4]]
    ; CHECK-NEXT: [[ADDI2:%[0-9]+]]:gpr = ADDI [[ADDI1]], 2
    ; CHECK-NEXT: [[L8UI6:%[0-9]+]]:gpr = L8UI [[ADDI1]], 2 :: (load (s8) from %ir.p + 6)
    ; CHECK-NEXT: [[L8UI7:%[0-9]+]]:gpr = L8UI [[ADDI2]], 1 :: (load (s8) from %ir.p + 7)
    ; CHECK-NEXT: [[SLLI4:%[0-9]+]]:gpr = SLLI [[L8UI7]], 8
    ; CHECK-NEXT: [[OR4:%[0-9]+]]:gpr = OR [[SLLI4]], [[L8UI6]]
    ; CHECK-NEXT: [[SLLI5:%[0-9]+]]:gpr = SLLI [[OR4]], 16
    ; CHECK-NEXT: [[OR5:%[0-9]+]]:gpr = OR [[SLLI5]], [[OR3]]
    ; CHECK-NEXT: $a2 = COPY [[OR2]]
    ; CHECK-NEXT: $a3 = COPY [[OR5]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %0:gprb(p0) = COPY $a2
    %38:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s8) from %ir.p)
    %39:gprb(s32) = G_CONSTANT i32 1
    %40:gprb(p0) = G_PTR_ADD %0, %39(s32)
    %41:gprb(s32) = G_ZEXTLOAD %40(p0) :: (load (s8) from %ir.p + 1)
    %42:gprb(s32) = G_CONSTANT i32 8
    %43:gprb(s32) = G_SHL %41, %42(s32)
    %26:gprb(s32) = G_OR %43, %38
    %27:gprb(s32) = G_CONSTANT i32 2
    %28:gprb(p0) = G_PTR_ADD %0, %27(s32)
    %32:gprb(s32) = G_ZEXTLOAD %28(p0) :: (load (s8) from %ir.p + 2)
    %33:gprb(s32) = G_CONSTANT i32 1
    %34:gprb(p0) = G_PTR_ADD %28, %33(s32)
    %35:gprb(s32) = G_LOAD %34(p0) :: (load (s8) from %ir.p + 3)
    %36:gprb(s32) = G_CONSTANT i32 8
    %37:gprb(s32) = G_SHL %35, %36(s32)
    %29:gprb(s32) = G_OR %37, %32
    %30:gprb(s32) = G_CONSTANT i32 16
    %31:gprb(s32) = G_SHL %29, %30(s32)
    %4:gprb(s32) = G_OR %31, %26
    %6:gprb(s32) = G_CONSTANT i32 4
    %5:gprb(p0) = G_PTR_ADD %0, %6(s32)
    %20:gprb(s32) = G_ZEXTLOAD %5(p0) :: (load (s8) from %ir.p + 4)
    %21:gprb(s32) = G_CONSTANT i32 1
    %22:gprb(p0) = G_PTR_ADD %5, %21(s32)
    %23:gprb(s32) = G_ZEXTLOAD %22(p0) :: (load (s8) from %ir.p + 5)
    %24:gprb(s32) = G_CONSTANT i32 8
    %25:gprb(s32) = G_SHL %23, %24(s32)
    %8:gprb(s32) = G_OR %25, %20
    %9:gprb(s32) = G_CONSTANT i32 2
    %10:gprb(p0) = G_PTR_ADD %5, %9(s32)
    %14:gprb(s32) = G_ZEXTLOAD %10(p0) :: (load (s8) from %ir.p + 6)
    %15:gprb(s32) = G_CONSTANT i32 1
    %16:gprb(p0) = G_PTR_ADD %10, %15(s32)
    %17:gprb(s32) = G_LOAD %16(p0) :: (load (s8) from %ir.p + 7)
    %18:gprb(s32) = G_CONSTANT i32 8
    %19:gprb(s32) = G_SHL %17, %18(s32)
    %11:gprb(s32) = G_OR %19, %14
    %12:gprb(s32) = G_CONSTANT i32 16
    %13:gprb(s32) = G_SHL %11, %12(s32)
    %7:gprb(s32) = G_OR %13, %8
    $a2 = COPY %4(s32)
    $a3 = COPY %7(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            load_i64_unaligned_2
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: gprb, preferred-register: '' }
  - { id: 18, class: gprb, preferred-register: '' }
  - { id: 19, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i64_unaligned_2
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L16UI:%[0-9]+]]:gpr = L16UI [[COPY]], 0 :: (load (s16) from %ir.p)
    ; CHECK-NEXT: [[L16UI1:%[0-9]+]]:gpr = L16UI [[COPY]], 2 :: (load (s16) from %ir.p + 2)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L16UI1]], 16
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L16UI]]
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 4
    ; CHECK-NEXT: [[L16UI2:%[0-9]+]]:gpr = L16UI [[COPY]], 4 :: (load (s16) from %ir.p + 4)
    ; CHECK-NEXT: [[L16UI3:%[0-9]+]]:gpr = L16UI [[ADDI]], 2 :: (load (s16) from %ir.p + 6)
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[L16UI3]], 16
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gpr = OR [[SLLI1]], [[L16UI2]]
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: $a3 = COPY [[OR1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %0:gprb(p0) = COPY $a2
    %14:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s16) from %ir.p)
    %15:gprb(s32) = G_CONSTANT i32 2
    %16:gprb(p0) = G_PTR_ADD %0, %15(s32)
    %17:gprb(s32) = G_LOAD %16(p0) :: (load (s16) from %ir.p + 2)
    %18:gprb(s32) = G_CONSTANT i32 16
    %19:gprb(s32) = G_SHL %17, %18(s32)
    %4:gprb(s32) = G_OR %19, %14
    %6:gprb(s32) = G_CONSTANT i32 4
    %5:gprb(p0) = G_PTR_ADD %0, %6(s32)
    %8:gprb(s32) = G_ZEXTLOAD %5(p0) :: (load (s16) from %ir.p + 4)
    %9:gprb(s32) = G_CONSTANT i32 2
    %10:gprb(p0) = G_PTR_ADD %5, %9(s32)
    %11:gprb(s32) = G_LOAD %10(p0) :: (load (s16) from %ir.p + 6)
    %12:gprb(s32) = G_CONSTANT i32 16
    %13:gprb(s32) = G_SHL %11, %12(s32)
    %7:gprb(s32) = G_OR %13, %8
    $a2 = COPY %4(s32)
    $a3 = COPY %7(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            load_i64_unaligned_4
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_i64_unaligned_4
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I [[COPY]], 0 :: (load (s32) from %ir.p)
    ; CHECK-NEXT: [[L32I1:%[0-9]+]]:gpr = L32I [[COPY]], 4 :: (load (s32) from %ir.p + 4)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: $a3 = COPY [[L32I1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %0:gprb(p0) = COPY $a2
    %4:gprb(s32) = G_LOAD %0(p0) :: (load (s32) from %ir.p)
    %6:gprb(s32) = G_CONSTANT i32 4
    %5:gprb(p0) = G_PTR_ADD %0, %6(s32)
    %7:gprb(s32) = G_LOAD %5(p0) :: (load (s32) from %ir.p + 4)
    $a2 = COPY %4(s32)
    $a3 = COPY %7(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            load_ptr
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_ptr
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L32I:%[0-9]+]]:gpr = L32I [[COPY]], 0 :: (load (p0) from %ir.p)
    ; CHECK-NEXT: $a2 = COPY [[L32I]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %1:gprb(p0) = G_LOAD %0(p0) :: (load (p0) from %ir.p)
    $a2 = COPY %1(p0)
    RETN implicit $a0, implicit $a2

...
---
name:            load_ptr_unaligned_1
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: gprb, preferred-register: '' }
  - { id: 18, class: gprb, preferred-register: '' }
  - { id: 19, class: gprb, preferred-register: '' }
  - { id: 20, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_ptr_unaligned_1
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L8UI:%[0-9]+]]:gpr = L8UI [[COPY]], 0 :: (load (s8) from %ir.p)
    ; CHECK-NEXT: [[L8UI1:%[0-9]+]]:gpr = L8UI [[COPY]], 1 :: (load (s8) from %ir.p + 1)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L8UI1]], 8
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L8UI]]
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 2
    ; CHECK-NEXT: [[L8UI2:%[0-9]+]]:gpr = L8UI [[COPY]], 2 :: (load (s8) from %ir.p + 2)
    ; CHECK-NEXT: [[L8UI3:%[0-9]+]]:gpr = L8UI [[ADDI]], 1 :: (load (s8) from %ir.p + 3)
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[L8UI3]], 8
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gpr = OR [[SLLI1]], [[L8UI2]]
    ; CHECK-NEXT: [[SLLI2:%[0-9]+]]:gpr = SLLI [[OR1]], 16
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:gpr = OR [[SLLI2]], [[OR]]
    ; CHECK-NEXT: $a2 = COPY [[OR2]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %15:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s8) from %ir.p)
    %16:gprb(s32) = G_CONSTANT i32 1
    %17:gprb(p0) = G_PTR_ADD %0, %16(s32)
    %18:gprb(s32) = G_ZEXTLOAD %17(p0) :: (load (s8) from %ir.p + 1)
    %19:gprb(s32) = G_CONSTANT i32 8
    %20:gprb(s32) = G_SHL %18, %19(s32)
    %2:gprb(s32) = G_OR %20, %15
    %3:gprb(s32) = G_CONSTANT i32 2
    %4:gprb(p0) = G_PTR_ADD %0, %3(s32)
    %9:gprb(s32) = G_ZEXTLOAD %4(p0) :: (load (s8) from %ir.p + 2)
    %10:gprb(s32) = G_CONSTANT i32 1
    %11:gprb(p0) = G_PTR_ADD %4, %10(s32)
    %12:gprb(s32) = G_LOAD %11(p0) :: (load (s8) from %ir.p + 3)
    %13:gprb(s32) = G_CONSTANT i32 8
    %14:gprb(s32) = G_SHL %12, %13(s32)
    %5:gprb(s32) = G_OR %14, %9
    %6:gprb(s32) = G_CONSTANT i32 16
    %7:gprb(s32) = G_SHL %5, %6(s32)
    %8:gprb(s32) = G_OR %7, %2
    %1:gprb(p0) = G_INTTOPTR %8(s32)
    $a2 = COPY %1(p0)
    RETN implicit $a0, implicit $a2

...
---
name:            load_ptr_unaligned_2
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gprb, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: gprb, preferred-register: '' }
  - { id: 5, class: gprb, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gprb, preferred-register: '' }
  - { id: 8, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2

    ; CHECK-LABEL: name: load_ptr_unaligned_2
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[L16UI:%[0-9]+]]:gpr = L16UI [[COPY]], 0 :: (load (s16) from %ir.p)
    ; CHECK-NEXT: [[L16UI1:%[0-9]+]]:gpr = L16UI [[COPY]], 2 :: (load (s16) from %ir.p + 2)
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[L16UI1]], 16
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI]], [[L16UI]]
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gprb(p0) = COPY $a2
    %2:gprb(s32) = G_ZEXTLOAD %0(p0) :: (load (s16) from %ir.p)
    %3:gprb(s32) = G_CONSTANT i32 2
    %4:gprb(p0) = G_PTR_ADD %0, %3(s32)
    %5:gprb(s32) = G_LOAD %4(p0) :: (load (s16) from %ir.p + 2)
    %6:gprb(s32) = G_CONSTANT i32 16
    %7:gprb(s32) = G_SHL %5, %6(s32)
    %8:gprb(s32) = G_OR %7, %2
    %1:gprb(p0) = G_INTTOPTR %8(s32)
    $a2 = COPY %1(p0)
    RETN implicit $a0, implicit $a2

...
