# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'shift_const_wide.ll'
  source_filename = "shift_const_wide.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i64 @shl_const(i64 %val) {
  entry:
    %shl = shl i64 %val, 5
    ret i64 %shl
  }

  define i64 @shl_const_5bit(i64 %val) {
  entry:
    %shl = shl i64 %val, 17
    ret i64 %shl
  }

  define i64 @shl_const_6bit(i64 %val) {
  entry:
    %shl = shl i64 %val, 37
    ret i64 %shl
  }

  define i64 @shl_const_overflow(i64 %val) {
  entry:
    %shl = shl i64 %val, 64
    ret i64 %shl
  }

  define i64 @lshr_const(i64 %val) {
  entry:
    %lshr = lshr i64 %val, 5
    ret i64 %lshr
  }

  define i64 @lshr_const_5bit(i64 %val) {
  entry:
    %lshr = lshr i64 %val, 17
    ret i64 %lshr
  }

  define i64 @lshr_const_6bit(i64 %val) {
  entry:
    %lshr = lshr i64 %val, 37
    ret i64 %lshr
  }

  define i64 @lshr_const_overflow(i64 %val) {
  entry:
    %lshr = lshr i64 %val, 64
    ret i64 %lshr
  }

  define i64 @ashr_const(i64 %val) {
  entry:
    %ashr = ashr i64 %val, 5
    ret i64 %ashr
  }

  define i64 @ashr_const_5bit(i64 %val) {
  entry:
    %ashr = ashr i64 %val, 17
    ret i64 %ashr
  }

  define i64 @ashr_const_6bit(i64 %val) {
  entry:
    %ashr = ashr i64 %val, 37
    ret i64 %ashr
  }

  define i64 @ashr_const_overflow(i64 %val) {
  entry:
    %ashr = ashr i64 %val, 64
    ret i64 %ashr
  }

...
---
name:            shl_const
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_const
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 5
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[COPY1]], 5
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY]], 27, 5
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI1]], [[EXTUI]]
    ; CHECK-NEXT: $a2 = COPY [[SLLI]]
    ; CHECK-NEXT: $a3 = COPY [[OR]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 5
    %11:gprb(s32) = G_SHL %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 5
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_CONSTANT i32 27
    %15:gprb(s32) = G_LSHR %1, %14(s32)
    %16:gprb(s32) = G_OR %13, %15
    $a2 = COPY %11(s32)
    $a3 = COPY %16(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            shl_const_5bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: gprb, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_const_5bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 17
    ; CHECK-NEXT: [[SLLI1:%[0-9]+]]:gpr = SLLI [[COPY1]], 17
    ; CHECK-NEXT: [[SRLI:%[0-9]+]]:gpr = SRLI [[COPY]], 15
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SLLI1]], [[SRLI]]
    ; CHECK-NEXT: $a2 = COPY [[SLLI]]
    ; CHECK-NEXT: $a3 = COPY [[OR]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 17
    %11:gprb(s32) = G_SHL %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 17
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_CONSTANT i32 15
    %15:gprb(s32) = G_LSHR %1, %14(s32)
    %16:gprb(s32) = G_OR %13, %15
    $a2 = COPY %11(s32)
    $a3 = COPY %16(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            shl_const_6bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_const_6bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 5
    ; CHECK-NEXT: $a2 = COPY [[MOVI]]
    ; CHECK-NEXT: $a3 = COPY [[SLLI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %10:gprb(s32) = G_CONSTANT i32 0
    %11:gprb(s32) = G_CONSTANT i32 5
    %12:gprb(s32) = G_SHL %1, %11(s32)
    $a2 = COPY %10(s32)
    $a3 = COPY %12(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            shl_const_overflow
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gpr, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gpr, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_const_overflow
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 32
    ; CHECK-NEXT: SSL [[MOVI1]], implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[MOVI]]
    ; CHECK-NEXT: $a3 = COPY [[SLL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gpr(s32) = COPY $a2
    %10:gprb(s32) = G_CONSTANT i32 0
    %11:gprb(s32) = G_CONSTANT i32 32
    G_XTENSA_SSL_INRANGE %11(s32), implicit-def $sar
    %12:gpr(s32) = SLL %1(s32), implicit $sar
    $a2 = COPY %10(s32)
    $a3 = COPY %12(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_const
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_const
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SRLI:%[0-9]+]]:gpr = SRLI [[COPY]], 5
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 27
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SRLI]], [[SLLI]]
    ; CHECK-NEXT: [[SRLI1:%[0-9]+]]:gpr = SRLI [[COPY1]], 5
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: $a3 = COPY [[SRLI1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 5
    %11:gprb(s32) = G_LSHR %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 27
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_OR %11, %13
    %15:gprb(s32) = G_LSHR %2, %10(s32)
    $a2 = COPY %14(s32)
    $a3 = COPY %15(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_const_5bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_const_5bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY]], 17, 15
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 15
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[EXTUI]], [[SLLI]]
    ; CHECK-NEXT: [[EXTUI1:%[0-9]+]]:gpr = EXTUI [[COPY1]], 17, 15
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: $a3 = COPY [[EXTUI1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 17
    %11:gprb(s32) = G_LSHR %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 15
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_OR %11, %13
    %15:gprb(s32) = G_LSHR %2, %10(s32)
    $a2 = COPY %14(s32)
    $a3 = COPY %15(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_const_6bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_const_6bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SRLI:%[0-9]+]]:gpr = SRLI [[COPY]], 5
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: $a2 = COPY [[SRLI]]
    ; CHECK-NEXT: $a3 = COPY [[MOVI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 5
    %11:gprb(s32) = G_LSHR %2, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 0
    $a2 = COPY %11(s32)
    $a3 = COPY %12(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_const_overflow
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gpr, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_const_overflow
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 32
    ; CHECK-NEXT: SSR [[MOVI]], implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr = SRL [[COPY]], implicit $sar
    ; CHECK-NEXT: [[MOVI1:%[0-9]+]]:gpr = MOVI 0
    ; CHECK-NEXT: $a2 = COPY [[SRL]]
    ; CHECK-NEXT: $a3 = COPY [[MOVI1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 32
    G_XTENSA_SSR_INRANGE %10(s32), implicit-def $sar
    %11:gpr(s32) = SRL %2(s32), implicit $sar
    %12:gprb(s32) = G_CONSTANT i32 0
    $a2 = COPY %11(s32)
    $a3 = COPY %12(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_const
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_const
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SRLI:%[0-9]+]]:gpr = SRLI [[COPY]], 5
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 27
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[SRLI]], [[SLLI]]
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[COPY1]], 5
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: $a3 = COPY [[SRAI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 5
    %11:gprb(s32) = G_LSHR %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 27
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_OR %11, %13
    %15:gprb(s32) = G_ASHR %2, %10(s32)
    $a2 = COPY %14(s32)
    $a3 = COPY %15(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_const_5bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: gprb, preferred-register: '' }
  - { id: 15, class: gprb, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_const_5bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY]], 17, 15
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 15
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR [[EXTUI]], [[SLLI]]
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[COPY1]], 17
    ; CHECK-NEXT: $a2 = COPY [[OR]]
    ; CHECK-NEXT: $a3 = COPY [[SRAI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %1:gprb(s32) = COPY $a2
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 17
    %11:gprb(s32) = G_LSHR %1, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 15
    %13:gprb(s32) = G_SHL %2, %12(s32)
    %14:gprb(s32) = G_OR %11, %13
    %15:gprb(s32) = G_ASHR %2, %10(s32)
    $a2 = COPY %14(s32)
    $a3 = COPY %15(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_const_6bit
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_const_6bit
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[COPY]], 5
    ; CHECK-NEXT: [[SRAI1:%[0-9]+]]:gpr = SRAI [[COPY]], 31
    ; CHECK-NEXT: $a2 = COPY [[SRAI]]
    ; CHECK-NEXT: $a3 = COPY [[SRAI1]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 5
    %11:gprb(s32) = G_ASHR %2, %10(s32)
    %12:gprb(s32) = G_CONSTANT i32 31
    %13:gprb(s32) = G_ASHR %2, %12(s32)
    $a2 = COPY %11(s32)
    $a3 = COPY %13(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_const_overflow
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gpr, preferred-register: '' }
  - { id: 12, class: gprb, preferred-register: '' }
  - { id: 13, class: gprb, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_const_overflow
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[MOVI:%[0-9]+]]:gpr = MOVI 32
    ; CHECK-NEXT: SSR [[MOVI]], implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr = SRA [[COPY]], implicit $sar
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[COPY]], 31
    ; CHECK-NEXT: $a2 = COPY [[SRA]]
    ; CHECK-NEXT: $a3 = COPY [[SRAI]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 32
    G_XTENSA_SSR_INRANGE %10(s32), implicit-def $sar
    %11:gpr(s32) = SRA %2(s32), implicit $sar
    %12:gprb(s32) = G_CONSTANT i32 31
    %13:gprb(s32) = G_ASHR %2, %12(s32)
    $a2 = COPY %11(s32)
    $a3 = COPY %13(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
