# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'shift_var_narrow.ll'
  source_filename = "shift_var_narrow.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i8 @shl_i8(i8 %val, i8 %shamt) {
  entry:
    %shl = shl i8 %val, %shamt
    ret i8 %shl
  }

  define i16 @shl_i16(i16 %val, i16 %shamt) {
  entry:
    %shl = shl i16 %val, %shamt
    ret i16 %shl
  }

  define i32 @shl_i32(i32 %val, i32 %shamt) {
  entry:
    %shl = shl i32 %val, %shamt
    ret i32 %shl
  }

  define i8 @lshr_i8(i8 %val, i8 %shamt) {
  entry:
    %lshr = lshr i8 %val, %shamt
    ret i8 %lshr
  }

  define i16 @lshr_i16(i16 %val, i16 %shamt) {
  entry:
    %lshr = lshr i16 %val, %shamt
    ret i16 %lshr
  }

  define i32 @lshr_i32(i32 %val, i32 %shamt) {
  entry:
    %lshr = lshr i32 %val, %shamt
    ret i32 %lshr
  }

  define i8 @ashr_i8(i8 %val, i8 %shamt) {
  entry:
    %ashr = ashr i8 %val, %shamt
    ret i8 %ashr
  }

  define i16 @ashr_i16(i16 %val, i16 %shamt) {
  entry:
    %ashr = ashr i16 %val, %shamt
    ret i16 %ashr
  }

  define i32 @ashr_i32(i32 %val, i32 %shamt) {
  entry:
    %ashr = ashr i32 %val, %shamt
    ret i32 %ashr
  }

...
---
name:            shl_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 8
    ; CHECK-NEXT: SSL [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gpr(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %9:gprb(s32) = G_CONSTANT i32 255
    %6:gprb(s32) = G_AND %3, %9
    G_XTENSA_SSL_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SLL %2(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shl_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 16
    ; CHECK-NEXT: SSL [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gpr(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %9:gprb(s32) = G_CONSTANT i32 65535
    %6:gprb(s32) = G_AND %3, %9
    G_XTENSA_SSL_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SLL %2(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shl_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: SSL [[COPY1]], implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr = SLL [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    G_XTENSA_SSL_INRANGE %1(s32), implicit-def $sar
    %2:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 8
    ; CHECK-NEXT: [[EXTUI1:%[0-9]+]]:gpr = EXTUI [[COPY]], 0, 8
    ; CHECK-NEXT: SSR [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr = SRL [[EXTUI1]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gprb(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 255
    %6:gprb(s32) = G_AND %3, %10
    %9:gprb(s32) = G_CONSTANT i32 255
    %7:gpr(s32) = G_AND %2, %9
    G_XTENSA_SSR_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SRL %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 16
    ; CHECK-NEXT: [[EXTUI1:%[0-9]+]]:gpr = EXTUI [[COPY]], 0, 16
    ; CHECK-NEXT: SSR [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr = SRL [[EXTUI1]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gprb(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %10:gprb(s32) = G_CONSTANT i32 65535
    %6:gprb(s32) = G_AND %3, %10
    %9:gprb(s32) = G_CONSTANT i32 65535
    %7:gpr(s32) = G_AND %2, %9
    G_XTENSA_SSR_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SRL %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: SSR [[COPY1]], implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr = SRL [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    G_XTENSA_SSR_INRANGE %1(s32), implicit-def $sar
    %2:gpr(s32) = SRL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 8
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 24
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 24
    ; CHECK-NEXT: SSR [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr = SRA [[SRAI]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gprb(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %9:gprb(s32) = G_CONSTANT i32 255
    %6:gprb(s32) = G_AND %3, %9
    %11:gprb(s32) = G_CONSTANT i32 24
    %10:gprb(s32) = G_SHL %2, %11(s32)
    %7:gpr(s32) = G_ASHR %10, %11(s32)
    G_XTENSA_SSR_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SRA %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gprb, preferred-register: '' }
  - { id: 3, class: gprb, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gprb, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gprb, preferred-register: '' }
  - { id: 10, class: gprb, preferred-register: '' }
  - { id: 11, class: gprb, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: [[EXTUI:%[0-9]+]]:gpr = EXTUI [[COPY1]], 0, 16
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 16
    ; CHECK-NEXT: [[SRAI:%[0-9]+]]:gpr = SRAI [[SLLI]], 16
    ; CHECK-NEXT: SSR [[EXTUI]], implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr = SRA [[SRAI]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gprb(s32) = COPY $a2
    %3:gprb(s32) = COPY $a3
    %9:gprb(s32) = G_CONSTANT i32 65535
    %6:gprb(s32) = G_AND %3, %9
    %11:gprb(s32) = G_CONSTANT i32 16
    %10:gprb(s32) = G_SHL %2, %11(s32)
    %7:gpr(s32) = G_ASHR %10, %11(s32)
    G_XTENSA_SSR_INRANGE %6(s32), implicit-def $sar
    %8:gpr(s32) = SRA %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: gprb, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $a3
    ; CHECK-NEXT: SSR [[COPY1]], implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr = SRA [[COPY]], implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]]
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:gprb(s32) = COPY $a3
    G_XTENSA_SSR_INRANGE %1(s32), implicit-def $sar
    %2:gpr(s32) = SRA %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
