; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s --check-prefix=OPT
; RUN: llc -O0 < %s -mtriple=xtensa | FileCheck %s --check-prefix=UNOPT
; RUN: llc < %s -mtriple=xtensa -mcpu=lx7 | FileCheck %s --check-prefix=LX7-OPT
; RUN: llc -O0 < %s -mtriple=xtensa -mcpu=lx7 | FileCheck %s --check-prefix=LX7-UNOPT

define i1 @add_i1(i1 %a, i1 %b) {
; OPT-LABEL: add_i1:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    add.n a2, a3, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i1:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    add.n a2, a3, a2
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i1:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a2, a3, a2
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i1:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    add.n a2, a3, a2
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i1 %b, %a
  ret i1 %add
}

define i8 @add_i8(i8 %a, i8 %b) {
; OPT-LABEL: add_i8:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    add.n a2, a3, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i8:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    add.n a2, a3, a2
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i8:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a2, a3, a2
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i8:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    add.n a2, a3, a2
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i8 %b, %a
  ret i8 %add
}

define i16 @add_i16(i16 %a, i16 %b) {
; OPT-LABEL: add_i16:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    add.n a2, a3, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i16:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    add.n a2, a3, a2
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i16:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a2, a3, a2
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i16:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    add.n a2, a3, a2
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i16 %b, %a
  ret i16 %add
}

define i32 @add_i32(i32 %a, i32 %b) {
; OPT-LABEL: add_i32:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    add.n a2, a3, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i32:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    add.n a2, a3, a2
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i32:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a2, a3, a2
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i32:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    add.n a2, a3, a2
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i32 %b, %a
  ret i32 %add
}

define i33 @add_i33(i33 %a, i33 %b) {
; OPT-LABEL: add_i33:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    mov.n a6, a2
; OPT-NEXT:    add.n a2, a4, a2
; OPT-NEXT:    add.n a3, a5, a3
; OPT-NEXT:    bgeu a2, a6, .LBB4_2
; OPT-NEXT:  # %bb.1:
; OPT-NEXT:    addi.n a3, a3, 1
; OPT-NEXT:  .LBB4_2: # %entry
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i33:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    addi a1, a1, -32
; UNOPT-NEXT:    s32i.n a2, a1, 8 # 4-byte Spill
; UNOPT-NEXT:    mov.n a2, a3
; UNOPT-NEXT:    l32i.n a3, a1, 8 # 4-byte Reload
; UNOPT-NEXT:    s32i.n a2, a1, 12 # 4-byte Spill
; UNOPT-NEXT:    s32i.n a5, a1, 16 # 4-byte Spill
; UNOPT-NEXT:    add.n a2, a4, a3
; UNOPT-NEXT:    s32i.n a2, a1, 20 # 4-byte Spill
; UNOPT-NEXT:    movi.n a4, 0
; UNOPT-NEXT:    s32i.n a4, a1, 24 # 4-byte Spill
; UNOPT-NEXT:    movi.n a4, 1
; UNOPT-NEXT:    s32i.n a4, a1, 28 # 4-byte Spill
; UNOPT-NEXT:    bltu a2, a3, .LBB4_3
; UNOPT-NEXT:  # %bb.2: # %entry
; UNOPT-NEXT:    l32i.n a2, a1, 24 # 4-byte Reload
; UNOPT-NEXT:    s32i.n a2, a1, 28 # 4-byte Spill
; UNOPT-NEXT:  .LBB4_3: # %entry
; UNOPT-NEXT:    l32i.n a2, a1, 20 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a3, a1, 16 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a5, a1, 12 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a4, a1, 28 # 4-byte Reload
; UNOPT-NEXT:    add.n a3, a3, a5
; UNOPT-NEXT:    add.n a3, a3, a4
; UNOPT-NEXT:    addi a1, a1, 32
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i33:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a4, a4, a2
; LX7-OPT-NEXT:    saltu a2, a4, a2
; LX7-OPT-NEXT:    add.n a3, a5, a3
; LX7-OPT-NEXT:    add.n a3, a3, a2
; LX7-OPT-NEXT:    mov.n a2, a4
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i33:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    addi a1, a1, -16
; LX7-UNOPT-NEXT:    s32i.n a2, a1, 12 # 4-byte Spill
; LX7-UNOPT-NEXT:    mov.n a2, a4
; LX7-UNOPT-NEXT:    l32i.n a4, a1, 12 # 4-byte Reload
; LX7-UNOPT-NEXT:    add.n a2, a2, a4
; LX7-UNOPT-NEXT:    saltu a4, a2, a4
; LX7-UNOPT-NEXT:    add.n a3, a5, a3
; LX7-UNOPT-NEXT:    add.n a3, a3, a4
; LX7-UNOPT-NEXT:    addi a1, a1, 16
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i33 %b, %a
  ret i33 %add
}

define i64 @add_i64(i64 %a, i64 %b) {
; OPT-LABEL: add_i64:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    mov.n a6, a2
; OPT-NEXT:    add.n a2, a4, a2
; OPT-NEXT:    add.n a3, a5, a3
; OPT-NEXT:    bgeu a2, a6, .LBB5_2
; OPT-NEXT:  # %bb.1:
; OPT-NEXT:    addi.n a3, a3, 1
; OPT-NEXT:  .LBB5_2: # %entry
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: add_i64:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    addi a1, a1, -32
; UNOPT-NEXT:    s32i.n a2, a1, 8 # 4-byte Spill
; UNOPT-NEXT:    mov.n a2, a3
; UNOPT-NEXT:    l32i.n a3, a1, 8 # 4-byte Reload
; UNOPT-NEXT:    s32i.n a2, a1, 12 # 4-byte Spill
; UNOPT-NEXT:    s32i.n a5, a1, 16 # 4-byte Spill
; UNOPT-NEXT:    add.n a2, a4, a3
; UNOPT-NEXT:    s32i.n a2, a1, 20 # 4-byte Spill
; UNOPT-NEXT:    movi.n a4, 0
; UNOPT-NEXT:    s32i.n a4, a1, 24 # 4-byte Spill
; UNOPT-NEXT:    movi.n a4, 1
; UNOPT-NEXT:    s32i.n a4, a1, 28 # 4-byte Spill
; UNOPT-NEXT:    bltu a2, a3, .LBB5_3
; UNOPT-NEXT:  # %bb.2: # %entry
; UNOPT-NEXT:    l32i.n a2, a1, 24 # 4-byte Reload
; UNOPT-NEXT:    s32i.n a2, a1, 28 # 4-byte Spill
; UNOPT-NEXT:  .LBB5_3: # %entry
; UNOPT-NEXT:    l32i.n a2, a1, 20 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a3, a1, 16 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a5, a1, 12 # 4-byte Reload
; UNOPT-NEXT:    l32i.n a4, a1, 28 # 4-byte Reload
; UNOPT-NEXT:    add.n a3, a3, a5
; UNOPT-NEXT:    add.n a3, a3, a4
; UNOPT-NEXT:    addi a1, a1, 32
; UNOPT-NEXT:    ret.n
;
; LX7-OPT-LABEL: add_i64:
; LX7-OPT:       # %bb.0: # %entry
; LX7-OPT-NEXT:    add.n a4, a4, a2
; LX7-OPT-NEXT:    saltu a2, a4, a2
; LX7-OPT-NEXT:    add.n a3, a5, a3
; LX7-OPT-NEXT:    add.n a3, a3, a2
; LX7-OPT-NEXT:    mov.n a2, a4
; LX7-OPT-NEXT:    ret.n
;
; LX7-UNOPT-LABEL: add_i64:
; LX7-UNOPT:       # %bb.1: # %entry
; LX7-UNOPT-NEXT:    addi a1, a1, -16
; LX7-UNOPT-NEXT:    s32i.n a2, a1, 12 # 4-byte Spill
; LX7-UNOPT-NEXT:    mov.n a2, a4
; LX7-UNOPT-NEXT:    l32i.n a4, a1, 12 # 4-byte Reload
; LX7-UNOPT-NEXT:    add.n a2, a2, a4
; LX7-UNOPT-NEXT:    saltu a4, a2, a4
; LX7-UNOPT-NEXT:    add.n a3, a5, a3
; LX7-UNOPT-NEXT:    add.n a3, a3, a4
; LX7-UNOPT-NEXT:    addi a1, a1, 16
; LX7-UNOPT-NEXT:    ret.n
entry:
  %add = add i64 %b, %a
  ret i64 %add
}
