; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i32 @addmi_pos(i32 %a) {
; CHECK-LABEL: addmi_pos:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 256
; CHECK-NEXT:    ret.n
  %add = add i32 %a, 256
  ret i32 %add
}

define i32 @addmi_neg(i32 %a) {
; CHECK-LABEL: addmi_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, -256
; CHECK-NEXT:    ret.n
  %add = add i32 %a, -256
  ret i32 %add
}

define i32 @addmi_pos_max(i32 %a) {
; CHECK-LABEL: addmi_pos_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 32512
; CHECK-NEXT:    ret.n
  %add = add i32 %a, 32512
  ret i32 %add
}

define i32 @addmi_neg_min(i32 %a) {
; CHECK-LABEL: addmi_neg_min:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, -32768
; CHECK-NEXT:    ret.n
  %add = add i32 %a, -32768
  ret i32 %add
}

define i32 @not_addmi_pos_min(i32 %a) {
; CHECK-LABEL: not_addmi_pos_min:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a3, .LCPI4_0
; CHECK-NEXT:    add.n a2, a2, a3
; CHECK-NEXT:    ret.n
  %add = add i32 %a, 33024
  ret i32 %add
}

define i32 @not_addmi_neg_max(i32 %a) {
; CHECK-LABEL: not_addmi_neg_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a3, .LCPI5_0
; CHECK-NEXT:    add.n a2, a2, a3
; CHECK-NEXT:    ret.n
  %add = add i32 %a, -33280
  ret i32 %add
}

define i32 @submi_pos(i32 %a) {
; CHECK-LABEL: submi_pos:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, -256
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, 256
  ret i32 %sub
}

define i32 @submi_neg(i32 %a) {
; CHECK-LABEL: submi_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 256
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, -256
  ret i32 %sub
}

define i32 @submi_pos_max(i32 %a) {
; CHECK-LABEL: submi_pos_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, -32768
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, 32768
  ret i32 %sub
}

define i32 @submi_neg_min(i32 %a) {
; CHECK-LABEL: submi_neg_min:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 32512
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, -32512
  ret i32 %sub
}

define i32 @not_submi_pos_min(i32 %a) {
; CHECK-LABEL: not_submi_pos_min:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a3, .LCPI10_0
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, 33280
  ret i32 %sub
}

define i32 @not_submi_neg_max(i32 %a) {
; CHECK-LABEL: not_submi_neg_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a3, .LCPI11_0
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    ret.n
  %sub = sub i32 %a, -33024
  ret i32 %sub
}
