; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

define i32 @not_and_1(i32 %a) {
; CHECK-LABEL: not_and_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi.n a3, 1
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    xor a2, a2, a3
; CHECK-NEXT:    ret.n
  %not = xor i32 %a, -1
  %and = and i32 %not, 1
  ret i32 %and
}

define i32 @not_and_17(i32 %a) {
; CHECK-LABEL: not_and_17:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi.n a3, 17
; CHECK-NEXT:    and a2, a3, a2
; CHECK-NEXT:    xor a2, a2, a3
; CHECK-NEXT:    ret.n
  %not = xor i32 %a, -1
  %and = and i32 %not, 17
  ret i32 %and
}

define i32 @and_not(i32 %a, i32 %b) {
; CHECK-LABEL: and_not:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and a3, a2, a3
; CHECK-NEXT:    xor a2, a3, a2
; CHECK-NEXT:    ret.n
  %not = xor i32 %b, -1
  %and = and i32 %a, %not
  ret i32 %and
}
