; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

define i1 @test_set_0(i32 %a) {
; CHECK-LABEL: test_set_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 1
  %icmp = icmp ne i32 %and, 0
  ret i1 %icmp
}

define i1 @test_clear_0(i32 %a) {
; CHECK-LABEL: test_clear_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi.n a3, 1
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    xor a2, a2, a3
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 1
  %icmp = icmp eq i32 %and, 0
  ret i1 %icmp
}

define i1 @test_set_5(i32 %a) {
; CHECK-LABEL: test_set_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 5, 1
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 32
  %icmp = icmp ne i32 %and, 0
  ret i1 %icmp
}

define i1 @test_clear_5(i32 %a) {
; CHECK-LABEL: test_clear_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi.n a3, 1
; CHECK-NEXT:    extui a2, a2, 5, 1
; CHECK-NEXT:    xor a2, a2, a3
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 32
  %icmp = icmp eq i32 %and, 0
  ret i1 %icmp
}

define i1 @test_set_31(i32 %a) {
; CHECK-LABEL: test_set_31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 31, 1
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 2147483648
  %icmp = icmp ne i32 %and, 0
  ret i1 %icmp
}

define i1 @test_clear_31(i32 %a) {
; CHECK-LABEL: test_clear_31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 31, 1
; CHECK-NEXT:    movi.n a3, 1
; CHECK-NEXT:    xor a2, a2, a3
; CHECK-NEXT:    ret.n
  %and = and i32 %a, 2147483648
  %icmp = icmp eq i32 %and, 0
  ret i1 %icmp
}
