; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 < %s -mtriple=xtensa | FileCheck %s

define void @branch_eq(i32 %a, i32 %b) {
; CHECK-LABEL: branch_eq:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    bne a2, a3, .LBB0_3
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp eq i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

declare void @func(...)

define void @branch_ne(i32 %a, i32 %b) {
; CHECK-LABEL: branch_ne:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    beq a2, a3, .LBB1_3
; CHECK-NEXT:    j .LBB1_2
; CHECK-NEXT:  .LBB1_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB1_3
; CHECK-NEXT:  .LBB1_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp ne i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_eqz(i32 %a) {
; CHECK-LABEL: branch_eqz:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    bnez a2, .LBB2_3
; CHECK-NEXT:    j .LBB2_2
; CHECK-NEXT:  .LBB2_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB2_3
; CHECK-NEXT:  .LBB2_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp eq i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_nez(i32 %a) {
; CHECK-LABEL: branch_nez:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    beqz a2, .LBB3_3
; CHECK-NEXT:    j .LBB3_2
; CHECK-NEXT:  .LBB3_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB3_3
; CHECK-NEXT:  .LBB3_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp ne i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_slt(i32 %a, i32 %b) {
; CHECK-LABEL: branch_slt:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    bge a2, a3, .LBB4_3
; CHECK-NEXT:    j .LBB4_2
; CHECK-NEXT:  .LBB4_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB4_3
; CHECK-NEXT:  .LBB4_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp slt i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sle(i32 %a, i32 %b) {
; CHECK-LABEL: branch_sle:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a3, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 4
; CHECK-NEXT:    blt a2, a3, .LBB5_3
; CHECK-NEXT:    j .LBB5_2
; CHECK-NEXT:  .LBB5_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB5_3
; CHECK-NEXT:  .LBB5_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp sle i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sgt(i32 %a, i32 %b) {
; CHECK-LABEL: branch_sgt:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a3, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 4
; CHECK-NEXT:    bge a2, a3, .LBB6_3
; CHECK-NEXT:    j .LBB6_2
; CHECK-NEXT:  .LBB6_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB6_3
; CHECK-NEXT:  .LBB6_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp sgt i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sge(i32 %a, i32 %b) {
; CHECK-LABEL: branch_sge:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    blt a2, a3, .LBB7_3
; CHECK-NEXT:    j .LBB7_2
; CHECK-NEXT:  .LBB7_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB7_3
; CHECK-NEXT:  .LBB7_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp sge i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sltz(i32 %a) {
; CHECK-LABEL: branch_sltz:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    bgez a2, .LBB8_3
; CHECK-NEXT:    j .LBB8_2
; CHECK-NEXT:  .LBB8_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB8_3
; CHECK-NEXT:  .LBB8_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp slt i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_slez(i32 %a) {
; CHECK-LABEL: branch_slez:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    bgei a2, 1, .LBB9_3
; CHECK-NEXT:    j .LBB9_2
; CHECK-NEXT:  .LBB9_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB9_3
; CHECK-NEXT:  .LBB9_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp sle i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sgtz(i32 %a) {
; CHECK-LABEL: branch_sgtz:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    blti a2, 1, .LBB10_3
; CHECK-NEXT:    j .LBB10_2
; CHECK-NEXT:  .LBB10_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB10_3
; CHECK-NEXT:  .LBB10_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp sgt i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_sgez(i32 %a) {
; CHECK-LABEL: branch_sgez:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    bltz a2, .LBB11_3
; CHECK-NEXT:    j .LBB11_2
; CHECK-NEXT:  .LBB11_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB11_3
; CHECK-NEXT:  .LBB11_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %cmp = icmp sge i32 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_ult(i32 %a, i32 %b) {
; CHECK-LABEL: branch_ult:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    bgeu a2, a3, .LBB12_3
; CHECK-NEXT:    j .LBB12_2
; CHECK-NEXT:  .LBB12_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB12_3
; CHECK-NEXT:  .LBB12_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp ult i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_ule(i32 %a, i32 %b) {
; CHECK-LABEL: branch_ule:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a3, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 4
; CHECK-NEXT:    bltu a2, a3, .LBB13_3
; CHECK-NEXT:    j .LBB13_2
; CHECK-NEXT:  .LBB13_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB13_3
; CHECK-NEXT:  .LBB13_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp ule i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_ugt(i32 %a, i32 %b) {
; CHECK-LABEL: branch_ugt:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a3, a1, 8
; CHECK-NEXT:    l32i.n a2, a1, 4
; CHECK-NEXT:    bgeu a2, a3, .LBB14_3
; CHECK-NEXT:    j .LBB14_2
; CHECK-NEXT:  .LBB14_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB14_3
; CHECK-NEXT:  .LBB14_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp ugt i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}

define void @branch_uge(i32 %a, i32 %b) {
; CHECK-LABEL: branch_uge:
; CHECK:       # %bb.1: # %entry
; CHECK-NEXT:    addi a1, a1, -16
; CHECK-NEXT:    s32i.n a0, a1, 12 # 4-byte Spill
; CHECK-NEXT:    s32i.n a2, a1, 8
; CHECK-NEXT:    s32i.n a3, a1, 4
; CHECK-NEXT:    l32i.n a2, a1, 8
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    bltu a2, a3, .LBB15_3
; CHECK-NEXT:    j .LBB15_2
; CHECK-NEXT:  .LBB15_2: # %if.then
; CHECK-NEXT:    call0 func
; CHECK-NEXT:    j .LBB15_3
; CHECK-NEXT:  .LBB15_3: # %if.end
; CHECK-NEXT:    l32i.n a0, a1, 12 # 4-byte Reload
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    ret.n
entry:
  %a.addr = alloca i32, align 4
  %b.addr = alloca i32, align 4
  store i32 %a, ptr %a.addr, align 4
  store i32 %b, ptr %b.addr, align 4
  %0 = load i32, ptr %a.addr, align 4
  %1 = load i32, ptr %b.addr, align 4
  %cmp = icmp uge i32 %0, %1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  call void @func()
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}
