; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

@global = global i64 0, align 8

define void @f1(i64 %a1) {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a4, .LCPI0_0
; CHECK-NEXT:    s32i.n a2, a4, 0
; CHECK-NEXT:    s32i.n a3, a4, 4
; CHECK-NEXT:    ret.n
  store i64 %a1, ptr @global
  ret void
}

define void @f2(i32 %a1, i32 %a2, i32 %a3, i32 %a4, i32 %a5, i64 %a6) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i.n a2, a1, 0
; CHECK-NEXT:    l32i.n a3, a1, 4
; CHECK-NEXT:    l32r a4, .LCPI1_0
; CHECK-NEXT:    s32i.n a2, a4, 0
; CHECK-NEXT:    s32i.n a3, a4, 4
; CHECK-NEXT:    ret.n
  store i64 %a6, ptr @global
  ret void
}
