; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

define i8 @load_i8(ptr %base, i32 %n) {
; CHECK-LABEL: load_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add.n a2, a2, a3
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 %n
  %load = load i8, ptr %p
  ret i8 %load
}

define void @store_i8(ptr %base, i32 %n, i8 %val) {
; CHECK-LABEL: store_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add.n a2, a2, a3
; CHECK-NEXT:    s8i a4, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 %n
  store i8 %val, ptr %p
  ret void
}

define i16 @load_i16(ptr %base, i32 %n) {
; CHECK-LABEL: load_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx2 a2, a3, a2
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 %n
  %load = load i16, ptr %p
  ret i16 %load
}

define void @store_i16(ptr %base, i32 %n, i16 %val) {
; CHECK-LABEL: store_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx2 a2, a3, a2
; CHECK-NEXT:    s16i a4, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 %n
  store i16 %val, ptr %p
  ret void
}

define i32 @load_i32(ptr %base, i32 %n) {
; CHECK-LABEL: load_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx4 a2, a3, a2
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 %n
  %load = load i32, ptr %p
  ret i32 %load
}

define void @store_i32(ptr %base, i32 %n, i32 %val) {
; CHECK-LABEL: store_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx4 a2, a3, a2
; CHECK-NEXT:    s32i.n a4, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 %n
  store i32 %val, ptr %p
  ret void
}

define i64 @load_i64(ptr %base, i32 %n) {
; CHECK-LABEL: load_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx8 a3, a3, a2
; CHECK-NEXT:    l32i.n a2, a3, 0
; CHECK-NEXT:    l32i.n a3, a3, 4
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 %n
  %load = load i64, ptr %p
  ret i64 %load
}

define void @store_i64(ptr %base, i32 %n, i64 %val) {
; CHECK-LABEL: store_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addx8 a2, a3, a2
; CHECK-NEXT:    s32i.n a4, a2, 0
; CHECK-NEXT:    s32i.n a5, a2, 4
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 %n
  store i64 %val, ptr %p
  ret void
}
