; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

define i32 @zextload_i8(ptr %p) {
; CHECK-LABEL: zextload_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %val = load i8, ptr %p
  %zext = zext i8 %val to i32
  ret i32 %zext
}

define i32 @sextload_i8(ptr %p) {
; CHECK-LABEL: sextload_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    sext a2, a2, 7
; CHECK-NEXT:    ret.n
  %val = load i8, ptr %p
  %sext = sext i8 %val to i32
  ret i32 %sext
}

define i32 @zextload_i16(ptr %p) {
; CHECK-LABEL: zextload_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %val = load i16, ptr %p
  %zext = zext i16 %val to i32
  ret i32 %zext
}

define i32 @sextload_i16(ptr %p) {
; CHECK-LABEL: sextload_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l16si a2, a2, 0
; CHECK-NEXT:    ret.n
  %val = load i16, ptr %p
  %sext = sext i16 %val to i32
  ret i32 %sext
}
