; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

define i1 @freeze_i1(i1 %a) {
; CHECK-LABEL: freeze_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %ret = freeze i1 %a
  ret i1 %ret
}

define i8 @freeze_i8(i8 %a) {
; CHECK-LABEL: freeze_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %ret = freeze i8 %a
  ret i8 %ret
}

define i16 @freeze_i16(i16 %a) {
; CHECK-LABEL: freeze_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %ret = freeze i16 %a
  ret i16 %ret
}

define i32 @freeze_i32(i32 %a) {
; CHECK-LABEL: freeze_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %ret = freeze i32 %a
  ret i32 %ret
}

define i64 @freeze_i64(i64 %a) {
; CHECK-LABEL: freeze_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %ret = freeze i64 %a
  ret i64 %ret
}
