; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s

@global = global i32 0, align 4

define void @set(i32 %val) {
; CHECK-LABEL: set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a3, .LCPI0_0
; CHECK-NEXT:    s32i.n a2, a3, 0
; CHECK-NEXT:    ret.n
  store i32 %val, ptr @global
  ret void
}

define i32 @get() {
; CHECK-LABEL: get:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32r a2, .LCPI1_0
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
  %1 = load i32, ptr @global
  ret i32 %1
}
