; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
; RUN: llc < %s -mtriple=xtensa -mcpu=lx7 | FileCheck %s --check-prefix=LX7

define i32 @select_icmp_eq_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_eq_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    moveqz a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_eq_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a2, a3
; LX7-NEXT:    moveqz a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp eq i32 %a, %b
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_ne_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ne_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    movnez a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ne_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a2, a3
; LX7-NEXT:    movnez a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp.not = icmp eq i32 %a, %b
  %cond = select i1 %cmp.not, i32 %d, i32 %c
  ret i32 %cond
}

define i32 @select_icmp_lt_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_lt_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    movltz a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_lt_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a2, a3
; LX7-NEXT:    movltz a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp slt i32 %a, %b
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_lte_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_lte_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a3, a2
; CHECK-NEXT:    movgez a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_lte_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a3, a2
; LX7-NEXT:    movgez a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp.not = icmp sgt i32 %a, %b
  %cond = select i1 %cmp.not, i32 %d, i32 %c
  ret i32 %cond
}

define i32 @select_icmp_gt_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_gt_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a3, a2
; CHECK-NEXT:    movltz a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_gt_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a3, a2
; LX7-NEXT:    movltz a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp sgt i32 %a, %b
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_gte_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_gte_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sub a2, a2, a3
; CHECK-NEXT:    movgez a5, a4, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_gte_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    sub a2, a2, a3
; LX7-NEXT:    movgez a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp.not = icmp slt i32 %a, %b
  %cond = select i1 %cmp.not, i32 %d, i32 %c
  ret i32 %cond
}

define i32 @select_icmp_ltz_i32(i32 %a, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ltz_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movltz a4, a3, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ltz_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    movltz a4, a3, a2
; LX7-NEXT:    mov.n a2, a4
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp slt i32 %a, 0
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_ltez_i32(i32 %a, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ltez_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi.n a2, a2, -1
; CHECK-NEXT:    movltz a4, a3, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ltez_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    addi.n a2, a2, -1
; LX7-NEXT:    movltz a4, a3, a2
; LX7-NEXT:    mov.n a2, a4
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp slt i32 %a, 1
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_gtz_i32(i32 %a, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_gtz_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi.n a2, a2, -1
; CHECK-NEXT:    movgez a4, a3, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_gtz_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    addi.n a2, a2, -1
; LX7-NEXT:    movgez a4, a3, a2
; LX7-NEXT:    mov.n a2, a4
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp sgt i32 %a, 0
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_gtez_i32(i32 %a, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_gtez_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movgez a4, a3, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_gtez_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    movgez a4, a3, a2
; LX7-NEXT:    mov.n a2, a4
; LX7-NEXT:    ret.n
entry:
  %cmp1 = icmp slt i32 %a, 0
  %cond = select i1 %cmp1, i32 %d, i32 %c
  ret i32 %cond
}

define i32 @select_icmp_ult_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ult_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov.n a6, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    bltu a6, a3, .LBB10_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:  .LBB10_2: # %entry
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ult_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    saltu a2, a2, a3
; LX7-NEXT:    movnez a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp ult i32 %a, %b
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_ulte_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ulte_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov.n a6, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    bltu a3, a6, .LBB11_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:  .LBB11_2: # %entry
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ulte_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    saltu a2, a3, a2
; LX7-NEXT:    moveqz a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp.not = icmp ugt i32 %a, %b
  %cond = select i1 %cmp.not, i32 %d, i32 %c
  ret i32 %cond
}

define i32 @select_icmp_ugt_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ugt_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov.n a6, a2
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    bltu a3, a6, .LBB12_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:  .LBB12_2: # %entry
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ugt_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    saltu a2, a3, a2
; LX7-NEXT:    movnez a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp = icmp ugt i32 %a, %b
  %cond = select i1 %cmp, i32 %c, i32 %d
  ret i32 %cond
}

define i32 @select_icmp_ugte_i32(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: select_icmp_ugte_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov.n a6, a2
; CHECK-NEXT:    mov.n a2, a5
; CHECK-NEXT:    bltu a6, a3, .LBB13_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:  .LBB13_2: # %entry
; CHECK-NEXT:    ret.n
;
; LX7-LABEL: select_icmp_ugte_i32:
; LX7:       # %bb.0: # %entry
; LX7-NEXT:    saltu a2, a2, a3
; LX7-NEXT:    moveqz a5, a4, a2
; LX7-NEXT:    mov.n a2, a5
; LX7-NEXT:    ret.n
entry:
  %cmp.not = icmp ult i32 %a, %b
  %cond = select i1 %cmp.not, i32 %d, i32 %c
  ret i32 %cond
}
