; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define ptr @int2ptr(i32 %i) {
; CHECK-LABEL: int2ptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %i2p = inttoptr i32 %i to ptr
  ret ptr %i2p
}

define i32 @ptr2int(ptr %p) {
; CHECK-LABEL: ptr2int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret.n
  %p2i = ptrtoint ptr %p to i32
  ret i32 %p2i
}
