; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i32 @invert_shl_masked(i32 %a, i32 %b) {
; CHECK-LABEL: invert_shl_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi a4, 3
; CHECK-NEXT:    or a3, a3, a4
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    sll a2, a2
; CHECK-NEXT:    ret.n
  %c = or i32 %b, 3
  %amt = sub i32 32, %c
  %shl = shl i32 %a, %amt
  ret i32 %shl
}

define i32 @invert_lshr_masked(i32 %a, i32 %b) {
; CHECK-LABEL: invert_lshr_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi a4, 3
; CHECK-NEXT:    or a3, a3, a4
; CHECK-NEXT:    ssl a3
; CHECK-NEXT:    srl a2, a2
; CHECK-NEXT:    ret.n
  %c = or i32 %b, 3
  %amt = sub i32 32, %c
  %lshr = lshr i32 %a, %amt
  ret i32 %lshr
}
