; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i8 @load_i8(ptr %p) {
; CHECK-LABEL: load_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    ret.n
entry:
  %load = load i8, ptr %p, align 1
  ret i8 %load
}

define i16 @load_i16(ptr %p) {
; CHECK-LABEL: load_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
entry:
  %load = load i16, ptr %p, align 2
  ret i16 %load
}

define i16 @load_i16_unaligned_1(ptr %p) {
; CHECK-LABEL: load_i16_unaligned_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l8ui a3, a2, 0
; CHECK-NEXT:    addi a2, a2, 1
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    slli a2, a2, 8
; CHECK-NEXT:    or a2, a2, a3
; CHECK-NEXT:    ret.n
entry:
  %load = load i16, ptr %p, align 1
  ret i16 %load
}

define i32 @load_i32(ptr %p) {
; CHECK-LABEL: load_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
entry:
  %load = load i32, ptr %p, align 4
  ret i32 %load
}

define i32 @load_i32_unaligned_1(ptr %p) {
; CHECK-LABEL: load_i32_unaligned_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l8ui a3, a2, 0
; CHECK-NEXT:    addi a4, a2, 1
; CHECK-NEXT:    l8ui a4, a4, 0
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    addi a4, a2, 2
; CHECK-NEXT:    l8ui a4, a4, 0
; CHECK-NEXT:    addi a2, a2, 3
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    or a2, a2, a3
; CHECK-NEXT:    ret.n
entry:
  %load = load i32, ptr %p, align 1
  ret i32 %load
}

define i32 @load_i32_unaligned_2(ptr %p) {
; CHECK-LABEL: load_i32_unaligned_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l16ui a3, a2, 0
; CHECK-NEXT:    addi a2, a2, 2
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    slli a2, a2, 16
; CHECK-NEXT:    or a2, a2, a3
; CHECK-NEXT:    ret.n
entry:
  %load = load i32, ptr %p, align 2
  ret i32 %load
}

define i64 @load_i64(ptr %p) {
; CHECK-LABEL: load_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32i.n a4, a2, 0
; CHECK-NEXT:    addi a2, a2, 4
; CHECK-NEXT:    l32i.n a3, a2, 0
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
entry:
  %load = load i64, ptr %p, align 8
  ret i64 %load
}

define i64 @load_i64_unaligned_1(ptr %p) {
; CHECK-LABEL: load_i64_unaligned_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l8ui a3, a2, 0
; CHECK-NEXT:    addi a4, a2, 1
; CHECK-NEXT:    l8ui a4, a4, 0
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    addi a4, a2, 2
; CHECK-NEXT:    l8ui a4, a4, 0
; CHECK-NEXT:    addi a5, a2, 3
; CHECK-NEXT:    l8ui a5, a5, 0
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a4, a4, a3
; CHECK-NEXT:    addi a3, a2, 4
; CHECK-NEXT:    l8ui a3, a3, 0
; CHECK-NEXT:    addi a5, a2, 5
; CHECK-NEXT:    l8ui a5, a5, 0
; CHECK-NEXT:    slli a5, a5, 8
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    addi a5, a2, 6
; CHECK-NEXT:    l8ui a5, a5, 0
; CHECK-NEXT:    addi a2, a2, 7
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    slli a5, a5, 16
; CHECK-NEXT:    or a2, a2, a5
; CHECK-NEXT:    or a3, a2, a3
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
entry:
  %load = load i64, ptr %p, align 1
  ret i64 %load
}

define i64 @load_i64_unaligned_2(ptr %p) {
; CHECK-LABEL: load_i64_unaligned_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l16ui a3, a2, 0
; CHECK-NEXT:    addi a4, a2, 2
; CHECK-NEXT:    l16ui a4, a4, 0
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    or a4, a4, a3
; CHECK-NEXT:    addi a3, a2, 4
; CHECK-NEXT:    l16ui a3, a3, 0
; CHECK-NEXT:    addi a2, a2, 6
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    slli a2, a2, 16
; CHECK-NEXT:    or a3, a2, a3
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
entry:
  %load = load i64, ptr %p, align 2
  ret i64 %load
}

define i64 @load_i64_unaligned_4(ptr %p) {
; CHECK-LABEL: load_i64_unaligned_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32i.n a4, a2, 0
; CHECK-NEXT:    addi a2, a2, 4
; CHECK-NEXT:    l32i.n a3, a2, 0
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
entry:
  %load = load i64, ptr %p, align 4
  ret i64 %load
}
