; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i32 @movin_zero() {
; CHECK-LABEL: movin_zero:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, 0
; CHECK-NEXT:    ret.n
entry:
  ret i32 0
}

define i32 @movin_one() {
; CHECK-LABEL: movin_one:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, 1
; CHECK-NEXT:    ret.n
entry:
  ret i32 1
}

define i32 @movin_neg_one() {
; CHECK-LABEL: movin_neg_one:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, -1
; CHECK-NEXT:    ret.n
entry:
  ret i32 -1
}

define i32 @movin_positive() {
; CHECK-LABEL: movin_positive:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, 7
; CHECK-NEXT:    ret.n
entry:
  ret i32 7
}

define i32 @movin_positive_limit() {
; CHECK-LABEL: movin_positive_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, 95
; CHECK-NEXT:    ret.n
entry:
  ret i32 95
}

define i32 @movi_positive_low_limit() {
; CHECK-LABEL: movi_positive_low_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, 96
; CHECK-NEXT:    ret.n
entry:
  ret i32 96
}

define i32 @movi_positive() {
; CHECK-LABEL: movi_positive:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, 356
; CHECK-NEXT:    ret.n
entry:
  ret i32 356
}

define i32 @movi_positive_high_limit() {
; CHECK-LABEL: movi_positive_high_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, 2047
; CHECK-NEXT:    ret.n
entry:
  ret i32 2047
}

define i32 @movin_negative() {
; CHECK-LABEL: movin_negative:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, -7
; CHECK-NEXT:    ret.n
entry:
  ret i32 -7
}

define i32 @movin_negative_limit() {
; CHECK-LABEL: movin_negative_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, -32
; CHECK-NEXT:    ret.n
entry:
  ret i32 -32
}

define i32 @movi_negative_high_limit() {
; CHECK-LABEL: movi_negative_high_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, -33
; CHECK-NEXT:    ret.n
entry:
  ret i32 -33
}

define i32 @movi_negative() {
; CHECK-LABEL: movi_negative:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, -800
; CHECK-NEXT:    ret.n
entry:
  ret i32 -800
}

define i32 @movi_negative_low_limit() {
; CHECK-LABEL: movi_negative_low_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi a2, -2048
; CHECK-NEXT:    ret.n
entry:
  ret i32 -2048
}

define i32 @not_movi_positive_low_limit() {
; CHECK-LABEL: not_movi_positive_low_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI13_0
; CHECK-NEXT:    ret.n
entry:
  ret i32 2048
}

define i32 @not_movi_negative_high_limit() {
; CHECK-LABEL: not_movi_negative_high_limit:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI14_0
; CHECK-NEXT:    ret.n
entry:
  ret i32 -2049
}

define i32 @not_movi_max() {
; CHECK-LABEL: not_movi_max:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI15_0
; CHECK-NEXT:    ret.n
entry:
  ret i32 2147483647
}

define i32 @not_movi_min() {
; CHECK-LABEL: not_movi_min:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI16_0
; CHECK-NEXT:    ret.n
entry:
  ret i32 -2147483648
}

define i64 @i64_split_not_movi_not_movi() {
; CHECK-LABEL: i64_split_not_movi_not_movi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI17_1
; CHECK-NEXT:    l32r a3, .LCPI17_0
; CHECK-NEXT:    ret.n
entry:
  ret i64 20014853001780
}

define i64 @i64_split_movi_not_movi() {
; CHECK-LABEL: i64_split_movi_not_movi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    l32r a2, .LCPI18_0
; CHECK-NEXT:    movi a3, 255
; CHECK-NEXT:    ret.n
entry:
  ret i64 1095522062900
}

define i64 @i64_split_movin_movi() {
; CHECK-LABEL: i64_split_movin_movi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movi.n a2, -1
; CHECK-NEXT:    movi a3, 291
; CHECK-NEXT:    ret.n
entry:
  ret i64 1254130450431
}
