; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s --check-prefix=OPT
; RUN: llc -O0 < %s -mtriple=xtensa | FileCheck %s --check-prefix=UNOPT

define i32 @movin_zero() {
; OPT-LABEL: movin_zero:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, 0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_zero:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, 0
; UNOPT-NEXT:    ret.n
entry:
  ret i32 0
}

define i32 @movin_one() {
; OPT-LABEL: movin_one:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, 1
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_one:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, 1
; UNOPT-NEXT:    ret.n
entry:
  ret i32 1
}

define i32 @movin_neg_one() {
; OPT-LABEL: movin_neg_one:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, -1
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_neg_one:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, -1
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -1
}

define i32 @movin_positive() {
; OPT-LABEL: movin_positive:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, 7
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_positive:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, 7
; UNOPT-NEXT:    ret.n
entry:
  ret i32 7
}

define i32 @movin_positive_limit() {
; OPT-LABEL: movin_positive_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, 95
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_positive_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, 95
; UNOPT-NEXT:    ret.n
entry:
  ret i32 95
}

define i32 @movi_positive_low_limit() {
; OPT-LABEL: movi_positive_low_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, 96
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_positive_low_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, 96
; UNOPT-NEXT:    ret.n
entry:
  ret i32 96
}

define i32 @movi_positive() {
; OPT-LABEL: movi_positive:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, 356
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_positive:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, 356
; UNOPT-NEXT:    ret.n
entry:
  ret i32 356
}

define i32 @movi_positive_high_limit() {
; OPT-LABEL: movi_positive_high_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, 2047
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_positive_high_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, 2047
; UNOPT-NEXT:    ret.n
entry:
  ret i32 2047
}

define i32 @movin_negative() {
; OPT-LABEL: movin_negative:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, -7
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_negative:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, -7
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -7
}

define i32 @movin_negative_limit() {
; OPT-LABEL: movin_negative_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, -32
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movin_negative_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, -32
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -32
}

define i32 @movi_negative_high_limit() {
; OPT-LABEL: movi_negative_high_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, -33
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_negative_high_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, -33
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -33
}

define i32 @movi_negative() {
; OPT-LABEL: movi_negative:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, -800
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_negative:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, -800
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -800
}

define i32 @movi_negative_low_limit() {
; OPT-LABEL: movi_negative_low_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi a2, -2048
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: movi_negative_low_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi a2, -2048
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -2048
}

define i32 @not_movi_positive_low_limit() {
; OPT-LABEL: not_movi_positive_low_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI13_0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: not_movi_positive_low_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI13_0
; UNOPT-NEXT:    ret.n
entry:
  ret i32 2048
}

define i32 @not_movi_negative_high_limit() {
; OPT-LABEL: not_movi_negative_high_limit:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI14_0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: not_movi_negative_high_limit:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI14_0
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -2049
}

define i32 @not_movi_max() {
; OPT-LABEL: not_movi_max:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI15_0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: not_movi_max:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI15_0
; UNOPT-NEXT:    ret.n
entry:
  ret i32 2147483647
}

define i32 @not_movi_min() {
; OPT-LABEL: not_movi_min:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI16_0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: not_movi_min:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI16_0
; UNOPT-NEXT:    ret.n
entry:
  ret i32 -2147483648
}

define i64 @i64_split_not_movi_not_movi() {
; OPT-LABEL: i64_split_not_movi_not_movi:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI17_1
; OPT-NEXT:    l32r a3, .LCPI17_0
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: i64_split_not_movi_not_movi:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI17_1
; UNOPT-NEXT:    l32r a3, .LCPI17_0
; UNOPT-NEXT:    ret.n
entry:
  ret i64 20014853001780
}

define i64 @i64_split_movi_not_movi() {
; OPT-LABEL: i64_split_movi_not_movi:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    l32r a2, .LCPI18_0
; OPT-NEXT:    movi a3, 255
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: i64_split_movi_not_movi:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    l32r a2, .LCPI18_0
; UNOPT-NEXT:    movi a3, 255
; UNOPT-NEXT:    ret.n
entry:
  ret i64 1095522062900
}

define i64 @i64_split_movin_movi() {
; OPT-LABEL: i64_split_movin_movi:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a2, -1
; OPT-NEXT:    movi a3, 291
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: i64_split_movin_movi:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    movi.n a2, -1
; UNOPT-NEXT:    movi a3, 291
; UNOPT-NEXT:    ret.n
entry:
  ret i64 1254130450431
}
