; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i32 @neg(i32 %val) {
; CHECK-LABEL: neg:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    neg a2, a2
; CHECK-NEXT:    ret.n
entry:
  %neg = sub i32 0, %val
  ret i32 %neg
}
