; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i8 @offset_load_i8(ptr %base) {
; CHECK-LABEL: offset_load_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a2, a2, 5
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 5
  %load = load i8, ptr %p
  ret i8 %load
}

define i8 @offset_load_i8_oob(ptr %base) {
; CHECK-LABEL: offset_load_i8_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 256
; CHECK-NEXT:    l8ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 256
  %load = load i8, ptr %p
  ret i8 %load
}

define i16 @offset_load_i16(ptr %base) {
; CHECK-LABEL: offset_load_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l16ui a2, a2, 10
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 5
  %load = load i16, ptr %p
  ret i16 %load
}

define i16 @offset_load_i16_unaligned_off(ptr %base) {
; CHECK-LABEL: offset_load_i16_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a2, a2, 11
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 11
  %load = load i16, ptr %p
  ret i16 %load
}

define i16 @offset_load_i16_oob(ptr %base) {
; CHECK-LABEL: offset_load_i16_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 512
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 256
  %load = load i16, ptr %p
  ret i16 %load
}

define i16 @offset_load_i16_oob2(ptr %base) {
; CHECK-LABEL: offset_load_i16_oob2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 512
; CHECK-NEXT:    addi a2, a2, 88
; CHECK-NEXT:    l16ui a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 300
  %load = load i16, ptr %p
  ret i16 %load
}

define i16 @offset_load_i16_unaligned(ptr %base) {
; CHECK-LABEL: offset_load_i16_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a3, a2, 10
; CHECK-NEXT:    l8ui a2, a2, 11
; CHECK-NEXT:    slli a2, a2, 8
; CHECK-NEXT:    or a2, a2, a3
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 5
  %load = load i16, ptr %p, align 1
  ret i16 %load
}

define i32 @offset_load_i32(ptr %base) {
; CHECK-LABEL: offset_load_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i.n a2, a2, 20
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_narrow_max(ptr %base) {
; CHECK-LABEL: offset_load_i32_narrow_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i.n a2, a2, 60
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 15
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_narrow_oob(ptr %base) {
; CHECK-LABEL: offset_load_i32_narrow_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i a2, a2, 64
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 16
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_unaligned_off(ptr %base) {
; CHECK-LABEL: offset_load_i32_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a2, a2, 22
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 22
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_oob(ptr %base) {
; CHECK-LABEL: offset_load_i32_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 1024
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 256
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_oob2(ptr %base) {
; CHECK-LABEL: offset_load_i32_oob2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 1280
; CHECK-NEXT:    addi a2, a2, -80
; CHECK-NEXT:    l32i.n a2, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 300
  %load = load i32, ptr %p
  ret i32 %load
}

define i32 @offset_load_i32_unaligned(ptr %base) {
; CHECK-LABEL: offset_load_i32_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a3, a2, 20
; CHECK-NEXT:    l8ui a4, a2, 21
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    l8ui a4, a2, 22
; CHECK-NEXT:    l8ui a2, a2, 23
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    or a2, a2, a3
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  %load = load i32, ptr %p, align 1
  ret i32 %load
}

define i64 @offset_load_i64(ptr %base) {
; CHECK-LABEL: offset_load_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i.n a4, a2, 40
; CHECK-NEXT:    l32i.n a3, a2, 44
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 5
  %load = load i64, ptr %p
  ret i64 %load
}

define i64 @offset_load_i64_unaligned_off4(ptr %base) {
; CHECK-LABEL: offset_load_i64_unaligned_off4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l32i.n a4, a2, 20
; CHECK-NEXT:    l32i.n a3, a2, 24
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  %load = load i64, ptr %p
  ret i64 %load
}

define i64 @offset_load_i64_unaligned_off(ptr %base) {
; CHECK-LABEL: offset_load_i64_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a3, a2, 21
; CHECK-NEXT:    l32i.n a4, a3, 0
; CHECK-NEXT:    addi a2, a2, 25
; CHECK-NEXT:    l32i.n a3, a2, 0
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 21
  %load = load i64, ptr %p
  ret i64 %load
}

define i64 @offset_load_i64_unaligned(ptr %base) {
; CHECK-LABEL: offset_load_i64_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    l8ui a3, a2, 40
; CHECK-NEXT:    l8ui a4, a2, 41
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    l8ui a4, a2, 42
; CHECK-NEXT:    l8ui a5, a2, 43
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a4, a4, a3
; CHECK-NEXT:    l8ui a3, a2, 44
; CHECK-NEXT:    l8ui a5, a2, 45
; CHECK-NEXT:    slli a5, a5, 8
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    l8ui a5, a2, 46
; CHECK-NEXT:    l8ui a2, a2, 47
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    slli a5, a5, 16
; CHECK-NEXT:    or a2, a2, a5
; CHECK-NEXT:    or a3, a2, a3
; CHECK-NEXT:    mov.n a2, a4
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 5
  %load = load i64, ptr %p, align 1
  ret i64 %load
}
