; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define void @offset_store_i8(ptr %base, i8 %val) {
; CHECK-LABEL: offset_store_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s8i a3, a2, 5
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 5
  store i8 %val, ptr %p
  ret void
}

define void @offset_store_i8_oob(ptr %base, i8 %val) {
; CHECK-LABEL: offset_store_i8_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 256
; CHECK-NEXT:    s8i a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 256
  store i8 %val, ptr %p
  ret void
}

define void @offset_store_i16(ptr %base, i16 %val) {
; CHECK-LABEL: offset_store_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s16i a3, a2, 10
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 5
  store i16 %val, ptr %p
  ret void
}

define void @offset_store_i16_unaligned_off(ptr %base, i16 %val) {
; CHECK-LABEL: offset_store_i16_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a2, a2, 11
; CHECK-NEXT:    s16i a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 11
  store i16 %val, ptr %p
  ret void
}

define void @offset_store_i16_oob(ptr %base, i16 %val) {
; CHECK-LABEL: offset_store_i16_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 512
; CHECK-NEXT:    s16i a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 256
  store i16 %val, ptr %p
  ret void
}

define void @offset_store_i16_oob2(ptr %base, i16 %val) {
; CHECK-LABEL: offset_store_i16_oob2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi a4, 600
; CHECK-NEXT:    add.n a2, a2, a4
; CHECK-NEXT:    s16i a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 300
  store i16 %val, ptr %p
  ret void
}

define void @offset_store_i16_unaligned(ptr %base, i16 %val) {
; CHECK-LABEL: offset_store_i16_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a4, a3, 0, 16
; CHECK-NEXT:    srli a4, a4, 8
; CHECK-NEXT:    s8i a3, a2, 10
; CHECK-NEXT:    s8i a4, a2, 11
; CHECK-NEXT:    ret.n
  %p = getelementptr i16, ptr %base, i32 5
  store i16 %val, ptr %p, align 1
  ret void
}

define void @offset_store_i32(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s32i.n a3, a2, 20
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_narrow_max(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_narrow_max:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s32i.n a3, a2, 60
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 15
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_narrow_oob(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_narrow_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s32i a3, a2, 64
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 16
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_unaligned_off(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a2, a2, 22
; CHECK-NEXT:    s32i.n a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 22
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_oob(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_oob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addmi a2, a2, 1024
; CHECK-NEXT:    s32i.n a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 256
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_oob2(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_oob2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi a4, 1200
; CHECK-NEXT:    add.n a2, a2, a4
; CHECK-NEXT:    s32i.n a3, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 300
  store i32 %val, ptr %p
  ret void
}

define void @offset_store_i32_unaligned(ptr %base, i32 %val) {
; CHECK-LABEL: offset_store_i32_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a4, a3, 16, 16
; CHECK-NEXT:    extui a5, a3, 0, 16
; CHECK-NEXT:    srli a5, a5, 8
; CHECK-NEXT:    s8i a3, a2, 20
; CHECK-NEXT:    s8i a5, a2, 21
; CHECK-NEXT:    extui a3, a3, 24, 8
; CHECK-NEXT:    s8i a4, a2, 22
; CHECK-NEXT:    s8i a3, a2, 23
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  store i32 %val, ptr %p, align 1
  ret void
}

define void @offset_store_i64(ptr %base, i64 %val) {
; CHECK-LABEL: offset_store_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s32i.n a4, a2, 40
; CHECK-NEXT:    s32i.n a5, a2, 44
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 5
  store i64 %val, ptr %p
  ret void
}

define void @offset_store_i64_unaligned_off4(ptr %base, i64 %val) {
; CHECK-LABEL: offset_store_i64_unaligned_off4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    s32i.n a4, a2, 20
; CHECK-NEXT:    s32i.n a5, a2, 24
; CHECK-NEXT:    ret.n
  %p = getelementptr i32, ptr %base, i32 5
  store i64 %val, ptr %p
  ret void
}

define void @offset_store_i64_unaligned_off(ptr %base, i64 %val) {
; CHECK-LABEL: offset_store_i64_unaligned_off:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi a3, a2, 21
; CHECK-NEXT:    s32i.n a4, a3, 0
; CHECK-NEXT:    addi a2, a2, 25
; CHECK-NEXT:    s32i.n a5, a2, 0
; CHECK-NEXT:    ret.n
  %p = getelementptr i8, ptr %base, i32 21
  store i64 %val, ptr %p
  ret void
}

define void @offset_store_i64_unaligned(ptr %base, i64 %val) {
; CHECK-LABEL: offset_store_i64_unaligned:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a3, a4, 16, 16
; CHECK-NEXT:    extui a6, a4, 0, 16
; CHECK-NEXT:    srli a6, a6, 8
; CHECK-NEXT:    s8i a4, a2, 40
; CHECK-NEXT:    s8i a6, a2, 41
; CHECK-NEXT:    extui a4, a4, 24, 8
; CHECK-NEXT:    s8i a3, a2, 42
; CHECK-NEXT:    s8i a4, a2, 43
; CHECK-NEXT:    extui a3, a5, 16, 16
; CHECK-NEXT:    extui a4, a5, 0, 16
; CHECK-NEXT:    srli a4, a4, 8
; CHECK-NEXT:    s8i a5, a2, 44
; CHECK-NEXT:    s8i a4, a2, 45
; CHECK-NEXT:    extui a4, a5, 24, 8
; CHECK-NEXT:    s8i a3, a2, 46
; CHECK-NEXT:    s8i a4, a2, 47
; CHECK-NEXT:    ret.n
  %p = getelementptr i64, ptr %base, i32 5
  store i64 %val, ptr %p, align 1
  ret void
}
