; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i32 @rev_shl(i32 %a, i32 %b) {
; CHECK-LABEL: rev_shl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movi.n a4, 32
; CHECK-NEXT:    sub a3, a4, a3
; CHECK-NEXT:    ssl a3
; CHECK-NEXT:    sll a2, a2
; CHECK-NEXT:    ret.n
  %shamt = sub i32 32, %b
  %shl = shl i32 %a, %shamt
  ret i32 %shl
}
