; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i1 @select_i1(i1 %val, i1 %a, i1 %b) {
; CHECK-LABEL: select_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    moveqz a3, a4, a2
; CHECK-NEXT:    mov.n a2, a3
; CHECK-NEXT:    ret.n
  %select = select i1 %val, i1 %a, i1 %b
  ret i1 %select
}

define i8 @select_i8(i1 %val, i8 %a, i8 %b) {
; CHECK-LABEL: select_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    moveqz a3, a4, a2
; CHECK-NEXT:    mov.n a2, a3
; CHECK-NEXT:    ret.n
  %select = select i1 %val, i8 %a, i8 %b
  ret i8 %select
}

define i16 @select_i16(i1 %val, i16 %a, i16 %b) {
; CHECK-LABEL: select_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    moveqz a3, a4, a2
; CHECK-NEXT:    mov.n a2, a3
; CHECK-NEXT:    ret.n
  %select = select i1 %val, i16 %a, i16 %b
  ret i16 %select
}

define i32 @select_i32(i1 %val, i32 %a, i32 %b) {
; CHECK-LABEL: select_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    extui a2, a2, 0, 1
; CHECK-NEXT:    moveqz a3, a4, a2
; CHECK-NEXT:    mov.n a2, a3
; CHECK-NEXT:    ret.n
  %select = select i1 %val, i32 %a, i32 %b
  ret i32 %select
}
