; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s
define i8 @shl_i8(i8 %val, i8 %shamt) {
; CHECK-LABEL: shl_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 8
; CHECK-NEXT:    ssl a3
; CHECK-NEXT:    sll a2, a2
; CHECK-NEXT:    ret.n
entry:
  %shl = shl i8 %val, %shamt
  ret i8 %shl
}

define i16 @shl_i16(i16 %val, i16 %shamt) {
; CHECK-LABEL: shl_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 16
; CHECK-NEXT:    ssl a3
; CHECK-NEXT:    sll a2, a2
; CHECK-NEXT:    ret.n
entry:
  %shl = shl i16 %val, %shamt
  ret i16 %shl
}

define i32 @shl_i32(i32 %val, i32 %shamt) {
; CHECK-LABEL: shl_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ssl a3
; CHECK-NEXT:    sll a2, a2
; CHECK-NEXT:    ret.n
entry:
  %shl = shl i32 %val, %shamt
  ret i32 %shl
}

define i8 @lshr_i8(i8 %val, i8 %shamt) {
; CHECK-LABEL: lshr_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 8
; CHECK-NEXT:    extui a2, a2, 0, 8
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    srl a2, a2
; CHECK-NEXT:    ret.n
entry:
  %lshr = lshr i8 %val, %shamt
  ret i8 %lshr
}

define i16 @lshr_i16(i16 %val, i16 %shamt) {
; CHECK-LABEL: lshr_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 16
; CHECK-NEXT:    extui a2, a2, 0, 16
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    srl a2, a2
; CHECK-NEXT:    ret.n
entry:
  %lshr = lshr i16 %val, %shamt
  ret i16 %lshr
}

define i32 @lshr_i32(i32 %val, i32 %shamt) {
; CHECK-LABEL: lshr_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    srl a2, a2
; CHECK-NEXT:    ret.n
entry:
  %lshr = lshr i32 %val, %shamt
  ret i32 %lshr
}

define i8 @ashr_i8(i8 %val, i8 %shamt) {
; CHECK-LABEL: ashr_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 8
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    srai a2, a2, 24
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    sra a2, a2
; CHECK-NEXT:    ret.n
entry:
  %ashr = ashr i8 %val, %shamt
  ret i8 %ashr
}

define i16 @ashr_i16(i16 %val, i16 %shamt) {
; CHECK-LABEL: ashr_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    extui a3, a3, 0, 16
; CHECK-NEXT:    slli a2, a2, 16
; CHECK-NEXT:    srai a2, a2, 16
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    sra a2, a2
; CHECK-NEXT:    ret.n
entry:
  %ashr = ashr i16 %val, %shamt
  ret i16 %ashr
}

define i32 @ashr_i32(i32 %val, i32 %shamt) {
; CHECK-LABEL: ashr_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ssr a3
; CHECK-NEXT:    sra a2, a2
; CHECK-NEXT:    ret.n
entry:
  %ashr = ashr i32 %val, %shamt
  ret i32 %ashr
}
