; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s --check-prefix=OPT
; RUN: llc -O0 < %s -mtriple=xtensa | FileCheck %s --check-prefix=UNOPT

define i33 @shl_i33(i33 %val, i33 %shamt) {
; OPT-LABEL: shl_i33:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a5, 32
; OPT-NEXT:    saltu a7, a4, a5
; OPT-NEXT:    ssl a4
; OPT-NEXT:    sll a5, a2
; OPT-NEXT:    neg a6, a4
; OPT-NEXT:    ssr a6
; OPT-NEXT:    srl a6, a2
; OPT-NEXT:    ssl a4
; OPT-NEXT:    sll a8, a3
; OPT-NEXT:    or a6, a6, a8
; OPT-NEXT:    sll a2, a2
; OPT-NEXT:    movi.n a8, 0
; OPT-NEXT:    moveqz a5, a8, a7
; OPT-NEXT:    moveqz a6, a2, a7
; OPT-NEXT:    moveqz a6, a3, a4
; OPT-NEXT:    mov.n a2, a5
; OPT-NEXT:    mov.n a3, a6
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: shl_i33:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a6, a2
; UNOPT-NEXT:    mov.n a9, a4
; UNOPT-NEXT:    movi.n a2, 32
; UNOPT-NEXT:    addi a8, a9, -32
; UNOPT-NEXT:    sub a4, a2, a9
; UNOPT-NEXT:    saltu a7, a9, a2
; UNOPT-NEXT:    movi.n a2, 1
; UNOPT-NEXT:    movi.n a5, 0
; UNOPT-NEXT:    moveqz a5, a2, a9
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a2, a6
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    srl a4, a6
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a9, a3
; UNOPT-NEXT:    or a4, a4, a9
; UNOPT-NEXT:    ssl a8
; UNOPT-NEXT:    sll a6, a6
; UNOPT-NEXT:    extui a9, a7, 0, 1
; UNOPT-NEXT:    movi.n a8, 0
; UNOPT-NEXT:    moveqz a2, a8, a9
; UNOPT-NEXT:    extui a7, a7, 0, 1
; UNOPT-NEXT:    moveqz a4, a6, a7
; UNOPT-NEXT:    extui a5, a5, 0, 1
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %shl = shl i33 %val, %shamt
  ret i33 %shl
}

define i64 @shl_i64(i64 %val, i64 %shamt) {
; OPT-LABEL: shl_i64:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a5, 32
; OPT-NEXT:    saltu a7, a4, a5
; OPT-NEXT:    ssl a4
; OPT-NEXT:    sll a5, a2
; OPT-NEXT:    neg a6, a4
; OPT-NEXT:    ssr a6
; OPT-NEXT:    srl a6, a2
; OPT-NEXT:    ssl a4
; OPT-NEXT:    sll a8, a3
; OPT-NEXT:    or a6, a6, a8
; OPT-NEXT:    sll a2, a2
; OPT-NEXT:    movi.n a8, 0
; OPT-NEXT:    moveqz a5, a8, a7
; OPT-NEXT:    moveqz a6, a2, a7
; OPT-NEXT:    moveqz a6, a3, a4
; OPT-NEXT:    mov.n a2, a5
; OPT-NEXT:    mov.n a3, a6
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: shl_i64:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a6, a2
; UNOPT-NEXT:    mov.n a9, a4
; UNOPT-NEXT:    movi.n a2, 32
; UNOPT-NEXT:    addi a8, a9, -32
; UNOPT-NEXT:    sub a4, a2, a9
; UNOPT-NEXT:    saltu a7, a9, a2
; UNOPT-NEXT:    movi.n a2, 1
; UNOPT-NEXT:    movi.n a5, 0
; UNOPT-NEXT:    moveqz a5, a2, a9
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a2, a6
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    srl a4, a6
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a9, a3
; UNOPT-NEXT:    or a4, a4, a9
; UNOPT-NEXT:    ssl a8
; UNOPT-NEXT:    sll a6, a6
; UNOPT-NEXT:    extui a9, a7, 0, 1
; UNOPT-NEXT:    movi.n a8, 0
; UNOPT-NEXT:    moveqz a2, a8, a9
; UNOPT-NEXT:    extui a7, a7, 0, 1
; UNOPT-NEXT:    moveqz a4, a6, a7
; UNOPT-NEXT:    extui a5, a5, 0, 1
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %shl = shl i64 %val, %shamt
  ret i64 %shl
}

define i33 @lshr_i33(i33 %val, i33 %shamt) {
; OPT-LABEL: lshr_i33:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    extui a6, a3, 0, 1
; OPT-NEXT:    movi.n a3, 32
; OPT-NEXT:    saltu a7, a4, a3
; OPT-NEXT:    ssr a4
; OPT-NEXT:    srl a3, a6
; OPT-NEXT:    srl a5, a2
; OPT-NEXT:    neg a8, a4
; OPT-NEXT:    ssl a8
; OPT-NEXT:    sll a8, a6
; OPT-NEXT:    or a5, a5, a8
; OPT-NEXT:    ssr a4
; OPT-NEXT:    srl a6, a6
; OPT-NEXT:    moveqz a5, a6, a7
; OPT-NEXT:    moveqz a5, a2, a4
; OPT-NEXT:    movi.n a2, 0
; OPT-NEXT:    moveqz a3, a2, a7
; OPT-NEXT:    mov.n a2, a5
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: lshr_i33:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a5, a4
; UNOPT-NEXT:    movi.n a4, -1
; UNOPT-NEXT:    and a2, a2, a4
; UNOPT-NEXT:    extui a7, a3, 0, 1
; UNOPT-NEXT:    movi.n a3, 32
; UNOPT-NEXT:    addi a8, a5, -32
; UNOPT-NEXT:    sub a9, a3, a5
; UNOPT-NEXT:    saltu a4, a5, a3
; UNOPT-NEXT:    movi.n a3, 1
; UNOPT-NEXT:    movi.n a6, 0
; UNOPT-NEXT:    moveqz a6, a3, a5
; UNOPT-NEXT:    ssr a5
; UNOPT-NEXT:    srl a3, a7
; UNOPT-NEXT:    ssr a5
; UNOPT-NEXT:    srl a5, a2
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a9, a7
; UNOPT-NEXT:    or a5, a5, a9
; UNOPT-NEXT:    ssr a8
; UNOPT-NEXT:    srl a7, a7
; UNOPT-NEXT:    extui a8, a4, 0, 1
; UNOPT-NEXT:    moveqz a5, a7, a8
; UNOPT-NEXT:    extui a6, a6, 0, 1
; UNOPT-NEXT:    moveqz a2, a5, a6
; UNOPT-NEXT:    extui a5, a4, 0, 1
; UNOPT-NEXT:    movi.n a4, 0
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %lshr = lshr i33 %val, %shamt
  ret i33 %lshr
}

define i64 @lshr_i64(i64 %val, i64 %shamt) {
; OPT-LABEL: lshr_i64:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a5, 32
; OPT-NEXT:    saltu a7, a4, a5
; OPT-NEXT:    ssr a4
; OPT-NEXT:    srl a5, a3
; OPT-NEXT:    srl a6, a2
; OPT-NEXT:    neg a8, a4
; OPT-NEXT:    ssl a8
; OPT-NEXT:    sll a8, a3
; OPT-NEXT:    or a6, a6, a8
; OPT-NEXT:    ssr a4
; OPT-NEXT:    srl a3, a3
; OPT-NEXT:    moveqz a6, a3, a7
; OPT-NEXT:    moveqz a6, a2, a4
; OPT-NEXT:    movi.n a2, 0
; OPT-NEXT:    moveqz a5, a2, a7
; OPT-NEXT:    mov.n a2, a6
; OPT-NEXT:    mov.n a3, a5
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: lshr_i64:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a7, a3
; UNOPT-NEXT:    mov.n a5, a4
; UNOPT-NEXT:    movi.n a3, 32
; UNOPT-NEXT:    addi a8, a5, -32
; UNOPT-NEXT:    sub a9, a3, a5
; UNOPT-NEXT:    saltu a4, a5, a3
; UNOPT-NEXT:    movi.n a3, 1
; UNOPT-NEXT:    movi.n a6, 0
; UNOPT-NEXT:    moveqz a6, a3, a5
; UNOPT-NEXT:    ssr a5
; UNOPT-NEXT:    srl a3, a7
; UNOPT-NEXT:    ssr a5
; UNOPT-NEXT:    srl a5, a2
; UNOPT-NEXT:    ssl a9
; UNOPT-NEXT:    sll a9, a7
; UNOPT-NEXT:    or a5, a5, a9
; UNOPT-NEXT:    ssr a8
; UNOPT-NEXT:    srl a7, a7
; UNOPT-NEXT:    extui a8, a4, 0, 1
; UNOPT-NEXT:    moveqz a5, a7, a8
; UNOPT-NEXT:    extui a6, a6, 0, 1
; UNOPT-NEXT:    moveqz a2, a5, a6
; UNOPT-NEXT:    extui a5, a4, 0, 1
; UNOPT-NEXT:    movi.n a4, 0
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %lshr = lshr i64 %val, %shamt
  ret i64 %lshr
}

define i33 @ashr_i33(i33 %val, i33 %shamt) {
; OPT-LABEL: ashr_i33:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    slli a5, a2, 31
; OPT-NEXT:    slli a3, a3, 31
; OPT-NEXT:    srli a2, a2, 1
; OPT-NEXT:    or a2, a3, a2
; OPT-NEXT:    extui a3, a5, 31, 1
; OPT-NEXT:    slli a5, a2, 1
; OPT-NEXT:    or a5, a3, a5
; OPT-NEXT:    srai a6, a2, 31
; OPT-NEXT:    movi.n a2, 32
; OPT-NEXT:    saltu a7, a4, a2
; OPT-NEXT:    ssr a4
; OPT-NEXT:    sra a3, a6
; OPT-NEXT:    srl a2, a5
; OPT-NEXT:    neg a8, a4
; OPT-NEXT:    ssl a8
; OPT-NEXT:    sll a8, a6
; OPT-NEXT:    or a2, a2, a8
; OPT-NEXT:    ssr a4
; OPT-NEXT:    sra a8, a6
; OPT-NEXT:    moveqz a2, a8, a7
; OPT-NEXT:    moveqz a2, a5, a4
; OPT-NEXT:    moveqz a3, a6, a7
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: ashr_i33:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a5, a2
; UNOPT-NEXT:    slli a2, a5, 31
; UNOPT-NEXT:    slli a3, a3, 31
; UNOPT-NEXT:    srli a5, a5, 1
; UNOPT-NEXT:    or a3, a3, a5
; UNOPT-NEXT:    extui a2, a2, 31, 1
; UNOPT-NEXT:    slli a5, a3, 1
; UNOPT-NEXT:    or a2, a2, a5
; UNOPT-NEXT:    srai a8, a3, 31
; UNOPT-NEXT:    movi.n a3, 32
; UNOPT-NEXT:    addi a9, a4, -32
; UNOPT-NEXT:    sub a6, a3, a4
; UNOPT-NEXT:    saltu a5, a4, a3
; UNOPT-NEXT:    movi.n a3, 1
; UNOPT-NEXT:    movi.n a7, 0
; UNOPT-NEXT:    moveqz a7, a3, a4
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    sra a3, a8
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    srl a4, a2
; UNOPT-NEXT:    ssl a6
; UNOPT-NEXT:    sll a6, a8
; UNOPT-NEXT:    or a6, a4, a6
; UNOPT-NEXT:    srai a4, a8, 31
; UNOPT-NEXT:    ssr a9
; UNOPT-NEXT:    sra a8, a8
; UNOPT-NEXT:    extui a9, a5, 0, 1
; UNOPT-NEXT:    moveqz a6, a8, a9
; UNOPT-NEXT:    extui a7, a7, 0, 1
; UNOPT-NEXT:    moveqz a2, a6, a7
; UNOPT-NEXT:    extui a5, a5, 0, 1
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %ashr = ashr i33 %val, %shamt
  ret i33 %ashr
}

define i64 @ashr_i64(i64 %val, i64 %shamt) {
; OPT-LABEL: ashr_i64:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    movi.n a5, 32
; OPT-NEXT:    saltu a7, a4, a5
; OPT-NEXT:    ssr a4
; OPT-NEXT:    sra a5, a3
; OPT-NEXT:    srl a6, a2
; OPT-NEXT:    neg a8, a4
; OPT-NEXT:    ssl a8
; OPT-NEXT:    sll a8, a3
; OPT-NEXT:    or a6, a6, a8
; OPT-NEXT:    srai a8, a3, 31
; OPT-NEXT:    ssr a4
; OPT-NEXT:    sra a3, a3
; OPT-NEXT:    moveqz a6, a3, a7
; OPT-NEXT:    moveqz a6, a2, a4
; OPT-NEXT:    moveqz a5, a8, a7
; OPT-NEXT:    mov.n a2, a6
; OPT-NEXT:    mov.n a3, a5
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: ashr_i64:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    mov.n a8, a3
; UNOPT-NEXT:    movi.n a3, 32
; UNOPT-NEXT:    addi a9, a4, -32
; UNOPT-NEXT:    sub a6, a3, a4
; UNOPT-NEXT:    saltu a5, a4, a3
; UNOPT-NEXT:    movi.n a3, 1
; UNOPT-NEXT:    movi.n a7, 0
; UNOPT-NEXT:    moveqz a7, a3, a4
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    sra a3, a8
; UNOPT-NEXT:    ssr a4
; UNOPT-NEXT:    srl a4, a2
; UNOPT-NEXT:    ssl a6
; UNOPT-NEXT:    sll a6, a8
; UNOPT-NEXT:    or a6, a4, a6
; UNOPT-NEXT:    srai a4, a8, 31
; UNOPT-NEXT:    ssr a9
; UNOPT-NEXT:    sra a8, a8
; UNOPT-NEXT:    extui a9, a5, 0, 1
; UNOPT-NEXT:    moveqz a6, a8, a9
; UNOPT-NEXT:    extui a7, a7, 0, 1
; UNOPT-NEXT:    moveqz a2, a6, a7
; UNOPT-NEXT:    extui a5, a5, 0, 1
; UNOPT-NEXT:    moveqz a3, a4, a5
; UNOPT-NEXT:    ret.n
entry:
  %ashr = ashr i64 %val, %shamt
  ret i64 %ashr
}
