; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s --check-prefix=OPT
; RUN: llc -O0 < %s -mtriple=xtensa | FileCheck %s --check-prefix=UNOPT

define i8 @shl_i8(i8 %val, i8 %shamt) {
; OPT-LABEL: shl_i8:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    ssl a3
; OPT-NEXT:    sll a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: shl_i8:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 8
; UNOPT-NEXT:    ssl a3
; UNOPT-NEXT:    sll a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %shl = shl i8 %val, %shamt
  ret i8 %shl
}

define i16 @shl_i16(i16 %val, i16 %shamt) {
; OPT-LABEL: shl_i16:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    ssl a3
; OPT-NEXT:    sll a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: shl_i16:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 16
; UNOPT-NEXT:    ssl a3
; UNOPT-NEXT:    sll a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %shl = shl i16 %val, %shamt
  ret i16 %shl
}

define i32 @shl_i32(i32 %val, i32 %shamt) {
; OPT-LABEL: shl_i32:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    ssl a3
; OPT-NEXT:    sll a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: shl_i32:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    ssl a3
; UNOPT-NEXT:    sll a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %shl = shl i32 %val, %shamt
  ret i32 %shl
}

define i8 @lshr_i8(i8 %val, i8 %shamt) {
; OPT-LABEL: lshr_i8:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    extui a2, a2, 0, 8
; OPT-NEXT:    ssr a3
; OPT-NEXT:    srl a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: lshr_i8:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 8
; UNOPT-NEXT:    extui a2, a2, 0, 8
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    srl a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %lshr = lshr i8 %val, %shamt
  ret i8 %lshr
}

define i16 @lshr_i16(i16 %val, i16 %shamt) {
; OPT-LABEL: lshr_i16:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    extui a2, a2, 0, 16
; OPT-NEXT:    ssr a3
; OPT-NEXT:    srl a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: lshr_i16:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 16
; UNOPT-NEXT:    extui a2, a2, 0, 16
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    srl a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %lshr = lshr i16 %val, %shamt
  ret i16 %lshr
}

define i32 @lshr_i32(i32 %val, i32 %shamt) {
; OPT-LABEL: lshr_i32:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    ssr a3
; OPT-NEXT:    srl a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: lshr_i32:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    srl a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %lshr = lshr i32 %val, %shamt
  ret i32 %lshr
}

define i8 @ashr_i8(i8 %val, i8 %shamt) {
; OPT-LABEL: ashr_i8:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    sext a2, a2, 7
; OPT-NEXT:    ssr a3
; OPT-NEXT:    sra a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: ashr_i8:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 8
; UNOPT-NEXT:    sext a2, a2, 7
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    sra a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %ashr = ashr i8 %val, %shamt
  ret i8 %ashr
}

define i16 @ashr_i16(i16 %val, i16 %shamt) {
; OPT-LABEL: ashr_i16:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    sext a2, a2, 15
; OPT-NEXT:    ssr a3
; OPT-NEXT:    sra a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: ashr_i16:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    extui a3, a3, 0, 16
; UNOPT-NEXT:    sext a2, a2, 15
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    sra a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %ashr = ashr i16 %val, %shamt
  ret i16 %ashr
}

define i32 @ashr_i32(i32 %val, i32 %shamt) {
; OPT-LABEL: ashr_i32:
; OPT:       # %bb.0: # %entry
; OPT-NEXT:    ssr a3
; OPT-NEXT:    sra a2, a2
; OPT-NEXT:    ret.n
;
; UNOPT-LABEL: ashr_i32:
; UNOPT:       # %bb.1: # %entry
; UNOPT-NEXT:    ssr a3
; UNOPT-NEXT:    sra a2, a2
; UNOPT-NEXT:    ret.n
entry:
  %ashr = ashr i32 %val, %shamt
  ret i32 %ashr
}
