; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=xtensa | FileCheck %s --check-prefix=OPT

define i32 @undef_i32() {
; OPT-LABEL: undef_i32:
; OPT:       # %bb.0:
; OPT-NEXT:    ret.n
  ret i32 undef
}

define i32 @poison_i32() {
; OPT-LABEL: poison_i32:
; OPT:       # %bb.0:
; OPT-NEXT:    ret.n
  ret i32 poison
}
