# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'shift.ll'
  source_filename = "shift.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i8 @shl_i8(i8 %val, i8 %shamt) {
    %shl = shl i8 %val, %shamt
    ret i8 %shl
  }

  define i16 @shl_i16(i16 %val, i16 %shamt) {
    %shl = shl i16 %val, %shamt
    ret i16 %shl
  }

  define i32 @shl_i32(i32 %val, i32 %shamt) {
    %shl = shl i32 %val, %shamt
    ret i32 %shl
  }

  define i33 @shl_i33(i33 %val, i33 %shamt) {
    %shl = shl i33 %val, %shamt
    ret i33 %shl
  }

  define i64 @shl_i64(i64 %val, i64 %shamt) {
    %shl = shl i64 %val, %shamt
    ret i64 %shl
  }

  define i8 @lshr_i8(i8 %val, i8 %shamt) {
    %lshr = lshr i8 %val, %shamt
    ret i8 %lshr
  }

  define i16 @lshr_i16(i16 %val, i16 %shamt) {
    %lshr = lshr i16 %val, %shamt
    ret i16 %lshr
  }

  define i32 @lshr_i32(i32 %val, i32 %shamt) {
    %lshr = lshr i32 %val, %shamt
    ret i32 %lshr
  }

  define i33 @lshr_i33(i33 %val, i33 %shamt) {
    %lshr = lshr i33 %val, %shamt
    ret i33 %lshr
  }

  define i64 @lshr_i64(i64 %val, i64 %shamt) {
    %lshr = lshr i64 %val, %shamt
    ret i64 %lshr
  }

  define i8 @ashr_i8(i8 %val, i8 %shamt) {
    %ashr = ashr i8 %val, %shamt
    ret i8 %ashr
  }

  define i16 @ashr_i16(i16 %val, i16 %shamt) {
    %ashr = ashr i16 %val, %shamt
    ret i16 %ashr
  }

  define i32 @ashr_i32(i32 %val, i32 %shamt) {
    %ashr = ashr i32 %val, %shamt
    ret i32 %ashr
  }

  define i33 @ashr_i33(i33 %val, i33 %shamt) {
    %ashr = ashr i33 %val, %shamt
    ret i33 %ashr
  }

  define i64 @ashr_i64(i64 %val, i64 %shamt) {
    %ashr = ashr i64 %val, %shamt
    ret i64 %ashr
  }

...
---
name:            shl_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gpr(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    G_XTENSA_SSL_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SLL %2(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shl_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:gpr(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    G_XTENSA_SSL_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SLL %2(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shl_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    G_XTENSA_SSL_MASKED %1(s32), implicit-def $sar
    %2:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shl_i33
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gpr, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gpr, preferred-register: '' }
  - { id: 24, class: gpr, preferred-register: '' }
  - { id: 25, class: gpr, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: gpr, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: _, preferred-register: '' }
  - { id: 40, class: _, preferred-register: '' }
  - { id: 41, class: _, preferred-register: '' }
  - { id: 42, class: _, preferred-register: '' }
  - { id: 43, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: shl_i33
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C1]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C2]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL1:%[0-9]+]]:gpr(s32) = SLL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SRL]], [[SLL1]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL2:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SLL]], [[C3]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR]], [[SLL2]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[COPY1]], [[SELECT1]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a2
    %3:gpr(s32) = COPY $a3
    %5:_(s32) = COPY $a4
    %15:_(s32) = G_CONSTANT i32 32
    %20:_(s32) = G_CONSTANT i32 0
    %36:_(s32) = G_ICMP intpred(ult), %5(s32), %15
    %35:_(s32) = G_ICMP intpred(eq), %5(s32), %20
    G_XTENSA_SSL_MASKED %5(s32), implicit-def $sar
    %23:gpr(s32) = SLL %2(s32), implicit $sar
    %40:_(s32) = G_CONSTANT i32 0
    %41:_(s32) = G_SUB %40, %5
    G_XTENSA_SSR_MASKED %41(s32), implicit-def $sar
    %24:gpr(s32) = SRL %2(s32), implicit $sar
    G_XTENSA_SSL_MASKED %5(s32), implicit-def $sar
    %25:gpr(s32) = SLL %3(s32), implicit $sar
    %26:_(s32) = G_OR %24, %25
    %27:_(s32) = G_CONSTANT i32 0
    G_XTENSA_SSL_MASKED %5(s32), implicit-def $sar
    %28:gpr(s32) = SLL %2(s32), implicit $sar
    %29:_(s32) = G_SELECT %36(s32), %23, %27
    %30:_(s32) = G_SELECT %36(s32), %26, %28
    %31:_(s32) = G_SELECT %35(s32), %3, %30
    $a2 = COPY %29(s32)
    $a3 = COPY %31(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            shl_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gpr, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: gpr, preferred-register: '' }
  - { id: 19, class: gpr, preferred-register: '' }
  - { id: 20, class: gpr, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gpr, preferred-register: '' }
  - { id: 24, class: _, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: shl_i64
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C1]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C2]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL1:%[0-9]+]]:gpr(s32) = SLL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SRL]], [[SLL1]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL2:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SLL]], [[C3]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR]], [[SLL2]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[COPY1]], [[SELECT1]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a2
    %3:gpr(s32) = COPY $a3
    %4:_(s32) = COPY $a4
    %10:_(s32) = G_CONSTANT i32 32
    %15:_(s32) = G_CONSTANT i32 0
    %31:_(s32) = G_ICMP intpred(ult), %4(s32), %10
    %30:_(s32) = G_ICMP intpred(eq), %4(s32), %15
    G_XTENSA_SSL_MASKED %4(s32), implicit-def $sar
    %18:gpr(s32) = SLL %2(s32), implicit $sar
    %35:_(s32) = G_CONSTANT i32 0
    %36:_(s32) = G_SUB %35, %4
    G_XTENSA_SSR_MASKED %36(s32), implicit-def $sar
    %19:gpr(s32) = SRL %2(s32), implicit $sar
    G_XTENSA_SSL_MASKED %4(s32), implicit-def $sar
    %20:gpr(s32) = SLL %3(s32), implicit $sar
    %21:_(s32) = G_OR %19, %20
    %22:_(s32) = G_CONSTANT i32 0
    G_XTENSA_SSL_MASKED %4(s32), implicit-def $sar
    %23:gpr(s32) = SLL %2(s32), implicit $sar
    %24:_(s32) = G_SELECT %31(s32), %18, %22
    %25:_(s32) = G_SELECT %31(s32), %21, %23
    %26:_(s32) = G_SELECT %30(s32), %3, %25
    $a2 = COPY %24(s32)
    $a3 = COPY %26(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 255
    ; CHECK-NEXT: [[AND:%[0-9]+]]:gpr(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[AND]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %9:_(s32) = G_CONSTANT i32 255
    %7:gpr(s32) = G_AND %2, %9
    G_XTENSA_SSR_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SRL %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 65535
    ; CHECK-NEXT: [[AND:%[0-9]+]]:gpr(s32) = G_AND [[COPY]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[AND]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %9:_(s32) = G_CONSTANT i32 65535
    %7:gpr(s32) = G_AND %2, %9
    G_XTENSA_SSR_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SRL %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: lshr_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    G_XTENSA_SSR_MASKED %1(s32), implicit-def $sar
    %2:gpr(s32) = SRL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            lshr_i33
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gpr, preferred-register: '' }
  - { id: 24, class: gpr, preferred-register: '' }
  - { id: 25, class: gpr, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: gpr, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: _, preferred-register: '' }
  - { id: 40, class: _, preferred-register: '' }
  - { id: 41, class: _, preferred-register: '' }
  - { id: 42, class: _, preferred-register: '' }
  - { id: 43, class: _, preferred-register: '' }
  - { id: 44, class: _, preferred-register: '' }
  - { id: 45, class: _, preferred-register: '' }
  - { id: 46, class: gpr, preferred-register: '' }
  - { id: 47, class: _, preferred-register: '' }
  - { id: 48, class: _, preferred-register: '' }
  - { id: 49, class: _, preferred-register: '' }
  - { id: 50, class: _, preferred-register: '' }
  - { id: 51, class: _, preferred-register: '' }
  - { id: 52, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: lshr_i33
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[AND:%[0-9]+]]:gpr(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C1]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C2]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[AND]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL1:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C3]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[AND]](s32), implicit $sar
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SRL1]], [[SLL]]
    ; CHECK-NEXT: [[C4:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL2:%[0-9]+]]:gpr(s32) = SRL [[AND]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR]], [[SRL2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[COPY]], [[SELECT]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SRL]], [[C4]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %5:_(s32) = COPY $a4
    %48:_(s32) = G_CONSTANT i32 1
    %46:gpr(s32) = G_AND %3, %48
    %15:_(s32) = G_CONSTANT i32 32
    %20:_(s32) = G_CONSTANT i32 0
    %36:_(s32) = G_ICMP intpred(ult), %5(s32), %15
    %35:_(s32) = G_ICMP intpred(eq), %5(s32), %20
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %23:gpr(s32) = SRL %46(s32), implicit $sar
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %24:gpr(s32) = SRL %2(s32), implicit $sar
    %49:_(s32) = G_CONSTANT i32 0
    %50:_(s32) = G_SUB %49, %5
    G_XTENSA_SSL_MASKED %50(s32), implicit-def $sar
    %25:gpr(s32) = SLL %46(s32), implicit $sar
    %26:_(s32) = G_OR %24, %25
    %27:_(s32) = G_CONSTANT i32 0
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %28:gpr(s32) = SRL %46(s32), implicit $sar
    %29:_(s32) = G_SELECT %36(s32), %26, %28
    %30:_(s32) = G_SELECT %35(s32), %2, %29
    %31:_(s32) = G_SELECT %36(s32), %23, %27
    $a2 = COPY %30(s32)
    $a3 = COPY %31(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            lshr_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gpr, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: gpr, preferred-register: '' }
  - { id: 19, class: gpr, preferred-register: '' }
  - { id: 20, class: gpr, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gpr, preferred-register: '' }
  - { id: 24, class: _, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: lshr_i64
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C1]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL1:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C2]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SRL1]], [[SLL]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL2:%[0-9]+]]:gpr(s32) = SRL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR]], [[SRL2]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[COPY]], [[SELECT]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SRL]], [[C3]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a2
    %3:gpr(s32) = COPY $a3
    %4:_(s32) = COPY $a4
    %10:_(s32) = G_CONSTANT i32 32
    %15:_(s32) = G_CONSTANT i32 0
    %31:_(s32) = G_ICMP intpred(ult), %4(s32), %10
    %30:_(s32) = G_ICMP intpred(eq), %4(s32), %15
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %18:gpr(s32) = SRL %3(s32), implicit $sar
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %19:gpr(s32) = SRL %2(s32), implicit $sar
    %35:_(s32) = G_CONSTANT i32 0
    %36:_(s32) = G_SUB %35, %4
    G_XTENSA_SSL_MASKED %36(s32), implicit-def $sar
    %20:gpr(s32) = SLL %3(s32), implicit $sar
    %21:_(s32) = G_OR %19, %20
    %22:_(s32) = G_CONSTANT i32 0
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %23:gpr(s32) = SRL %3(s32), implicit $sar
    %24:_(s32) = G_SELECT %31(s32), %21, %23
    %25:_(s32) = G_SELECT %30(s32), %2, %24
    %26:_(s32) = G_SELECT %31(s32), %18, %22
    $a2 = COPY %25(s32)
    $a3 = COPY %26(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_i8
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i8
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 24
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:gpr(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr(s32) = SRA [[ASHR]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %11:_(s32) = G_CONSTANT i32 24
    %10:_(s32) = G_SHL %2, %11(s32)
    %7:gpr(s32) = G_ASHR %10, %11(s32)
    G_XTENSA_SSR_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SRA %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i16
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i16
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 16
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:gpr(s32) = G_ASHR [[SHL]], [[C]](s32)
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr(s32) = SRA [[ASHR]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %2:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %11:_(s32) = G_CONSTANT i32 16
    %10:_(s32) = G_SHL %2, %11(s32)
    %7:gpr(s32) = G_ASHR %10, %11(s32)
    G_XTENSA_SSR_MASKED %3(s32), implicit-def $sar
    %8:gpr(s32) = SRA %7(s32), implicit $sar
    $a2 = COPY %8(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i32
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: ashr_i32
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr(s32) = SRA [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRA]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    G_XTENSA_SSR_MASKED %1(s32), implicit-def $sar
    %2:gpr(s32) = SRA %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            ashr_i33
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: gpr, preferred-register: '' }
  - { id: 24, class: gpr, preferred-register: '' }
  - { id: 25, class: gpr, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: gpr, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: _, preferred-register: '' }
  - { id: 40, class: _, preferred-register: '' }
  - { id: 41, class: _, preferred-register: '' }
  - { id: 42, class: _, preferred-register: '' }
  - { id: 43, class: _, preferred-register: '' }
  - { id: 44, class: _, preferred-register: '' }
  - { id: 45, class: _, preferred-register: '' }
  - { id: 46, class: _, preferred-register: '' }
  - { id: 47, class: _, preferred-register: '' }
  - { id: 48, class: _, preferred-register: '' }
  - { id: 49, class: _, preferred-register: '' }
  - { id: 50, class: gpr, preferred-register: '' }
  - { id: 51, class: gpr, preferred-register: '' }
  - { id: 52, class: _, preferred-register: '' }
  - { id: 53, class: _, preferred-register: '' }
  - { id: 54, class: _, preferred-register: '' }
  - { id: 55, class: _, preferred-register: '' }
  - { id: 56, class: _, preferred-register: '' }
  - { id: 57, class: _, preferred-register: '' }
  - { id: 58, class: _, preferred-register: '' }
  - { id: 59, class: _, preferred-register: '' }
  - { id: 60, class: _, preferred-register: '' }
  - { id: 61, class: _, preferred-register: '' }
  - { id: 62, class: _, preferred-register: '' }
  - { id: 63, class: _, preferred-register: '' }
  - { id: 64, class: _, preferred-register: '' }
  - { id: 65, class: _, preferred-register: '' }
  - { id: 66, class: _, preferred-register: '' }
  - { id: 67, class: _, preferred-register: '' }
  - { id: 68, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: ashr_i33
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprb(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprb(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:gprb(s32) = G_SHL [[COPY]], [[C]](s32)
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[SHL1:%[0-9]+]]:gprb(s32) = G_SHL [[COPY1]], [[C1]](s32)
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:gprb(s32) = G_LSHR [[COPY]], [[C2]](s32)
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SHL1]], [[LSHR]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[LSHR1:%[0-9]+]]:gprb(s32) = G_LSHR [[SHL]], [[C3]](s32)
    ; CHECK-NEXT: [[C4:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[SHL2:%[0-9]+]]:gprb(s32) = G_SHL [[OR]], [[C4]](s32)
    ; CHECK-NEXT: [[OR1:%[0-9]+]]:gpr(s32) = G_OR [[LSHR1]], [[SHL2]]
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:gpr(s32) = G_ASHR [[OR]], [[C3]](s32)
    ; CHECK-NEXT: [[C5:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C6:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C5]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C6]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr(s32) = SRA [[ASHR]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[OR1]](s32), implicit $sar
    ; CHECK-NEXT: [[C7:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C7]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[ASHR]](s32), implicit $sar
    ; CHECK-NEXT: [[OR2:%[0-9]+]]:gprb(s32) = G_OR [[SRL]], [[SLL]]
    ; CHECK-NEXT: [[C8:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[ASHR1:%[0-9]+]]:gprb(s32) = G_ASHR [[OR]], [[C8]](s32)
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA1:%[0-9]+]]:gpr(s32) = SRA [[ASHR]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR2]], [[SRA1]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[OR1]], [[SELECT]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SRA]], [[ASHR1]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %5:_(s32) = COPY $a4
    %55:_(s32) = G_CONSTANT i32 31
    %56:_(s32) = G_SHL %2, %55(s32)
    %57:_(s32) = G_CONSTANT i32 31
    %58:_(s32) = G_SHL %3, %57(s32)
    %59:_(s32) = G_CONSTANT i32 1
    %60:_(s32) = G_LSHR %2, %59(s32)
    %61:_(s32) = G_OR %58, %60
    %46:_(s32) = G_CONSTANT i32 31
    %47:_(s32) = G_LSHR %56, %46(s32)
    %48:_(s32) = G_CONSTANT i32 1
    %49:_(s32) = G_SHL %61, %48(s32)
    %50:gpr(s32) = G_OR %47, %49
    %51:gpr(s32) = G_ASHR %61, %46(s32)
    %15:_(s32) = G_CONSTANT i32 32
    %20:_(s32) = G_CONSTANT i32 0
    %37:_(s32) = G_ICMP intpred(ult), %5(s32), %15
    %36:_(s32) = G_ICMP intpred(eq), %5(s32), %20
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %23:gpr(s32) = SRA %51(s32), implicit $sar
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %24:gpr(s32) = SRL %50(s32), implicit $sar
    %65:_(s32) = G_CONSTANT i32 0
    %66:_(s32) = G_SUB %65, %5
    G_XTENSA_SSL_MASKED %66(s32), implicit-def $sar
    %25:gpr(s32) = SLL %51(s32), implicit $sar
    %26:_(s32) = G_OR %24, %25
    %64:_(s32) = G_CONSTANT i32 31
    %28:_(s32) = G_ASHR %61, %64(s32)
    G_XTENSA_SSR_MASKED %5(s32), implicit-def $sar
    %29:gpr(s32) = SRA %51(s32), implicit $sar
    %30:_(s32) = G_SELECT %37(s32), %26, %29
    %31:_(s32) = G_SELECT %36(s32), %50, %30
    %32:_(s32) = G_SELECT %37(s32), %23, %28
    $a2 = COPY %31(s32)
    $a3 = COPY %32(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
---
name:            ashr_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gpr, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: gpr, preferred-register: '' }
  - { id: 19, class: gpr, preferred-register: '' }
  - { id: 20, class: gpr, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
  - { id: 22, class: _, preferred-register: '' }
  - { id: 23, class: _, preferred-register: '' }
  - { id: 24, class: gpr, preferred-register: '' }
  - { id: 25, class: _, preferred-register: '' }
  - { id: 26, class: _, preferred-register: '' }
  - { id: 27, class: _, preferred-register: '' }
  - { id: 28, class: _, preferred-register: '' }
  - { id: 29, class: _, preferred-register: '' }
  - { id: 30, class: _, preferred-register: '' }
  - { id: 31, class: _, preferred-register: '' }
  - { id: 32, class: _, preferred-register: '' }
  - { id: 33, class: _, preferred-register: '' }
  - { id: 34, class: _, preferred-register: '' }
  - { id: 35, class: _, preferred-register: '' }
  - { id: 36, class: _, preferred-register: '' }
  - { id: 37, class: _, preferred-register: '' }
  - { id: 38, class: _, preferred-register: '' }
  - { id: 39, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5

    ; CHECK-LABEL: name: ashr_i64
    ; CHECK: liveins: $a2, $a3, $a4, $a5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprb(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[C1:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[ICMP:%[0-9]+]]:gprb(s32) = G_ICMP intpred(ult), [[COPY2]](s32), [[C]]
    ; CHECK-NEXT: [[ICMP1:%[0-9]+]]:gprb(s32) = G_ICMP intpred(eq), [[COPY2]](s32), [[C1]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA:%[0-9]+]]:gpr(s32) = SRA [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: [[C2:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:gprb(s32) = G_SUB [[C2]], [[COPY2]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gprb(s32) = G_OR [[SRL]], [[SLL]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:gprb(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:gprb(s32) = G_ASHR [[COPY1]], [[C3]](s32)
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY2]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRA1:%[0-9]+]]:gpr(s32) = SRA [[COPY1]](s32), implicit $sar
    ; CHECK-NEXT: [[SELECT:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[OR]], [[SRA1]]
    ; CHECK-NEXT: [[SELECT1:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP1]](s32), [[COPY]], [[SELECT]]
    ; CHECK-NEXT: [[SELECT2:%[0-9]+]]:gprb(s32) = G_SELECT [[ICMP]](s32), [[SRA]], [[ASHR]]
    ; CHECK-NEXT: $a2 = COPY [[SELECT1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[SELECT2]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2, implicit $a3
    %2:gpr(s32) = COPY $a2
    %3:gpr(s32) = COPY $a3
    %4:_(s32) = COPY $a4
    %10:_(s32) = G_CONSTANT i32 32
    %15:_(s32) = G_CONSTANT i32 0
    %32:_(s32) = G_ICMP intpred(ult), %4(s32), %10
    %31:_(s32) = G_ICMP intpred(eq), %4(s32), %15
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %18:gpr(s32) = SRA %3(s32), implicit $sar
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %19:gpr(s32) = SRL %2(s32), implicit $sar
    %36:_(s32) = G_CONSTANT i32 0
    %37:_(s32) = G_SUB %36, %4
    G_XTENSA_SSL_MASKED %37(s32), implicit-def $sar
    %20:gpr(s32) = SLL %3(s32), implicit $sar
    %21:_(s32) = G_OR %19, %20
    %22:_(s32) = G_CONSTANT i32 31
    %23:_(s32) = G_ASHR %3, %22(s32)
    G_XTENSA_SSR_MASKED %4(s32), implicit-def $sar
    %24:gpr(s32) = SRA %3(s32), implicit $sar
    %25:_(s32) = G_SELECT %32(s32), %21, %24
    %26:_(s32) = G_SELECT %31(s32), %2, %25
    %27:_(s32) = G_SELECT %32(s32), %18, %23
    $a2 = COPY %26(s32)
    $a3 = COPY %27(s32)
    RETN implicit $a0, implicit $a2, implicit $a3

...
