# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=prologepilog -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = './llvm/test/CodeGen/Xtensa/GlobalISel/llvm-ir/call_args_fp.ll'
  source_filename = "./llvm/test/CodeGen/Xtensa/GlobalISel/llvm-ir/call_args_fp.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  declare void @reg_args_i32(i32, i32, i32, i32, i32, i32)

  declare void @reg_arg_i1(i1)

  declare void @reg_arg_i8(i8)

  declare void @reg_arg_i16(i16)

  declare void @reg_arg_i64(i64)

  declare void @reg_arg_i64_packed(i32, i32, i64)

  declare void @reg_arg_i64_aligned(i32, i64)

  declare void @mixed_reg_args(i32, i1, i64, i8, i16)

  declare void @stack_arg_i32(i32, i32, i32, i32, i32, i32, i32)

  declare void @stack_arg_i1(i32, i32, i32, i32, i32, i32, i1)

  declare void @stack_arg_i8(i32, i32, i32, i32, i32, i32, i8)

  declare void @stack_arg_i16(i32, i32, i32, i32, i32, i32, i16)

  declare void @stack_arg_i64(i32, i32, i32, i32, i32, i32, i64)

  declare void @stack_arg_i64_reg_unaligned(i32, i32, i32, i32, i32, i64)

  declare void @stack_arg_i64_aligned(i32, i32, i32, i32, i32, i32, i32, i64)

  declare void @mixed_reg_stack_args(i32, i1, i8, i64, i16)

  declare void @mixed_stack_args(i32, i32, i32, i32, i32, i32, i16, i8, i64)

  define void @call_simple_reg_args() #0 {
  entry:
    call void @reg_args_i32(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6)
    call void @reg_arg_i1(i1 true)
    call void @reg_arg_i8(i8 1)
    call void @reg_arg_i16(i16 1)
    ret void
  }

  define void @call_reg_i64() #0 {
  entry:
    call void @reg_arg_i64(i64 1)
    call void @reg_arg_i64_packed(i32 1, i32 2, i64 3)
    call void @reg_arg_i64_aligned(i32 1, i64 2)
    ret void
  }

  define void @call_mixed_reg_args() #0 {
  entry:
    call void @mixed_reg_args(i32 1, i1 true, i64 3, i8 4, i16 5)
    ret void
  }

  define void @call_stack() #0 {
  entry:
    call void @stack_arg_i32(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7)
    call void @stack_arg_i1(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i1 true)
    call void @stack_arg_i8(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i8 7)
    call void @stack_arg_i16(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i16 7)
    ret void
  }

  define void @call_stack_i64() #0 {
  entry:
    call void @stack_arg_i64(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i64 7)
    call void @stack_arg_i64_reg_unaligned(i32 1, i32 2, i32 3, i32 4, i32 5, i64 6)
    call void @stack_arg_i64_aligned(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i64 8)
    ret void
  }

  attributes #0 = { "frame-pointer"="all" }

...
---
name:            call_simple_reg_args
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:       []
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: call_simple_reg_args
    ; CHECK: $a1 = ADDI killed $a1, -16
    ; CHECK-NEXT: S32I killed $a0, $a1, 12 :: (store (s32) into %fixed-stack.0)
    ; CHECK-NEXT: S32I killed $a15, $a1, 8 :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $a15 = MOVN $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: renamable $a3 = MOVI 2
    ; CHECK-NEXT: renamable $a4 = MOVI 3
    ; CHECK-NEXT: renamable $a5 = MOVI 4
    ; CHECK-NEXT: renamable $a6 = MOVI 5
    ; CHECK-NEXT: renamable $a7 = MOVI 6
    ; CHECK-NEXT: CALL0 @reg_args_i32, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: CALL0 @reg_arg_i1, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: CALL0 @reg_arg_i8, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: CALL0 @reg_arg_i16, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ; CHECK-NEXT: $a1 = MOVN killed $a15
    ; CHECK-NEXT: $a15 = L32I $a1, 8 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $a0 = L32I $a1, 12 :: (load (s32) from %fixed-stack.0)
    ; CHECK-NEXT: $a1 = ADDI killed $a1, 16
    ; CHECK-NEXT: RETN implicit $a0
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    renamable $a3 = MOVI 2
    renamable $a4 = MOVI 3
    renamable $a5 = MOVI 4
    renamable $a6 = MOVI 5
    renamable $a7 = MOVI 6
    CALL0 @reg_args_i32, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    CALL0 @reg_arg_i1, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    CALL0 @reg_arg_i8, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    CALL0 @reg_arg_i16, csr_xtensa_call0, implicit-def $a0, implicit killed $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            call_reg_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:       []
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: call_reg_i64
    ; CHECK: $a1 = ADDI killed $a1, -16
    ; CHECK-NEXT: S32I killed $a0, $a1, 12 :: (store (s32) into %fixed-stack.0)
    ; CHECK-NEXT: S32I killed $a15, $a1, 8 :: (store (s32) into %stack.1)
    ; CHECK-NEXT: $a15 = MOVN $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: renamable $a3 = MOVI 0
    ; CHECK-NEXT: CALL0 @reg_arg_i64, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: S32I $a2, $a15, 4 :: (store (s32) into %stack.0)
    ; CHECK-NEXT: renamable $a3 = MOVI 2
    ; CHECK-NEXT: renamable $a4 = MOVI 3
    ; CHECK-NEXT: renamable $a5 = MOVI 0
    ; CHECK-NEXT: CALL0 @reg_arg_i64_packed, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5
    ; CHECK-NEXT: $a2 = L32I $a15, 4 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: renamable $a4 = MOVI 2
    ; CHECK-NEXT: renamable $a5 = MOVI 0
    ; CHECK-NEXT: CALL0 @reg_arg_i64_aligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a4, implicit killed $a5
    ; CHECK-NEXT: $a1 = MOVN killed $a15
    ; CHECK-NEXT: $a15 = L32I $a1, 8 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $a0 = L32I $a1, 12 :: (load (s32) from %fixed-stack.0)
    ; CHECK-NEXT: $a1 = ADDI killed $a1, 16
    ; CHECK-NEXT: RETN implicit $a0
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    renamable $a3 = MOVI 0
    CALL0 @reg_arg_i64, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    S32I $a2, %stack.0, 0 :: (store (s32) into %stack.0)
    renamable $a3 = MOVI 2
    renamable $a4 = MOVI 3
    renamable $a5 = MOVI 0
    CALL0 @reg_arg_i64_packed, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5
    $a2 = L32I %stack.0, 0 :: (load (s32) from %stack.0)
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a4 = MOVI 2
    renamable $a5 = MOVI 0
    CALL0 @reg_arg_i64_aligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a4, implicit killed $a5
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            call_mixed_reg_args
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:       []
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: call_mixed_reg_args
    ; CHECK: $a1 = ADDI killed $a1, -16
    ; CHECK-NEXT: S32I killed $a0, $a1, 12 :: (store (s32) into %fixed-stack.0)
    ; CHECK-NEXT: S32I killed $a15, $a1, 8 :: (store (s32) into %stack.0)
    ; CHECK-NEXT: $a15 = MOVN $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: renamable $a3 = MOVI 1
    ; CHECK-NEXT: renamable $a4 = MOVI 3
    ; CHECK-NEXT: renamable $a5 = MOVI 0
    ; CHECK-NEXT: renamable $a6 = MOVI 4
    ; CHECK-NEXT: renamable $a7 = MOVI 5
    ; CHECK-NEXT: CALL0 @mixed_reg_args, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a1 = MOVN killed $a15
    ; CHECK-NEXT: $a15 = L32I $a1, 8 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: $a0 = L32I $a1, 12 :: (load (s32) from %fixed-stack.0)
    ; CHECK-NEXT: $a1 = ADDI killed $a1, 16
    ; CHECK-NEXT: RETN implicit $a0
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    renamable $a2 = MOVI 1
    renamable $a3 = MOVI 1
    renamable $a4 = MOVI 3
    renamable $a5 = MOVI 0
    renamable $a6 = MOVI 4
    renamable $a7 = MOVI 5
    CALL0 @mixed_reg_args, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            call_stack
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:       []
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 4, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 5, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: call_stack
    ; CHECK: $a1 = ADDI killed $a1, -48
    ; CHECK-NEXT: S32I killed $a0, $a1, 44 :: (store (s32) into %fixed-stack.0)
    ; CHECK-NEXT: S32I killed $a15, $a1, 40 :: (store (s32) into %stack.6)
    ; CHECK-NEXT: $a15 = MOVN $a1
    ; CHECK-NEXT: renamable $a3 = COPY $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 7
    ; CHECK-NEXT: S32I killed renamable $a2, killed renamable $a3, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: S32I $a2, $a15, 16 :: (store (s32) into %stack.5)
    ; CHECK-NEXT: renamable $a3 = MOVI 2
    ; CHECK-NEXT: S32I $a3, $a15, 20 :: (store (s32) into %stack.4)
    ; CHECK-NEXT: renamable $a4 = MOVI 3
    ; CHECK-NEXT: S32I $a4, $a15, 24 :: (store (s32) into %stack.3)
    ; CHECK-NEXT: renamable $a5 = MOVI 4
    ; CHECK-NEXT: S32I $a5, $a15, 28 :: (store (s32) into %stack.2)
    ; CHECK-NEXT: renamable $a6 = MOVI 5
    ; CHECK-NEXT: S32I $a6, $a15, 32 :: (store (s32) into %stack.1)
    ; CHECK-NEXT: renamable $a7 = MOVI 6
    ; CHECK-NEXT: S32I $a7, $a15, 36 :: (store (s32) into %stack.0)
    ; CHECK-NEXT: CALL0 @stack_arg_i32, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a2 = L32I $a15, 16 :: (load (s32) from %stack.5)
    ; CHECK-NEXT: $a3 = L32I $a15, 20 :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $a4 = L32I $a15, 24 :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $a5 = L32I $a15, 28 :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $a6 = L32I $a15, 32 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $a7 = L32I $a15, 36 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 1
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: CALL0 @stack_arg_i1, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a2 = L32I $a15, 16 :: (load (s32) from %stack.5)
    ; CHECK-NEXT: $a3 = L32I $a15, 20 :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $a4 = L32I $a15, 24 :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $a5 = L32I $a15, 28 :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $a6 = L32I $a15, 32 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $a7 = L32I $a15, 36 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 7
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: CALL0 @stack_arg_i8, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a2 = L32I $a15, 16 :: (load (s32) from %stack.5)
    ; CHECK-NEXT: $a3 = L32I $a15, 20 :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $a4 = L32I $a15, 24 :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $a5 = L32I $a15, 28 :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $a6 = L32I $a15, 32 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $a7 = L32I $a15, 36 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 7
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: CALL0 @stack_arg_i16, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a1 = MOVN killed $a15
    ; CHECK-NEXT: $a15 = L32I $a1, 40 :: (load (s32) from %stack.6)
    ; CHECK-NEXT: $a0 = L32I $a1, 44 :: (load (s32) from %fixed-stack.0)
    ; CHECK-NEXT: $a1 = ADDI killed $a1, 48
    ; CHECK-NEXT: RETN implicit $a0
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    renamable $a3 = COPY $a1
    renamable $a2 = MOVI 7
    S32I killed renamable $a2, killed renamable $a3, 0 :: (store (s32) into stack)
    renamable $a2 = MOVI 1
    S32I $a2, %stack.5, 0 :: (store (s32) into %stack.5)
    renamable $a3 = MOVI 2
    S32I $a3, %stack.4, 0 :: (store (s32) into %stack.4)
    renamable $a4 = MOVI 3
    S32I $a4, %stack.3, 0 :: (store (s32) into %stack.3)
    renamable $a5 = MOVI 4
    S32I $a5, %stack.2, 0 :: (store (s32) into %stack.2)
    renamable $a6 = MOVI 5
    S32I $a6, %stack.1, 0 :: (store (s32) into %stack.1)
    renamable $a7 = MOVI 6
    S32I $a7, %stack.0, 0 :: (store (s32) into %stack.0)
    CALL0 @stack_arg_i32, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    $a2 = L32I %stack.5, 0 :: (load (s32) from %stack.5)
    $a3 = L32I %stack.4, 0 :: (load (s32) from %stack.4)
    $a4 = L32I %stack.3, 0 :: (load (s32) from %stack.3)
    $a5 = L32I %stack.2, 0 :: (load (s32) from %stack.2)
    $a6 = L32I %stack.1, 0 :: (load (s32) from %stack.1)
    $a7 = L32I %stack.0, 0 :: (load (s32) from %stack.0)
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 1
    S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    CALL0 @stack_arg_i1, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    $a2 = L32I %stack.5, 0 :: (load (s32) from %stack.5)
    $a3 = L32I %stack.4, 0 :: (load (s32) from %stack.4)
    $a4 = L32I %stack.3, 0 :: (load (s32) from %stack.3)
    $a5 = L32I %stack.2, 0 :: (load (s32) from %stack.2)
    $a6 = L32I %stack.1, 0 :: (load (s32) from %stack.1)
    $a7 = L32I %stack.0, 0 :: (load (s32) from %stack.0)
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 7
    S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    CALL0 @stack_arg_i8, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    $a2 = L32I %stack.5, 0 :: (load (s32) from %stack.5)
    $a3 = L32I %stack.4, 0 :: (load (s32) from %stack.4)
    $a4 = L32I %stack.3, 0 :: (load (s32) from %stack.3)
    $a5 = L32I %stack.2, 0 :: (load (s32) from %stack.2)
    $a6 = L32I %stack.1, 0 :: (load (s32) from %stack.1)
    $a7 = L32I %stack.0, 0 :: (load (s32) from %stack.0)
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 7
    S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    CALL0 @stack_arg_i16, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            call_stack_i64
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: true
selected:        true
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:       []
liveins:         []
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    8
  adjustsStack:    false
  hasCalls:        true
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 3, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 4, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 5, name: '', type: spill-slot, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1.entry:
    ; CHECK-LABEL: name: call_stack_i64
    ; CHECK: $a1 = ADDI killed $a1, -48
    ; CHECK-NEXT: S32I killed $a0, $a1, 44 :: (store (s32) into %fixed-stack.0)
    ; CHECK-NEXT: S32I killed $a15, $a1, 40 :: (store (s32) into %stack.6)
    ; CHECK-NEXT: $a15 = MOVN $a1
    ; CHECK-NEXT: renamable $a3 = COPY $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 7
    ; CHECK-NEXT: S32I killed renamable $a2, killed renamable $a3, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: renamable $a3 = COPY $a1
    ; CHECK-NEXT: renamable $a2 = MOVI 0
    ; CHECK-NEXT: S32I killed renamable $a2, killed renamable $a3, 4 :: (store (s32) into stack + 4)
    ; CHECK-NEXT: renamable $a2 = MOVI 1
    ; CHECK-NEXT: S32I $a2, $a15, 16 :: (store (s32) into %stack.5)
    ; CHECK-NEXT: renamable $a3 = MOVI 2
    ; CHECK-NEXT: S32I $a3, $a15, 20 :: (store (s32) into %stack.4)
    ; CHECK-NEXT: renamable $a4 = MOVI 3
    ; CHECK-NEXT: S32I $a4, $a15, 24 :: (store (s32) into %stack.3)
    ; CHECK-NEXT: renamable $a5 = MOVI 4
    ; CHECK-NEXT: S32I $a5, $a15, 28 :: (store (s32) into %stack.2)
    ; CHECK-NEXT: renamable $a6 = MOVI 5
    ; CHECK-NEXT: S32I $a6, $a15, 32 :: (store (s32) into %stack.1)
    ; CHECK-NEXT: renamable $a7 = MOVI 6
    ; CHECK-NEXT: S32I $a7, $a15, 36 :: (store (s32) into %stack.0)
    ; CHECK-NEXT: CALL0 @stack_arg_i64, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a2 = L32I $a15, 16 :: (load (s32) from %stack.5)
    ; CHECK-NEXT: $a3 = L32I $a15, 20 :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $a4 = L32I $a15, 24 :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $a5 = L32I $a15, 28 :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $a6 = L32I $a15, 32 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: renamable $a8 = COPY $a1
    ; CHECK-NEXT: renamable $a7 = MOVI 6
    ; CHECK-NEXT: S32I killed renamable $a7, killed renamable $a8, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: renamable $a8 = COPY $a1
    ; CHECK-NEXT: renamable $a7 = MOVI 0
    ; CHECK-NEXT: S32I killed renamable $a7, killed renamable $a8, 4 :: (store (s32) into stack + 4)
    ; CHECK-NEXT: CALL0 @stack_arg_i64_reg_unaligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6
    ; CHECK-NEXT: $a2 = L32I $a15, 16 :: (load (s32) from %stack.5)
    ; CHECK-NEXT: $a3 = L32I $a15, 20 :: (load (s32) from %stack.4)
    ; CHECK-NEXT: $a4 = L32I $a15, 24 :: (load (s32) from %stack.3)
    ; CHECK-NEXT: $a5 = L32I $a15, 28 :: (load (s32) from %stack.2)
    ; CHECK-NEXT: $a6 = L32I $a15, 32 :: (load (s32) from %stack.1)
    ; CHECK-NEXT: $a7 = L32I $a15, 36 :: (load (s32) from %stack.0)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 7
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 8
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 8 :: (store (s32) into stack + 8)
    ; CHECK-NEXT: renamable $a9 = COPY $a1
    ; CHECK-NEXT: renamable $a8 = MOVI 0
    ; CHECK-NEXT: S32I killed renamable $a8, killed renamable $a9, 12 :: (store (s32) into stack + 12)
    ; CHECK-NEXT: CALL0 @stack_arg_i64_aligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ; CHECK-NEXT: $a1 = MOVN killed $a15
    ; CHECK-NEXT: $a15 = L32I $a1, 40 :: (load (s32) from %stack.6)
    ; CHECK-NEXT: $a0 = L32I $a1, 44 :: (load (s32) from %fixed-stack.0)
    ; CHECK-NEXT: $a1 = ADDI killed $a1, 48
    ; CHECK-NEXT: RETN implicit $a0
    ADJCALLSTACKDOWN 8, 0, implicit-def $a1, implicit $a1
    renamable $a3 = COPY $a1
    renamable $a2 = MOVI 7
    S32I killed renamable $a2, killed renamable $a3, 0 :: (store (s32) into stack)
    renamable $a3 = COPY $a1
    renamable $a2 = MOVI 0
    S32I killed renamable $a2, killed renamable $a3, 4 :: (store (s32) into stack + 4)
    renamable $a2 = MOVI 1
    S32I $a2, %stack.5, 0 :: (store (s32) into %stack.5)
    renamable $a3 = MOVI 2
    S32I $a3, %stack.4, 0 :: (store (s32) into %stack.4)
    renamable $a4 = MOVI 3
    S32I $a4, %stack.3, 0 :: (store (s32) into %stack.3)
    renamable $a5 = MOVI 4
    S32I $a5, %stack.2, 0 :: (store (s32) into %stack.2)
    renamable $a6 = MOVI 5
    S32I $a6, %stack.1, 0 :: (store (s32) into %stack.1)
    renamable $a7 = MOVI 6
    S32I $a7, %stack.0, 0 :: (store (s32) into %stack.0)
    CALL0 @stack_arg_i64, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    $a2 = L32I %stack.5, 0 :: (load (s32) from %stack.5)
    $a3 = L32I %stack.4, 0 :: (load (s32) from %stack.4)
    $a4 = L32I %stack.3, 0 :: (load (s32) from %stack.3)
    $a5 = L32I %stack.2, 0 :: (load (s32) from %stack.2)
    $a6 = L32I %stack.1, 0 :: (load (s32) from %stack.1)
    ADJCALLSTACKUP 8, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 8, 0, implicit-def $a1, implicit $a1
    renamable $a8 = COPY $a1
    renamable $a7 = MOVI 6
    S32I killed renamable $a7, killed renamable $a8, 0 :: (store (s32) into stack)
    renamable $a8 = COPY $a1
    renamable $a7 = MOVI 0
    S32I killed renamable $a7, killed renamable $a8, 4 :: (store (s32) into stack + 4)
    CALL0 @stack_arg_i64_reg_unaligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6
    $a2 = L32I %stack.5, 0 :: (load (s32) from %stack.5)
    $a3 = L32I %stack.4, 0 :: (load (s32) from %stack.4)
    $a4 = L32I %stack.3, 0 :: (load (s32) from %stack.3)
    $a5 = L32I %stack.2, 0 :: (load (s32) from %stack.2)
    $a6 = L32I %stack.1, 0 :: (load (s32) from %stack.1)
    $a7 = L32I %stack.0, 0 :: (load (s32) from %stack.0)
    ADJCALLSTACKUP 8, 0, implicit-def $a1, implicit $a1
    ADJCALLSTACKDOWN 16, 0, implicit-def $a1, implicit $a1
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 7
    S32I killed renamable $a8, killed renamable $a9, 0 :: (store (s32) into stack)
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 8
    S32I killed renamable $a8, killed renamable $a9, 8 :: (store (s32) into stack + 8)
    renamable $a9 = COPY $a1
    renamable $a8 = MOVI 0
    S32I killed renamable $a8, killed renamable $a9, 12 :: (store (s32) into stack + 12)
    CALL0 @stack_arg_i64_aligned, csr_xtensa_call0, implicit-def $a0, implicit killed $a2, implicit killed $a3, implicit killed $a4, implicit killed $a5, implicit killed $a6, implicit killed $a7
    ADJCALLSTACKUP 16, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
