; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -O0 -mtriple=xtensa -stop-after=irtranslator -verify-machineinstrs %s -o - | FileCheck %s

@global = global i64 0, align 8

define void @f1(i64 %a1) {
  ; CHECK-LABEL: name: f1
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a2, $a3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @global
  ; CHECK-NEXT:   G_STORE [[MV]](s64), [[GV]](p0) :: (store (s64) into @global)
  ; CHECK-NEXT:   RETN implicit $a0
  store i64 %a1, ptr @global
  ret void
}

define void @f2(i32 %a1, i32 %a2, i32 %a3, i32 %a4, i32 %a5, i64 %a6) {
  ; CHECK-LABEL: name: f2
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a2, $a3, $a4, $a5, $a6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a2
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $a4
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $a5
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $a6
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s32) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
  ; CHECK-NEXT:   [[GV:%[0-9]+]]:_(p0) = G_GLOBAL_VALUE @global
  ; CHECK-NEXT:   G_STORE [[MV]](s64), [[GV]](p0) :: (store (s64) into @global)
  ; CHECK-NEXT:   RETN implicit $a0
  store i64 %a6, ptr @global
  ret void
}
