; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -O0 -mtriple=xtensa -stop-after=irtranslator -verify-machineinstrs %s -o - | FileCheck %s

define void @ret_void() {
  ; CHECK-LABEL: name: ret_void
  ; CHECK: bb.1.entry:
  ; CHECK-NEXT:   RETN implicit $a0
entry:
  ret void
}
