# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=legalizer -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'alloca_dyn.ll'
  source_filename = "alloca_dyn.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  declare void @f(ptr)

  declare void @f2(i32, i32, i32, i32, i32, i32, ptr)

  define void @alloca_variable(i32 %size, i8 %x) {
    %p = alloca i8, i32 %size, align 1
    store i8 %x, ptr %p, align 1
    ret void
  }

  define void @alloca_variable_int(i32 %size, i32 %x) {
    %p = alloca i32, i32 %size, align 4
    store i32 %x, ptr %p, align 4
    ret void
  }

  define void @alloca_variable_call(i32 %size) {
    %p = alloca i8, i32 %size, align 1
    call void @f(ptr %p)
    ret void
  }

  define void @alloca_variable_call_stack(i32 %size) {
    %p = alloca i8, i32 %size, align 1
    call void @f2(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, ptr %p)
    ret void
  }

  define void @alloca_overaligned(i8 %x) {
    %p = alloca i8, i32 32, align 32
    store i8 %x, ptr %p, align 1
    ret void
  }

  define void @alloca_overaligned_call(i8 %x) {
    %p = alloca i8, i32 32, align 32
    call void @f(ptr %p)
    ret void
  }

  define void @alloca_overaligned_call_stack(i8 %x) {
    %p = alloca i8, i32 32, align 32
    call void @f2(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, ptr %p)
    ret void
  }

  define void @alloca_variable_overaligned(i32 %size, i8 %x) {
    %p = alloca i8, i32 %size, align 32
    store i8 %x, ptr %p, align 1
    ret void
  }

  define void @alloca_variable_overaligned_call(i32 %size) {
    %p = alloca i8, i32 %size, align 32
    call void @f(ptr %p)
    ret void
  }

  define void @alloca_variable_overaligned_call_stack(i32 %size) {
    %p = alloca i8, i32 %size, align 32
    call void @f2(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, ptr %p)
    ret void
  }

  define void @alloca_variable_and_overaligned(i32 %size, i8 %x1, i8 %x2) {
    %p1 = alloca i8, i32 %size, align 1
    %p2 = alloca i8, i32 32, align 32
    store i8 %x1, ptr %p1, align 1
    store i8 %x2, ptr %p2, align 1
    ret void
  }

  define void @alloca_variable_and_overaligned_call(i32 %size, i8 %x1, i8 %x2) {
    %p1 = alloca i8, i32 %size, align 1
    %p2 = alloca i8, i32 32, align 32
    store i8 %x1, ptr %p1, align 1
    store i8 %x2, ptr %p2, align 1
    call void @f(ptr %p1)
    ret void
  }

  define void @alloca_variable_and_overaligned_call_stack(i32 %size, i8 %x1, i8 %x2) {
    %p1 = alloca i8, i32 %size, align 1
    %p2 = alloca i8, i32 32, align 32
    store i8 %x1, ptr %p1, align 1
    store i8 %x2, ptr %p2, align 1
    call void @f2(i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, ptr %p1)
    ret void
  }

  define void @alloca_variable_and_overaligned_call_stack_formal_stack_arg(i32 %size, i8 %x1, i8 %x2, i32 %a4, i32 %a5, i32 %a6, i32 %a7) {
    %p1 = alloca i8, i32 %size, align 1
    %p2 = alloca i8, i32 32, align 32
    store i8 %x1, ptr %p1, align 1
    store i8 %x2, ptr %p2, align 1
    call void @f2(i32 %a7, i32 0, i32 0, i32 0, i32 0, i32 0, ptr %p1)
    ret void
  }

...
---
name:            alloca_variable
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: alloca_variable
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY2]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY3]](p0) :: (store (s8) into %ir.p)
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %2(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_MUL %0, %4
    %5:_(s32) = G_CONSTANT i32 15
    %6:_(s32) = nuw G_ADD %3, %5
    %7:_(s32) = G_CONSTANT i32 -16
    %8:_(s32) = G_AND %6, %7
    %9:_(p0) = G_DYN_STACKALLOC %8(s32), 1
    G_STORE %1(s8), %9(p0) :: (store (s8) into %ir.p)
    RETN implicit $a0

...
---
name:            alloca_variable_int
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: alloca_variable_int
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY2]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY3]](p0) :: (store (s32) into %ir.p)
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %3:_(s32) = G_CONSTANT i32 4
    %2:_(s32) = G_MUL %0, %3
    %4:_(s32) = G_CONSTANT i32 15
    %5:_(s32) = nuw G_ADD %2, %4
    %6:_(s32) = G_CONSTANT i32 -16
    %7:_(s32) = G_AND %5, %6
    %8:_(p0) = G_DYN_STACKALLOC %7(s32), 1
    G_STORE %1(s32), %8(p0) :: (store (s32) into %ir.p)
    RETN implicit $a0

...
---
name:            alloca_variable_call
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_variable_call
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY1]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: $a2 = COPY [[COPY2]](p0)
    ; CHECK-NEXT: CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = G_CONSTANT i32 1
    %1:_(s32) = G_MUL %0, %2
    %3:_(s32) = G_CONSTANT i32 15
    %4:_(s32) = nuw G_ADD %1, %3
    %5:_(s32) = G_CONSTANT i32 -16
    %6:_(s32) = G_AND %4, %5
    %7:_(p0) = G_DYN_STACKALLOC %6(s32), 1
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    $a2 = COPY %7(p0)
    CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_call_stack
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    4
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_variable_call_stack
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C3]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY1]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY3]], [[C4]](s32)
    ; CHECK-NEXT: G_STORE [[COPY2]](p0), [[PTR_ADD]](p0) :: (store (p0) into stack)
    ; CHECK-NEXT: $a2 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a4 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a5 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a6 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a7 = COPY [[C1]](s32)
    ; CHECK-NEXT: CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ; CHECK-NEXT: ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = G_CONSTANT i32 1
    %8:_(s32) = G_CONSTANT i32 0
    %1:_(s32) = G_MUL %0, %2
    %3:_(s32) = G_CONSTANT i32 15
    %4:_(s32) = nuw G_ADD %1, %3
    %5:_(s32) = G_CONSTANT i32 -16
    %6:_(s32) = G_AND %4, %5
    %7:_(p0) = G_DYN_STACKALLOC %6(s32), 1
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    %9:_(p0) = COPY $a1
    %10:_(s32) = G_CONSTANT i32 0
    %11:_(p0) = G_PTR_ADD %9, %10(s32)
    G_STORE %7(p0), %11(p0) :: (store (p0) into stack)
    $a2 = COPY %8(s32)
    $a3 = COPY %8(s32)
    $a4 = COPY %8(s32)
    $a5 = COPY %8(s32)
    $a6 = COPY %8(s32)
    $a7 = COPY %8(s32)
    CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_overaligned
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_overaligned
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.p
    ; CHECK-NEXT: G_STORE [[COPY]](s32), [[FRAME_INDEX]](p0) :: (store (s8) into %ir.p)
    ; CHECK-NEXT: RETN implicit $a0
    %1:_(s32) = COPY $a2
    %0:_(s8) = G_TRUNC %1(s32)
    %2:_(p0) = G_FRAME_INDEX %stack.0.p
    G_STORE %0(s8), %2(p0) :: (store (s8) into %ir.p)
    RETN implicit $a0

...
---
name:            alloca_overaligned_call
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_overaligned_call
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.p
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: $a2 = COPY [[FRAME_INDEX]](p0)
    ; CHECK-NEXT: CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %2:_(p0) = G_FRAME_INDEX %stack.0.p
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    $a2 = COPY %2(p0)
    CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_overaligned_call_stack
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_overaligned_call_stack
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.0.p
    ; CHECK-NEXT: ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY]], [[C1]](s32)
    ; CHECK-NEXT: G_STORE [[FRAME_INDEX]](p0), [[PTR_ADD]](p0) :: (store (p0) into stack)
    ; CHECK-NEXT: $a2 = COPY [[C]](s32)
    ; CHECK-NEXT: $a3 = COPY [[C]](s32)
    ; CHECK-NEXT: $a4 = COPY [[C]](s32)
    ; CHECK-NEXT: $a5 = COPY [[C]](s32)
    ; CHECK-NEXT: $a6 = COPY [[C]](s32)
    ; CHECK-NEXT: $a7 = COPY [[C]](s32)
    ; CHECK-NEXT: CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ; CHECK-NEXT: ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %3:_(s32) = G_CONSTANT i32 0
    %2:_(p0) = G_FRAME_INDEX %stack.0.p
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    %4:_(p0) = COPY $a1
    %5:_(s32) = G_CONSTANT i32 0
    %6:_(p0) = G_PTR_ADD %4, %5(s32)
    G_STORE %2(p0), %6(p0) :: (store (p0) into stack)
    $a2 = COPY %3(s32)
    $a3 = COPY %3(s32)
    $a4 = COPY %3(s32)
    $a5 = COPY %3(s32)
    $a6 = COPY %3(s32)
    $a7 = COPY %3(s32)
    CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_overaligned
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 32, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: alloca_variable_overaligned
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY2]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -32
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[SUB]], [[C3]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[AND1]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY3]](p0) :: (store (s8) into %ir.p)
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %2(s32)
    %4:_(s32) = G_CONSTANT i32 1
    %3:_(s32) = G_MUL %0, %4
    %5:_(s32) = G_CONSTANT i32 15
    %6:_(s32) = nuw G_ADD %3, %5
    %7:_(s32) = G_CONSTANT i32 -16
    %8:_(s32) = G_AND %6, %7
    %9:_(p0) = G_DYN_STACKALLOC %8(s32), 32
    G_STORE %1(s8), %9(p0) :: (store (s8) into %ir.p)
    RETN implicit $a0

...
---
name:            alloca_variable_overaligned_call
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 32, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_variable_overaligned_call
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY1]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -32
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[SUB]], [[C3]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[AND1]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: $a2 = COPY [[COPY2]](p0)
    ; CHECK-NEXT: CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = G_CONSTANT i32 1
    %1:_(s32) = G_MUL %0, %2
    %3:_(s32) = G_CONSTANT i32 15
    %4:_(s32) = nuw G_ADD %1, %3
    %5:_(s32) = G_CONSTANT i32 -16
    %6:_(s32) = G_AND %4, %5
    %7:_(p0) = G_DYN_STACKALLOC %6(s32), 32
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    $a2 = COPY %7(p0)
    CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_overaligned_call_stack
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p, type: variable-sized, offset: 0, alignment: 32, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2

    ; CHECK-LABEL: name: alloca_variable_overaligned_call_stack
    ; CHECK: liveins: $a2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C3]]
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY1]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 -32
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s32) = G_AND [[SUB]], [[C4]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[AND1]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY3]], [[C5]](s32)
    ; CHECK-NEXT: G_STORE [[COPY2]](p0), [[PTR_ADD]](p0) :: (store (p0) into stack)
    ; CHECK-NEXT: $a2 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a4 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a5 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a6 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a7 = COPY [[C1]](s32)
    ; CHECK-NEXT: CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ; CHECK-NEXT: ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %2:_(s32) = G_CONSTANT i32 1
    %8:_(s32) = G_CONSTANT i32 0
    %1:_(s32) = G_MUL %0, %2
    %3:_(s32) = G_CONSTANT i32 15
    %4:_(s32) = nuw G_ADD %1, %3
    %5:_(s32) = G_CONSTANT i32 -16
    %6:_(s32) = G_AND %4, %5
    %7:_(p0) = G_DYN_STACKALLOC %6(s32), 32
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    %9:_(p0) = COPY $a1
    %10:_(s32) = G_CONSTANT i32 0
    %11:_(p0) = G_PTR_ADD %9, %10(s32)
    G_STORE %7(p0), %11(p0) :: (store (p0) into stack)
    $a2 = COPY %8(s32)
    $a3 = COPY %8(s32)
    $a4 = COPY %8(s32)
    $a5 = COPY %8(s32)
    $a6 = COPY %8(s32)
    $a7 = COPY %8(s32)
    CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_and_overaligned
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p1, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: p2, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4

    ; CHECK-LABEL: name: alloca_variable_and_overaligned
    ; CHECK: liveins: $a2, $a3, $a4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY3]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p2
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY4]](p0) :: (store (s8) into %ir.p1)
    ; CHECK-NEXT: G_STORE [[COPY2]](s32), [[FRAME_INDEX]](p0) :: (store (s8) into %ir.p2)
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = COPY $a4
    %2:_(s8) = G_TRUNC %4(s32)
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_MUL %0, %6
    %7:_(s32) = G_CONSTANT i32 15
    %8:_(s32) = nuw G_ADD %5, %7
    %9:_(s32) = G_CONSTANT i32 -16
    %10:_(s32) = G_AND %8, %9
    %11:_(p0) = G_DYN_STACKALLOC %10(s32), 1
    %12:_(p0) = G_FRAME_INDEX %stack.1.p2
    G_STORE %1(s8), %11(p0) :: (store (s8) into %ir.p1)
    G_STORE %2(s8), %12(p0) :: (store (s8) into %ir.p2)
    RETN implicit $a0

...
---
name:            alloca_variable_and_overaligned_call
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p1, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: p2, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4

    ; CHECK-LABEL: name: alloca_variable_and_overaligned_call
    ; CHECK: liveins: $a2, $a3, $a4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C1]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C2]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY3]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p2
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY4]](p0) :: (store (s8) into %ir.p1)
    ; CHECK-NEXT: G_STORE [[COPY2]](s32), [[FRAME_INDEX]](p0) :: (store (s8) into %ir.p2)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: $a2 = COPY [[COPY4]](p0)
    ; CHECK-NEXT: CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ; CHECK-NEXT: ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = COPY $a4
    %2:_(s8) = G_TRUNC %4(s32)
    %6:_(s32) = G_CONSTANT i32 1
    %5:_(s32) = G_MUL %0, %6
    %7:_(s32) = G_CONSTANT i32 15
    %8:_(s32) = nuw G_ADD %5, %7
    %9:_(s32) = G_CONSTANT i32 -16
    %10:_(s32) = G_AND %8, %9
    %11:_(p0) = G_DYN_STACKALLOC %10(s32), 1
    %12:_(p0) = G_FRAME_INDEX %stack.1.p2
    G_STORE %1(s8), %11(p0) :: (store (s8) into %ir.p1)
    G_STORE %2(s8), %12(p0) :: (store (s8) into %ir.p2)
    ADJCALLSTACKDOWN 0, 0, implicit-def $a1, implicit $a1
    $a2 = COPY %11(p0)
    CALL0 @f, csr_xtensa_call0, implicit-def $a0, implicit $a2
    ADJCALLSTACKUP 0, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_and_overaligned_call_stack
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:
  - { id: 0, name: p1, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: p2, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4

    ; CHECK-LABEL: name: alloca_variable_and_overaligned_call_stack
    ; CHECK: liveins: $a2, $a3, $a4
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $a4
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C3]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY3]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p2
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY4]](p0) :: (store (s8) into %ir.p1)
    ; CHECK-NEXT: G_STORE [[COPY2]](s32), [[FRAME_INDEX]](p0) :: (store (s8) into %ir.p2)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY5]], [[C4]](s32)
    ; CHECK-NEXT: G_STORE [[COPY4]](p0), [[PTR_ADD]](p0) :: (store (p0) into stack)
    ; CHECK-NEXT: $a2 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a3 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a4 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a5 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a6 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a7 = COPY [[C1]](s32)
    ; CHECK-NEXT: CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ; CHECK-NEXT: ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %3:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %3(s32)
    %4:_(s32) = COPY $a4
    %2:_(s8) = G_TRUNC %4(s32)
    %6:_(s32) = G_CONSTANT i32 1
    %13:_(s32) = G_CONSTANT i32 0
    %5:_(s32) = G_MUL %0, %6
    %7:_(s32) = G_CONSTANT i32 15
    %8:_(s32) = nuw G_ADD %5, %7
    %9:_(s32) = G_CONSTANT i32 -16
    %10:_(s32) = G_AND %8, %9
    %11:_(p0) = G_DYN_STACKALLOC %10(s32), 1
    %12:_(p0) = G_FRAME_INDEX %stack.1.p2
    G_STORE %1(s8), %11(p0) :: (store (s8) into %ir.p1)
    G_STORE %2(s8), %12(p0) :: (store (s8) into %ir.p2)
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    %14:_(p0) = COPY $a1
    %15:_(s32) = G_CONSTANT i32 0
    %16:_(p0) = G_PTR_ADD %14, %15(s32)
    G_STORE %11(p0), %16(p0) :: (store (p0) into stack)
    $a2 = COPY %13(s32)
    $a3 = COPY %13(s32)
    $a4 = COPY %13(s32)
    $a5 = COPY %13(s32)
    $a6 = COPY %13(s32)
    $a7 = COPY %13(s32)
    CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
---
name:            alloca_variable_and_overaligned_call_stack_formal_stack_arg
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: _, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: _, preferred-register: '' }
  - { id: 7, class: _, preferred-register: '' }
  - { id: 8, class: _, preferred-register: '' }
  - { id: 9, class: _, preferred-register: '' }
  - { id: 10, class: _, preferred-register: '' }
  - { id: 11, class: _, preferred-register: '' }
  - { id: 12, class: _, preferred-register: '' }
  - { id: 13, class: _, preferred-register: '' }
  - { id: 14, class: _, preferred-register: '' }
  - { id: 15, class: _, preferred-register: '' }
  - { id: 16, class: _, preferred-register: '' }
  - { id: 17, class: _, preferred-register: '' }
  - { id: 18, class: _, preferred-register: '' }
  - { id: 19, class: _, preferred-register: '' }
  - { id: 20, class: _, preferred-register: '' }
  - { id: 21, class: _, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
  - { reg: '$a4', virtual-reg: '' }
  - { reg: '$a5', virtual-reg: '' }
  - { reg: '$a6', virtual-reg: '' }
  - { reg: '$a7', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    32
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:
  - { id: 0, type: default, offset: 0, size: 4, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
stack:
  - { id: 0, name: p1, type: variable-sized, offset: 0, alignment: 1, stack-id: default,
      callee-saved-register: '', callee-saved-restored: true, debug-info-variable: '',
      debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: p2, type: default, offset: 0, size: 32, alignment: 32,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3, $a4, $a5, $a6, $a7

    ; CHECK-LABEL: name: alloca_variable_and_overaligned_call_stack_formal_stack_arg
    ; CHECK: liveins: $a2, $a3, $a4, $a5, $a6, $a7
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:_(s32) = COPY $a4
    ; CHECK-NEXT: [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
    ; CHECK-NEXT: [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s32) from %fixed-stack.0, align 16)
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
    ; CHECK-NEXT: [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[MUL:%[0-9]+]]:_(s32) = G_MUL [[COPY]], [[C]]
    ; CHECK-NEXT: [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 15
    ; CHECK-NEXT: [[ADD:%[0-9]+]]:_(s32) = nuw G_ADD [[MUL]], [[C2]]
    ; CHECK-NEXT: [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 -16
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[ADD]], [[C3]]
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[PTRTOINT:%[0-9]+]]:_(s32) = G_PTRTOINT [[COPY3]](p0)
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[PTRTOINT]], [[AND]]
    ; CHECK-NEXT: [[INTTOPTR:%[0-9]+]]:_(p0) = G_INTTOPTR [[SUB]](s32)
    ; CHECK-NEXT: $a1 = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:_(p0) = COPY [[INTTOPTR]](p0)
    ; CHECK-NEXT: [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %stack.1.p2
    ; CHECK-NEXT: G_STORE [[COPY1]](s32), [[COPY4]](p0) :: (store (s8) into %ir.p1)
    ; CHECK-NEXT: G_STORE [[COPY2]](s32), [[FRAME_INDEX1]](p0) :: (store (s8) into %ir.p2)
    ; CHECK-NEXT: ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:_(p0) = COPY $a1
    ; CHECK-NEXT: [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY5]], [[C4]](s32)
    ; CHECK-NEXT: G_STORE [[COPY4]](p0), [[PTR_ADD]](p0) :: (store (p0) into stack)
    ; CHECK-NEXT: $a2 = COPY [[LOAD]](s32)
    ; CHECK-NEXT: $a3 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a4 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a5 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a6 = COPY [[C1]](s32)
    ; CHECK-NEXT: $a7 = COPY [[C1]](s32)
    ; CHECK-NEXT: CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ; CHECK-NEXT: ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    ; CHECK-NEXT: RETN implicit $a0
    %0:_(s32) = COPY $a2
    %7:_(s32) = COPY $a3
    %1:_(s8) = G_TRUNC %7(s32)
    %8:_(s32) = COPY $a4
    %2:_(s8) = G_TRUNC %8(s32)
    %9:_(p0) = G_FRAME_INDEX %fixed-stack.0
    %6:_(s32) = G_LOAD %9(p0) :: (load (s32) from %fixed-stack.0, align 16)
    %11:_(s32) = G_CONSTANT i32 1
    %18:_(s32) = G_CONSTANT i32 0
    %10:_(s32) = G_MUL %0, %11
    %12:_(s32) = G_CONSTANT i32 15
    %13:_(s32) = nuw G_ADD %10, %12
    %14:_(s32) = G_CONSTANT i32 -16
    %15:_(s32) = G_AND %13, %14
    %16:_(p0) = G_DYN_STACKALLOC %15(s32), 1
    %17:_(p0) = G_FRAME_INDEX %stack.1.p2
    G_STORE %1(s8), %16(p0) :: (store (s8) into %ir.p1)
    G_STORE %2(s8), %17(p0) :: (store (s8) into %ir.p2)
    ADJCALLSTACKDOWN 4, 0, implicit-def $a1, implicit $a1
    %19:_(p0) = COPY $a1
    %20:_(s32) = G_CONSTANT i32 0
    %21:_(p0) = G_PTR_ADD %19, %20(s32)
    G_STORE %16(p0), %21(p0) :: (store (p0) into stack)
    $a2 = COPY %6(s32)
    $a3 = COPY %18(s32)
    $a4 = COPY %18(s32)
    $a5 = COPY %18(s32)
    $a6 = COPY %18(s32)
    $a7 = COPY %18(s32)
    CALL0 @f2, csr_xtensa_call0, implicit-def $a0, implicit $a2, implicit $a3, implicit $a4, implicit $a5, implicit $a6, implicit $a7
    ADJCALLSTACKUP 4, 0, implicit-def $a1, implicit $a1
    RETN implicit $a0

...
