# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -O0 -mtriple=xtensa -run-pass=xtensa-shift-combiner -xtensashiftcombinerhelper-only-enable-rule=lower_set_sar_inrange -verify-machineinstrs %s -o - | FileCheck %s
--- |
  ; ModuleID = 'lower_set_sar_inrange.ll'
  source_filename = "lower_set_sar_inrange.ll"
  target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
  target triple = "xtensa"

  define i32 @shl_simple(i32 %a, i32 %b) {
    %shl = shl i32 %a, %b
    ret i32 %shl
  }

  define i32 @shr_simple(i32 %a, i32 %b) {
    %shr = lshr i32 %a, %b
    ret i32 %shr
  }

  define i32 @rev_shl(i32 %a, i32 %b) {
    %shamt = sub i32 32, %b
    %shl = shl i32 %a, %shamt
    ret i32 %shl
  }

  define i32 @rev_shr(i32 %a, i32 %b) {
    %shamt = sub i32 32, %b
    %shr = lshr i32 %a, %shamt
    ret i32 %shr
  }

  define i32 @rev_shl_masked(i32 %a, i32 %b) {
    %masked = and i32 %b, 31
    %shamt = sub i32 32, %masked
    %shl = shl i32 %a, %shamt
    ret i32 %shl
  }

  define i32 @rev_shr_masked(i32 %a, i32 %b) {
    %masked = and i32 %b, 31
    %shamt = sub i32 32, %masked
    %shr = lshr i32 %a, %shamt
    ret i32 %shr
  }

  define i32 @rev_shl_masked_small(i32 %a, i32 %b) {
    %masked = and i32 %b, 3
    %shamt = sub i32 32, %masked
    %shl = shl i32 %a, %shamt
    ret i32 %shl
  }

  define i32 @rev_shl_masked_weird(i32 %a, i32 %b) {
    %masked = and i32 %b, 9
    %shamt = sub i32 32, %masked
    %shl = shl i32 %a, %shamt
    ret i32 %shl
  }

...
---
name:            shl_simple
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shl_simple
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    G_XTENSA_SSL_INRANGE %1(s32), implicit-def $sar
    %2:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            shr_simple
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: shr_simple
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[COPY1]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    G_XTENSA_SSR_INRANGE %1(s32), implicit-def $sar
    %2:gpr(s32) = SRL %0(s32), implicit $sar
    $a2 = COPY %2(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shl
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shl
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C]], [[COPY1]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_SUB %2, %1
    G_XTENSA_SSL_INRANGE %3(s32), implicit-def $sar
    %4:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shr
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shr
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 32
    ; CHECK-NEXT: [[SUB:%[0-9]+]]:_(s32) = G_SUB [[C]], [[COPY1]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[SUB]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_SUB %2, %1
    G_XTENSA_SSR_INRANGE %3(s32), implicit-def $sar
    %4:gpr(s32) = SRL %0(s32), implicit $sar
    $a2 = COPY %4(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shl_masked
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shl_masked
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[AND]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 31
    %4:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_AND %1, %2
    %5:_(s32) = G_SUB %4, %3
    G_XTENSA_SSL_INRANGE %5(s32), implicit-def $sar
    %6:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %6(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shr_masked
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shr_masked
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 31
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSL_MASKED [[AND]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SRL:%[0-9]+]]:gpr(s32) = SRL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SRL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 31
    %4:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_AND %1, %2
    %5:_(s32) = G_SUB %4, %3
    G_XTENSA_SSR_INRANGE %5(s32), implicit-def $sar
    %6:gpr(s32) = SRL %0(s32), implicit $sar
    $a2 = COPY %6(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shl_masked_small
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shl_masked_small
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[AND]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 3
    %4:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_AND %1, %2
    %5:_(s32) = G_SUB %4, %3
    G_XTENSA_SSL_INRANGE %5(s32), implicit-def $sar
    %6:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %6(s32)
    RETN implicit $a0, implicit $a2

...
---
name:            rev_shl_masked_weird
alignment:       4
exposesReturnsTwice: false
legalized:       true
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
callsEHReturn:   false
callsUnwindInit: false
hasEHCatchret:   false
hasEHScopes:     false
hasEHFunclets:   false
failsVerification: false
tracksDebugUserValues: false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: _, preferred-register: '' }
  - { id: 2, class: _, preferred-register: '' }
  - { id: 3, class: _, preferred-register: '' }
  - { id: 4, class: _, preferred-register: '' }
  - { id: 5, class: _, preferred-register: '' }
  - { id: 6, class: gpr, preferred-register: '' }
liveins:
  - { reg: '$a2', virtual-reg: '' }
  - { reg: '$a3', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    1
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  functionContext: ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:      []
stack:           []
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.1 (%ir-block.0):
    liveins: $a2, $a3

    ; CHECK-LABEL: name: rev_shl_masked_weird
    ; CHECK: liveins: $a2, $a3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr(s32) = COPY $a2
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s32) = COPY $a3
    ; CHECK-NEXT: [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 9
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s32) = G_AND [[COPY1]], [[C]]
    ; CHECK-NEXT: G_XTENSA_SSR_MASKED [[AND]](s32), implicit-def $sar
    ; CHECK-NEXT: [[SLL:%[0-9]+]]:gpr(s32) = SLL [[COPY]](s32), implicit $sar
    ; CHECK-NEXT: $a2 = COPY [[SLL]](s32)
    ; CHECK-NEXT: RETN implicit $a0, implicit $a2
    %0:gpr(s32) = COPY $a2
    %1:_(s32) = COPY $a3
    %2:_(s32) = G_CONSTANT i32 9
    %4:_(s32) = G_CONSTANT i32 32
    %3:_(s32) = G_AND %1, %2
    %5:_(s32) = G_SUB %4, %3
    G_XTENSA_SSL_INRANGE %5(s32), implicit-def $sar
    %6:gpr(s32) = SLL %0(s32), implicit $sar
    $a2 = COPY %6(s32)
    RETN implicit $a0, implicit $a2

...
